/// <reference types='vitest' />
import angular from '@analogjs/vite-plugin-angular';
import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';
import { defineConfig } from 'vite';

/**
 * GENERATED by tools/generate-vite-configs.mjs. Regenerate rather than hand-editing.
 *
 * Shaped after what nx g @nx/angular:library --unitTestRunner=vitest-analog produces, so migrated projects match the
 * generators and the workspace keeps ONE convention instead of a migration-specific
 * one. Deviations from that base, each with its reason:
 *
 *   environment: 'happy-dom'  carried from this project's jest.config.ts so its DOM
 *                          surface does not change (FR-007). Nx defaults to jsdom.
 *   reporters / coverage   reproduce the CI artifacts the pipeline already consumes
 *                          (FR-008). Nx emits 'default' only.
 *   deps.inline            everything importing @angular/core must resolve to one
 *                          instance; without it components fail on 'ngModule' of
 *                          null. See the generator for the measurement.
 */
export default defineConfig(() => ({
    root: __dirname,
    cacheDir: '../../../node_modules/.vite/libs/portlets/dot-usage',
    // nxViteTsPaths(), NOT tsconfigPaths(). Nx prints a deprecation notice for this
    // plugin (removal in v24) and points at vite-tsconfig-paths — but the two are not
    // interchangeable in this workspace. nxViteTsPaths knows the Nx project layout and
    // resolves sibling libraries consumed FROM SOURCE, which a bare tsconfigPaths()
    // cannot: with it, edit-content runs 1,658 tests; without it, 0, because
    // "@dotcms/utils-testing" resolves and then fails to load from outside the project
    // root. Passing tsconfigPaths the workspace base tsconfig and widening
    // server.fs.allow were both tried and neither closed the gap.
    //
    // Follow-up, not a blocker: when Nx removes it in v24 this needs revisiting, and
    // Nx will have to offer a path for exactly this case.
    plugins: [angular(), nxViteTsPaths()],
    test: {
        name: 'portlets-dot-usage',
        watch: false,
        globals: true,
        environment: 'happy-dom',
        include: ['{src,tests}/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
        setupFiles: ['src/test-setup.ts'],
        server: {
            deps: {
                inline: [
                    /[\\/](libs|apps)[\\/]/,
                    /zone\.js/,
                    /@primeuix/,
                    /@analogjs\/vite-plugin-angular/,
                    /@angular\/animations/,
                    /@angular\/cdk/,
                    /@angular\/common/,
                    /@angular\/core/,
                    /@angular\/elements/,
                    /@angular\/forms/,
                    /@angular\/platform-browser/,
                    /@angular\/platform-browser-dynamic/,
                    /@angular\/router/,
                    /@materia-ui\/ngx-monaco-editor/,
                    /@ngrx\/component-store/,
                    /@ngrx\/signals/,
                    /@openng\/spectator/,
                    /@tinymce\/tinymce-angular/,
                    /ng-mocks/,
                    /ng2-dragula/,
                    /ngx-markdown/,
                    /ngx-tiptap/,
                    /primeng/
                ]
            }
        },
        reporters: [
            'default',
            'github-actions',
            ['junit', { outputFile: '../../../target/core-web-reports/portlets-dot-usage.xml' }]
        ],
        coverage: {
            reportsDirectory: '../../../coverage/libs/portlets/dot-usage',
            reporter: ['html', 'lcov', 'text'],
            provider: 'v8' as const
        }
    }
}));
