/// <reference types='vitest' />
import react from '@vitejs/plugin-react';
import tsconfigPaths from 'vite-tsconfig-paths';
import { defineConfig } from 'vite';

import { resolve } from 'path';

import { stubScss } from '../../../tools/vitest-stub-scss.mts';

/**
 * GENERATED by tools/generate-vite-configs.mjs. Regenerate rather than hand-editing.
 *
 * Shaped after what nx g @nx/react:library --unitTestRunner=vitest produces, so migrated projects match the
 * generators and the workspace keeps ONE convention instead of a migration-specific
 * one. Deviations from that base, each with its reason:
 *
 *   environment: 'jsdom'  carried from this project's jest.config.ts so its DOM
 *                          surface does not change (FR-007). Nx defaults to jsdom.
 *   reporters / coverage   reproduce the CI artifacts the pipeline already consumes
 *                          (FR-008). Nx emits 'default' only.
 *   deps.inline            everything importing @angular/core must resolve to one
 *                          instance; without it components fail on 'ngModule' of
 *                          null. See the generator for the measurement.
 */
export default defineConfig(() => ({
    root: __dirname,
    cacheDir: '../../../node_modules/.vite/libs/sdk/analytics',
    // tsconfigPaths(), with BOTH options supplied. Nx deprecated nxViteTsPaths (removal
    // in v24) and points here, and the two are interchangeable only if this plugin is
    // told where to look: a bare tsconfigPaths() resolves nothing across projects,
    // which is what made an earlier attempt report 0 tests for edit-content.
    //
    //   root      the workspace, not the project. Vite's own root is __dirname, so
    //             without this the plugin only sees this project's tsconfig and every
    //             `@dotcms/*` sibling stays unresolved.
    //   projects  tsconfig.base.json ONLY, and that is a fix rather than a
    //             simplification: nxViteTsPaths picked the project tsconfig by a fixed
    //             preference (app, else lib, else json) and never looked at
    //             tsconfig.spec.json, so sdk-experiments' build-only paths into dist/
    //             leaked into its test run and two spec files died on
    //             "Cannot find module '@dotcms/types'". Naming the base config takes
    //             the source paths and nothing else.
    plugins: [
        // Never let Vite load a SCSS preprocessor: sass-embedded's dart subprocess
        // outlives the run often enough to hang a task forever, and Jest compiled no
        // CSS at all. See tools/vitest-stub-scss.mts for the measurement.
        stubScss(),
        react(),
        tsconfigPaths({ root: resolve(__dirname, '../../..'), projects: ['tsconfig.base.json'] })
    ],
    test: {
        name: 'sdk-analytics',
        watch: false,
        globals: true,
        // Jest routed every .css/.scss/.sass/.less import through identity-obj-proxy
        // (@nx/jest/plugins/resolver), so a CSS-module class came back as its own name.
        // Vitest's default 'stable' strategy returns _name_hash instead, and
        // sdk-react's Column test — which asserts toHaveClass('col-start-2') on a class
        // read out of a *.module.css — failed on the hash. 'non-scoped' restores the
        // Jest reading.
        //
        // 'include: []' is load-bearing, not decoration: an object under 'css' turns CSS
        // PROCESSING on, and processing a .scss file starts sass-embedded, whose dart
        // subprocess outlives the run — content-drive finished all 30 files and then
        // hung indefinitely without printing a summary. An empty include leaves every
        // file unprocessed while the module-name strategy still applies.
        css: { include: [], modules: { classNameStrategy: 'non-scoped' } },
        // Explicit per research.md R-9: Jest gave every spec file a fresh module registry
        // and these specs were written under that. Measured exceptions live in NO_ISOLATE
        // in tools/generate-vite-configs.mjs.
        isolate: true,
        // The pool is a MEMORY decision here, not a speed one, and it is what makes this
        // suite fit a CI runner at all.
        //
        // With the default 'forks' pool, a worker keeps Vite's module graph and transform
        // cache for the whole run and reuses them across test files — that reuse is where
        // Vitest's speed comes from, and isolate only replaces the ENVIRONMENT per file,
        // never that cache. Angular makes the consequence extreme: the JIT compiler hangs
        // compiled definitions off the component classes held in that cache, so nothing is
        // released. Measured on dotcms-ui: one spec file peaks at 2.9GB and the same process
        // reaches 14.2GB after 226 of them. Jest never showed this because it drops its
        // module registry per test file — its workers stayed at 1.15GB each, so the same
        // total memory arrived in pieces a runner could schedule instead of one block that
        // has to fit whole. Frontend Unit Tests was killed three times for exactly this,
        // always mid-dotcms-ui, always a bare "The operation was canceled.".
        //
        // 'vmForks' gives each test file a fresh VM context, so module state does not
        // accumulate, and vmMemoryLimit caps what one of them may hold. Measured peak RSS of
        // a single process, same specs, all green:
        //
        //   dotcms-ui              14.2GB -> 2.16GB    (44s -> 38s)
        //   ui                     13.7GB -> 1.92GB
        //   edit-content           ~14GB  -> 1.68GB
        //   portlets-content-drive ~14GB  -> 2.72GB
        //
        // Faster as well as smaller, which is not the usual direction for an isolation
        // change. Ruled out first, each measured the same way: maxForks (14.2GB unchanged —
        // shrinking the count cannot shrink a block that size), 4-way sharding (13.3GB, the
        // cost is the graph rather than the file count), dropping the libs|apps deps.inline
        // entry (17.8GB, WORSE — Node then loads those sources separately), and happy-dom
        // instead of jsdom (9%).
        pool: 'forks',
        environment: 'jsdom',
        environmentOptions: { jsdom: { url: 'http://localhost/' } },
        include: ['{src,tests}/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
        server: {
            deps: {
                inline: [
                    /[\\/](libs|apps)[\\/]/,
                    /zone\.js/,
                    /@primeuix/,
                    /@analogjs\/vite-plugin-angular/,
                    /@angular\/animations/,
                    /@angular\/cdk/,
                    /@angular\/common/,
                    /@angular\/core/,
                    /@angular\/elements/,
                    /@angular\/forms/,
                    /@angular\/platform-browser/,
                    /@angular\/platform-browser-dynamic/,
                    /@angular\/router/,
                    /@materia-ui\/ngx-monaco-editor/,
                    /@ngrx\/component-store/,
                    /@ngrx\/signals/,
                    /@openng\/spectator/,
                    /@tinymce\/tinymce-angular/,
                    /ng-mocks/,
                    /ng2-dragula/,
                    /ngx-markdown/,
                    /ngx-tiptap/,
                    /primeng/
                ]
            }
        },
        // 'github-actions' is GATED, not dropped: an explicit reporters array replaces
        // Vitest's environment-based auto-selection, so deleting the entry would take
        // the CI annotations with it — while leaving it in emitted ::error commands on
        // every local run, where nothing parses them. junit stays unconditional; CI
        // consumes those XML files (generates_test_results in .github/test-matrix.yml).
        reporters: process.env.GITHUB_ACTIONS
            ? [
                  'default',
                  'github-actions',
                  ['junit', { outputFile: '../../../target/core-web-reports/sdk-analytics.xml' }]
              ]
            : [
                  'default',
                  ['junit', { outputFile: '../../../target/core-web-reports/sdk-analytics.xml' }]
              ],
        coverage: {
            reportsDirectory: '../../../coverage/libs/sdk/analytics',
            reporter: ['html', 'lcov', 'text'],
            provider: 'v8' as const
        }
    }
}));
