/// <reference types='vitest' />
import angular from '@analogjs/vite-plugin-angular';
import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';
import { defineConfig } from 'vite';

/**
 * GENERATED by tools/generate-vite-configs.mjs. Regenerate rather than hand-editing.
 *
 * Shaped after what nx g @nx/angular:library --unitTestRunner=vitest-analog produces, so migrated projects match the
 * generators and the workspace keeps ONE convention instead of a migration-specific
 * one. Deviations from that base, each with its reason:
 *
 *   environment: 'jsdom'  carried from this project's jest.config.ts so its DOM
 *                          surface does not change (FR-007). Nx defaults to jsdom.
 *   reporters / coverage   reproduce the CI artifacts the pipeline already consumes
 *                          (FR-008). Nx emits 'default' only.
 *   deps.inline            everything importing @angular/core must resolve to one
 *                          instance; without it components fail on 'ngModule' of
 *                          null. See the generator for the measurement.
 */
export default defineConfig(() => ({
    root: __dirname,
    cacheDir: '../../../../node_modules/.vite/libs/portlets/edit-ema/portlet',
    // nxViteTsPaths(), NOT tsconfigPaths(). Nx prints a deprecation notice for this
    // plugin (removal in v24) and points at vite-tsconfig-paths — but the two are not
    // interchangeable in this workspace. nxViteTsPaths knows the Nx project layout and
    // resolves sibling libraries consumed FROM SOURCE, which a bare tsconfigPaths()
    // cannot: with it, edit-content runs 1,658 tests; without it, 0, because
    // "@dotcms/utils-testing" resolves and then fails to load from outside the project
    // root. Passing tsconfigPaths the workspace base tsconfig and widening
    // server.fs.allow were both tried and neither closed the gap.
    //
    // Follow-up, not a blocker: when Nx removes it in v24 this needs revisiting, and
    // Nx will have to offer a path for exactly this case.
    plugins: [angular(), nxViteTsPaths()],
    test: {
        name: 'portlets-edit-ema-portlet',
        watch: false,
        globals: true,
        // Jest routed every .css/.scss/.sass/.less import through identity-obj-proxy
        // (@nx/jest/plugins/resolver), so a CSS-module class came back as its own name.
        // Vitest's default 'stable' strategy returns _name_hash instead, and
        // sdk-react's Column test — which asserts toHaveClass('col-start-2') on a class
        // read out of a *.module.css — failed on the hash. 'non-scoped' restores the
        // Jest reading.
        //
        // 'include: []' is load-bearing, not decoration: an object under 'css' turns CSS
        // PROCESSING on, and processing a .scss file starts sass-embedded, whose dart
        // subprocess outlives the run — content-drive finished all 30 files and then
        // hung indefinitely without printing a summary. An empty include leaves every
        // file unprocessed while the module-name strategy still applies.
        css: { include: [], modules: { classNameStrategy: 'non-scoped' } },
        environment: 'jsdom',
        environmentOptions: { jsdom: { url: 'http://localhost/' } },
        include: ['{src,tests}/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
        setupFiles: ['src/test-setup.ts'],
        server: {
            deps: {
                inline: [
                    /[\\/](libs|apps)[\\/]/,
                    /zone\.js/,
                    /@primeuix/,
                    /@analogjs\/vite-plugin-angular/,
                    /@angular\/animations/,
                    /@angular\/cdk/,
                    /@angular\/common/,
                    /@angular\/core/,
                    /@angular\/elements/,
                    /@angular\/forms/,
                    /@angular\/platform-browser/,
                    /@angular\/platform-browser-dynamic/,
                    /@angular\/router/,
                    /@materia-ui\/ngx-monaco-editor/,
                    /@ngrx\/component-store/,
                    /@ngrx\/signals/,
                    /@openng\/spectator/,
                    /@tinymce\/tinymce-angular/,
                    /ng-mocks/,
                    /ng2-dragula/,
                    /ngx-markdown/,
                    /ngx-tiptap/,
                    /primeng/,
                    /y-protocols/,
                    /lib0/,
                    /y-prosemirror/,
                    /@tiptap/,
                    /marked/,
                    /lowlight/,
                    /devlop/
                ]
            }
        },
        reporters: [
            'default',
            'github-actions',
            [
                'junit',
                { outputFile: '../../../../target/core-web-reports/portlets-edit-ema-portlet.xml' }
            ]
        ],
        coverage: {
            reportsDirectory: '../../../../coverage/libs/portlets/edit-ema/portlet',
            reporter: ['html', 'lcov', 'text'],
            provider: 'v8' as const
        }
    }
}));
