export enum ENUM_WORKFLOW_ACTIONS {
    NEW = 'NEW',
    EDIT = 'EDIT',
    PUBLISH = 'PUBLISH',
    UNPUBLISH = 'UNPUBLISH',
    ARCHIVE = 'ARCHIVE',
    UNARCHIVE = 'UNARCHIVE',
    DELETE = 'DELETE',
    DESTROY = 'DESTROY'
}

const NEW_WORKFLOW_ACTIONS = {
    name: 'new',
    id: ENUM_WORKFLOW_ACTIONS.NEW
};

const EDIT_WORKFLOW_ACTIONS = {
    name: 'edit',
    id: ENUM_WORKFLOW_ACTIONS.EDIT
};

const PUBLISH_WORKFLOW_ACTIONS = {
    name: 'publish',
    id: ENUM_WORKFLOW_ACTIONS.PUBLISH
};

const UNPUBLISH_WORKFLOW_ACTIONS = {
    name: 'unpublish',
    id: ENUM_WORKFLOW_ACTIONS.UNPUBLISH
};

const ARCHIVE_WORKFLOW_ACTIONS = {
    name: 'archive',
    id: ENUM_WORKFLOW_ACTIONS.ARCHIVE
};

const UNARCHIVE_WORKFLOW_ACTIONS = {
    name: 'unarchive',
    id: ENUM_WORKFLOW_ACTIONS.UNARCHIVE
};

const DELETE_WORKFLOW_ACTIONS = {
    name: 'delete',
    id: ENUM_WORKFLOW_ACTIONS.DELETE
};

const DESTROY_WORKFLOW_ACTIONS = {
    name: 'destroy',
    id: ENUM_WORKFLOW_ACTIONS.DESTROY
};

export const DEFAULT_WORKFLOW_ACTIONS = [
    NEW_WORKFLOW_ACTIONS,
    EDIT_WORKFLOW_ACTIONS,
    PUBLISH_WORKFLOW_ACTIONS,
    UNPUBLISH_WORKFLOW_ACTIONS,
    ARCHIVE_WORKFLOW_ACTIONS,
    UNARCHIVE_WORKFLOW_ACTIONS,
    DELETE_WORKFLOW_ACTIONS,
    DESTROY_WORKFLOW_ACTIONS
];
