import { OnboardingContent, SupportedFrameworks } from './models';

export const STORAGE_KEY = 'dotcmsDeveloperOnboarding';

export const getOnboardingContent = (selectedFramework: SupportedFrameworks): OnboardingContent => {
    return {
        title: 'Build Your First dotCMS Headless Application',
        description:
            'Choose a framework and configuration. The dotCMS CLI bootstraps your app, configures authentication, and enables visual editing in one minute',
        steps: [
            {
                number: 1,
                title: 'Bootstrap the project using the cli',
                description:
                    'Use the @dotcms/create-app CLI to scaffold a production-ready project that serves as the foundation for your headless application.',
                substeps: [
                    {
                        code:
                            'npx @dotcms/create-app@latest my-dotcms-app ' +
                            ' --framework=' +
                            selectedFramework +
                            ' --directory=<PROJECT_DIRECTORY>' +
                            ' --url=<DOTCMS_CLOUD_URL>' +
                            ' --username=<DOTCMS_USERNAME> ' +
                            ' --password=<DOTCMS_PASSWORD>',
                        language: 'bash',
                        type: 'terminal',
                        explanation: {
                            title: 'Create the project using create-dotcms-app cli',
                            description: `
                        The CLI connects to your dotCMS cloud instance ,sets up the UVE config, gets **Authentication Token** and **Site ID** using the below options:

                        \n- **--framework** : Specifies the frontend framework to use.
                        \n- **--directory** : Sets the project directory.
                        \n- **--url**: dotCMS Cloud instance URL.
                        \n- **--username**: dotCMS Cloud instance username.
                        \n- **--password**: dotCMS Cloud instance password.

                        \n⚠️ **Save the generated variables — once the terminal is cleared they are lost. Use --help for more options.**
                        `
                        }
                    },
                    {
                        code: '',
                        language: 'bash',
                        type: 'terminal',
                        explanation: {
                            title: 'Follow the instructions generated by the CLI to complete the setup.',
                            description:
                                'Once the cli scaffolds the project ,follow the CLI generated instructions to set env variables, install dependencies, and run the project.'
                        }
                    }
                    // {
                    //     code: 'cp .env.example .env',
                    //     language: 'bash',
                    //     type: 'terminal',
                    //     explanation: {
                    //         title: 'Replace the environment variables',
                    //         description: `Replace the generated project’s environment variables with the CLI-provided values. Following variables are required to connect your frontend to dotCMS :
                    //     \n- Authentication token
                    //     \n- Site identifier
                    //     \n- Cloud URL
                    //     `
                    //     }
                    // },
                    // {
                    //     code: 'npm install',
                    //     language: 'bash',
                    //     type: 'terminal',
                    //     explanation: {
                    //         title: 'Install the dependencies',
                    //         description: `Install the dependencies in the project.`
                    //     }
                    // },
                    // {
                    //     code: 'npm run dev',
                    //     language: 'bash',
                    //     type: 'terminal',
                    //     explanation: {
                    //         title: 'Start the development server',
                    //         description: `The development server will start and the app will be available at http://localhost:${portFrontEnd}. Keep this terminal running while developing.`
                    //     }
                    // }
                ]
            },
            //         {
            //             number: 2,
            //             title: 'Install dotCMS libraries',
            //             description:
            //                 'Install the official dotCMS SDK packages that enable your Next.js app to communicate with dotCMS and render content with full TypeScript support.',
            //             substeps: [
            //                 {
            //                     code: 'npm install @dotcms/client @dotcms/react @dotcms/types',
            //                     language: 'bash',
            //                     type: 'terminal',
            //                     explanation: {
            //                         title: 'Install dotCMS packages',
            //                         description: `- \`@dotcms/client\` - Handles authentication, API communication, and content fetching from dotCMS
            // - \`@dotcms/react\` - Provides React-specific hooks and components for rendering dotCMS content
            // - \`@dotcms/types\` - Provides TypeScript type definitions for dotCMS SDK`
            //                     }
            //                 }
            //             ]
            //         },
            //         {
            //             number: 3,
            //             title: 'Authenticate dotCMS (create your API Key)',
            //             description:
            //                 'Set up secure authentication between your Next.js app and dotCMS using a read-only API key and environment variables.',
            //             substeps: [
            //                 {
            //                     code: 'touch .env.local',
            //                     language: 'bash',
            //                     type: 'terminal',
            //                     explanation: {
            //                         title: 'Create .env.local file in project root',
            //                         description: `To generate your API key:
            // - Navigate to [**System** → **Users**](https://minstarter.dotcms.com/c/users) in your dotCMS instance
            // - Select your user account (e.g., \`admin@dotcms.com\`)
            // - Scroll to the **API Access Key** section
            // - Click **Generate** to create a new key (read-only permissions recommended)
            // - Copy the generated key - it will look something like: \`abcd1234efgh5678ijkl9012mnop3456\`
            //
            // **Important:** Save this key safely - you'll need it in the next step!
            //
            // For detailed instructions, refer to: [dotCMS REST API Authentication](https://dev.dotcms.com/docs/rest-api-authentication#ReadOnlyToken)`
            //                     }
            //                 },
            //                 {
            //                     code: `NEXT_PUBLIC_DOTCMS_URL=https://minstarter.dotcms.com
            // DOTCMS_TOKEN=your-api-key-here`,
            //                     language: 'env',
            //                     type: 'file',
            //                     filePath: '.env.local',
            //                     explanation: {
            //                         title: 'Add your dotCMS credentials',
            //                         description: `Replace \`your-api-key-here\` with the actual API Key you copied from dotCMS.
            //
            // - \`NEXT_PUBLIC_DOTCMS_URL\` - Available in both server and client components (needed for image URLs)
            //
            // - \`DOTCMS_TOKEN\` - Server-only (keeps your API key secure, never exposed to browser)`
            //                     }
            //                 }
            //             ]
            //         },
            //         {
            //             number: 4,
            //             title: 'Fetch content from dotCMS',
            //             description:
            //                 'Test your dotCMS connection by fetching page data and displaying it as JSON. Seeing the raw data helps you understand the structure of dotCMS content before rendering it visually.',
            //             substeps: [
            //                 {
            //                     code: `import { createDotCMSClient } from '@dotcms/client';
            //
            // // Create dotCMS client
            // const client = createDotCMSClient({
            //   dotcmsUrl: process.env.NEXT_PUBLIC_DOTCMS_URL!,
            //   authToken: process.env.DOTCMS_TOKEN,
            // });
            //
            // export default async function Home() {
            //   // Fetch page content from dotCMS
            //   const { pageAsset } = await client.page.get('/');
            //
            //   return (
            //     <div className="min-h-screen p-8">
            //       <h1 className="text-2xl font-bold mb-4">dotCMS Page Data</h1>
            //       <pre className="bg-gray-100 p-4 rounded overflow-auto text-xs">
            //         {JSON.stringify(pageAsset, null, 2)}
            //       </pre>
            //     </div>
            //   );
            // }`,
            //                     language: 'typescript',
            //                     type: 'file',
            //                     filePath: 'src/app/page.tsx',
            //                     explanation: {
            //                         title: 'Replace all content in the page component',
            //                         description: `- \`createDotCMSClient\` - Creates a configured client instance that can communicate with your dotCMS instance
            // - \`client.page.get('/')\` - Makes an API call to fetch the home page content (identified by path \`/\`)
            // - \`pageAsset\` - The complete page object containing all content, layout, and configuration data
            // - \`JSON.stringify\` - Converts the JavaScript object into readable JSON format for inspection`
            //                     }
            //                 }
            //             ]
            //         },
            //         {
            //             number: 5,
            //             title: 'Render content with DotCMSLayoutBody',
            //             description:
            //                 'Transform the raw JSON data into a beautiful, interactive page. You will create a client-side component that automatically maps dotCMS content types to React components.',
            //             substeps: [
            //                 {
            //                     code: 'mkdir -p src/components && touch src/components/DotCMSPageClient.tsx',
            //                     language: 'bash',
            //                     type: 'terminal',
            //                     explanation: {
            //                         title: 'Create components directory',
            //                         description: `We need a dedicated place for our client-side components.`
            //                     }
            //                 },
            //                 {
            //                     code: `'use client';
            //
            // import { DotCMSLayoutBody } from '@dotcms/react';
            // import type { DotCMSPageAsset } from '@dotcms/types';
            // import Image from 'next/image';
            //
            // // 1. Define the Banner Component
            // // This component matches the fields defined in your dotCMS "Banner" Content Type
            // function Banner({ title, caption, image, link, target }: any) {
            //   const dotcmsUrl = process.env.NEXT_PUBLIC_DOTCMS_URL;
            //   const imageUrl = image?.idPath ? \`\${dotcmsUrl}\${image.idPath}\` : null;
            //
            //   return (
            //     <div className="relative w-full bg-gray-900 text-white overflow-hidden min-h-[400px] flex items-center rounded-xl my-8">
            //       <div className="container mx-auto px-8 relative z-10">
            //         <div className="max-w-2xl">
            //           {title && <h1 className="text-5xl font-bold mb-6">{title}</h1>}
            //           {caption && <p className="text-xl mb-8 text-gray-200">{caption}</p>}
            //           {link && (
            //             <a href={link} target={target} className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-8 rounded transition-colors">
            //               Learn More
            //             </a>
            //           )}
            //         </div>
            //       </div>
            //       {imageUrl && (
            //         <div className="absolute inset-0 opacity-40">
            //           {/* 'unoptimized' allows loading images from external dotCMS domains without extra Next.js config */}
            //           <Image src={imageUrl} alt={title || 'Banner'} fill className="object-cover" unoptimized />
            //         </div>
            //       )}
            //     </div>
            //   );
            // }
            //
            // // 2. Create the Component Map
            // // Keys must EXACTLY match the Content Type Variable Name in dotCMS
            // const COMPONENTS_MAP = {
            //   Banner: Banner,
            // };
            //
            // // 3. Main Client Component
            // export function DotCMSPageClient({ pageAsset }: { pageAsset: DotCMSPageAsset }) {
            //   return (
            //     <DotCMSLayoutBody
            //       page={pageAsset}
            //       components={COMPONENTS_MAP}
            //     />
            //   );
            // }`,
            //                     language: 'typescript',
            //                     type: 'file',
            //                     filePath: 'src/components/DotCMSPageClient.tsx',
            //                     explanation: {
            //                         title: 'Create the Component Mapper',
            //                         description: `This file handles the logic of turning data into UI:
            //
            // - **Banner Component**: A standard React component. Note the \`unoptimized\` prop on the Image—this allows Next.js to display images from your specific dotCMS instance URL without complex configuration changes.
            // - **COMPONENTS_MAP**: This object tells the SDK "When you see content of type 'Banner', render this React component."
            // - **DotCMSLayoutBody**: The magic component from the SDK that iterates over the page layout and renders the correct components automatically.`
            //                     }
            //                 },
            //                 {
            //                     code: `import { createDotCMSClient } from '@dotcms/client';
            // import { DotCMSPageClient } from '@/components/DotCMSPageClient';
            //
            // const client = createDotCMSClient({
            //   dotcmsUrl: process.env.NEXT_PUBLIC_DOTCMS_URL!,
            //   authToken: process.env.DOTCMS_TOKEN,
            // });
            //
            // export default async function Home() {
            //   const { pageAsset } = await client.page.get('/');
            //
            //   return (
            //     <main className="container mx-auto px-4">
            //       <DotCMSPageClient pageAsset={pageAsset} />
            //     </main>
            //   );
            // }`,
            //                     language: 'typescript',
            //                     type: 'file',
            //                     filePath: 'src/app/page.tsx',
            //                     explanation: {
            //                         title: 'Update the Home Page',
            //                         description: `We replace the raw JSON dump with our new \`<DotCMSPageClient />\`.
            //
            // The server fetches the data securely, and the client component renders it. This "Hybrid" approach gives you the best of both worlds: SEO performance and interactive UI.`
            //                     }
            //                 }
            //             ]
            //         },
            //         {
            //             number: 6,
            //             title: 'Configure Universal Visual Editor',
            //             description:
            //                 'Now connect the two worlds. We need to tell dotCMS to load your local development environment (`localhost:3000`) inside its visual editor instead of the production site.',
            //             substeps: [
            //                 {
            //                     code: `{
            //   "config": [
            //     {
            //       "pattern": ".*",
            //       "url": "http://localhost:3000"
            //     }
            //   ]
            // }`, // No code needed, purely visual
            //                     language: 'json',
            //                     type: 'config', // UI placeholder
            //                     explanation: {
            //                         title: 'Open the Visual Editor',
            //                         description: `1. In dotCMS, navigate to **Settings > Apps** and click on **UVE - Universal Visual Editor**
            // 2. Click the plus button at the right of the site we're integrating (i.e., \`demo.dotcms.com\`).
            // 3. In the Configuration field, add the JSON object.`
            //                     }
            //                 }
            //             ]
            //         },
            {
                number: 2,
                title: 'Edit your page visually',
                description:
                    'The moment of truth. You will now edit content in dotCMS and see it update live in your Next.js application without touching the code.',
                substeps: [
                    {
                        code: '', // No code needed, purely visual
                        language: 'text',
                        type: 'terminal',
                        explanation: {
                            title: 'Open the Visual Editor',
                            description: `1. Go to **Site Browser** → **Pages** in the dotCMS sidebar.
2. Click on the **Home** page (index).
3. The screen will split: dotCMS controls on the right, your Next.js app on the left.
4. Click the **Edit** (pencil) icon on the top right.
5. Click directly on the **Banner** component in the preview.
6. Change the **Title** text and press **Save**.

Watch your Next.js app update instantly!`
                        }
                    }
                ]
            },
            {
                number: 3,
                title: `You Did It! Now what's next`,
                videoPath: `videopath`,
                description:
                    'Congratulations! You have successfully built a Headless Next.js app with full visual editing capabilities. You now have a workflow where developers build components in React, and editors manage content visually.Now it is time to build our custom component.'
            }
        ]
    };
};
