package com.dotmarketing.startup.runonce;

import com.dotmarketing.startup.AbstractJDBCStartupTask;

import java.util.List;

/**
 * Creates the new {@code system_event} table. The main goal of this table is to
 * store events generated by the system (i.e., notifications, errors,
 * information messages, etc.) that can be handled and interpreted by different
 * pieces of the application so they can react to them.
 * 
 * @author Jose Castro
 * @version 3.7
 * @since Jul 11, 2016
 */
public class Task03700AddingSystemEventTable extends AbstractJDBCStartupTask {

	@Override
	public boolean forceRun() {
		return true;
	}

	/**
	 * The SQL for Postgres
	 *
	 * @return
	 */
	@Override
	public String getPostgresScript () {
		return "CREATE TABLE system_event (\n" + 
				"identifier VARCHAR(36) NOT NULL,\n" +
				"event_type VARCHAR(50) NOT NULL,\n" +
				"payload LONGTEXT NOT NULL,\n" +
				"created BIGINT NOT NULL,\n" +
				"PRIMARY KEY (identifier)\n" +
			");\n" +
			"CREATE INDEX idx_system_event ON system_event (created);";
	}

	/**
	 * The SQL for MySQL
	 *
	 * @return
	 */
	@Override
	public String getMySQLScript () {
		return "CREATE TABLE system_event (\n" + 
					"identifier VARCHAR(36) NOT NULL,\n" +
					"event_type VARCHAR(50) NOT NULL,\n" +
					"payload LONGTEXT NOT NULL,\n" +
					"created BIGINT NOT NULL,\n" +
					"PRIMARY KEY (identifier)\n" +
				");\n" +
				"CREATE INDEX idx_system_event ON system_event (created);";
	}

	/**
	 * The SQL for Oracle
	 *
	 * @return
	 */
	@Override
	public String getOracleScript () {
		return "ALTER TABLE User_ ADD mod_date date null;";
	}

	/**
	 * The SQL for MSSQL
	 *
	 * @return
	 */
	@Override
	public String getMSSQLScript () {
		return "ALTER TABLE User_ ADD mod_date   datetime null;";
	}

	/**
	 * The SQL for H2
	 *
	 * @return
	 */
	@Override
	public String getH2Script () {
		return "ALTER TABLE User_ ADD COLUMN mod_date timestamp null;";
	}

	@Override
	protected List<String> getTablesToDropConstraints() {
		// Not required for this task
		return null;
	}

}
