import { DotContentDriveItem } from '@dotcms/dotcms-models';

export const mockItems: DotContentDriveItem[] = [
    {
        identifier: '123',
        title: 'Item 1 - Content',
        archived: false,
        baseType: 'CONTENT',
        contentType: 'content',
        folder: 'folder',
        live: true,
        modDate: new Date().toISOString(),
        modUserName: 'User 1',
        path: 'path',
        status: 'status',
        type: 'type',
        url: 'url',
        version: 1,
        versionType: 'versionType',
        hasTitleImage: false,
        host: 'host',
        hostName: 'hostName',
        inode: 'inode',
        languageId: 1,
        language: 'language',
        languageCode: 'languageCode',
        locked: false,
        modUser: 'modUser',
        owner: 'owner',
        sortOrder: 1,
        titleImage: 'titleImage',
        titleImageId: 'titleImageId',
        stInode: 'stInode1',
        working: true
    },
    {
        identifier: '456',
        title: 'Item 2 - File Asset',
        archived: false,
        baseType: 'FILEASSET',
        contentType: 'document',
        folder: 'documents',
        live: false,
        modDate: new Date().toISOString(),
        modUserName: 'User 2',
        path: '/documents/item2.pdf',
        status: 'draft',
        type: 'pdf',
        url: '/documents/item2.pdf',
        version: 2,
        versionType: 'draft',
        hasTitleImage: false,
        host: 'demo.dotcms.com',
        hostName: 'Demo Site',
        inode: 'inode456',
        languageId: 1,
        language: 'en-US',
        languageCode: 'en-us',
        locked: true,
        modUser: 'admin',
        owner: 'admin',
        sortOrder: 2,
        titleImage: '',
        titleImageId: '',
        stInode: 'stInode2',
        working: true,
        mimeType: 'application/pdf'
    },
    {
        identifier: '789',
        title: 'Item 3 - Dot Asset',
        archived: false,
        baseType: 'DOTASSET',
        contentType: 'image',
        folder: 'images',
        live: true,
        modDate: new Date().toISOString(),
        modUserName: 'User 3',
        path: '/images/item3.png',
        status: 'published',
        type: 'png',
        url: '/images/item3.png',
        version: 1,
        versionType: 'live',
        hasTitleImage: true,
        host: 'demo.dotcms.com',
        hostName: 'Demo Site',
        inode: 'inode789',
        languageId: 1,
        language: 'en-US',
        languageCode: 'en-us',
        locked: false,
        modUser: 'content-editor',
        owner: 'content-editor',
        sortOrder: 3,
        titleImage: '/images/item3.png',
        titleImageId: '789',
        stInode: 'stInode3',
        working: false,
        mimeType: 'image/png'
    },
    {
        identifier: '101112',
        title: 'Item 4 - Persona',
        archived: false,
        baseType: 'PERSONA',
        contentType: 'persona',
        folder: 'system',
        live: true,
        modDate: new Date().toISOString(),
        modUserName: 'Admin',
        path: '/personas/default-visitor',
        status: 'published',
        type: 'persona',
        url: '/personas/default-visitor',
        version: 1,
        versionType: 'live',
        hasTitleImage: false,
        host: 'demo.dotcms.com',
        hostName: 'Demo Site',
        inode: 'inode101112',
        languageId: 1,
        language: 'en-US',
        languageCode: 'en-us',
        locked: false,
        modUser: 'admin',
        owner: 'admin',
        sortOrder: 4,
        titleImage: '',
        titleImageId: '',
        stInode: 'stInode4',
        working: true,
        keyTag: 'dot:persona',
        name: 'Default Visitor',
        personalized: false
    },
    {
        identifier: '131415',
        title: 'Item 5 - Key Value',
        archived: false,
        baseType: 'KEY_VALUE',
        contentType: 'keyvalue',
        folder: 'config',
        live: true,
        modDate: new Date().toISOString(),
        modUserName: 'Admin',
        path: '/config/site-variables',
        status: 'published',
        type: 'keyvalue',
        url: '/config/site-variables',
        version: 1,
        versionType: 'live',
        hasTitleImage: false,
        host: 'demo.dotcms.com',
        hostName: 'Demo Site',
        inode: 'inode131415',
        languageId: 1,
        language: 'en-US',
        languageCode: 'en-us',
        locked: false,
        modUser: 'admin',
        owner: 'admin',
        sortOrder: 5,
        titleImage: '',
        titleImageId: '',
        stInode: 'stInode5',
        working: true,
        key: 'site.name',
        value: 'Demo Site'
    }
];
