name: dotcms-analytics

volumes:
  clickhouse-01-data:
  clickhouse-02-data:
  clickhouse-keeper-data:

services:
  clickhouse-keeper:
    image: clickhouse/clickhouse-keeper:25.8
    container_name: clickhouse-keeper
    ports:
      - "9181:9181"
    volumes:
      - ./conf/keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - clickhouse-keeper-data:/var/lib/clickhouse-keeper
    healthcheck:
      test: [ "CMD-SHELL", "clickhouse-keeper-client -h 127.0.0.1 -p 9181 -q 'ruok' 2>/dev/null | grep -q imok" ]
      interval: 5s
      timeout: 3s
      retries: 30

  clickhouse-01:
    image: clickhouse/clickhouse-server:25.8
    container_name: clickhouse-01
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./conf/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./conf/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ./conf/clickhouse-01/macros.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./init:/docker-entrypoint-initdb.d
      - clickhouse-01-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      clickhouse-keeper:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8123/ping | grep -q Ok" ]
      interval: 5s
      timeout: 3s
      retries: 30

  clickhouse-02:
    image: clickhouse/clickhouse-server:25.8
    container_name: clickhouse-02
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ./conf/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./conf/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ./conf/clickhouse-02/macros.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./init:/docker-entrypoint-initdb.d
      - clickhouse-02-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      clickhouse-keeper:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8123/ping | grep -q Ok" ]
      interval: 5s
      timeout: 3s
      retries: 30

  ca-event-manager:
    image: ghcr.io/dotcms/dot-ca-event-manager:latest
    container_name: ca-event-manager
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - ANALYTICS_ASYNC_INSERT_TIMEOUT_MS=200
      - ANALYTICS_ASYNC_INSERT_MAX_DATA_SIZE=104857600
      - CLICKHOUSE_URL=jdbc:clickhouse://clickhouse-01:8123/analytics?async_insert=1&wait_for_async_insert=1&async_insert_busy_timeout_ms=${ANALYTICS_ASYNC_INSERT_TIMEOUT_MS:-200}&async_insert_max_data_size=${ANALYTICS_ASYNC_INSERT_MAX_DATA_SIZE:-104857600}
      - ANALYTICS_CH_PROBE_USR=${ANALYTICS_CH_PROBE_USR:-admin}
      - ANALYTICS_CH_PROBE_PWD=${ANALYTICS_CH_PROBE_PWD:-admin}
    ports:
      - "8082:8080"
    depends_on:
      clickhouse-01:
        condition: service_healthy
