System.config({
  "baseURL": "/",
  "transpiler": "traceur",
  "traceurOptions": {
    "annotations": true,
    "memberVariables": true,
    "typeAssertions": true,
    "typeAssertionModule": "rtts_assert/rtts_assert",
    "types": true
  },
  "paths": {
    "src/*": "src/*",
    "*.css": "*.css",
    "*.html": "*.html",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js",
    "angular2/*": "thirdparty/ng2dist/js/prod/es6/angular2/*.es6",
    "rtts_assert/*": "thirdparty/ng2dist/js/prod/es6/rtts_assert/*.es6",
    "*": "*.js"
  },
  "bundles": {
    "jspm_bundles/core-web.min": [
      "rtts_assert/src/rtts_assert",
      "npm:ms@0.7.1/index",
      "npm:base64-js@0.0.8/lib/b64",
      "npm:ieee754@1.1.5/index",
      "npm:is-array@1.0.1/index",
      "npm:process@0.10.1/browser",
      "npm:inherits@2.0.1/inherits_browser",
      "npm:create-hash@1.1.1/helpers",
      "npm:ripemd160@1.0.1/lib/ripemd160",
      "npm:sha.js@2.4.2/hash",
      "npm:sha.js@2.4.2/sha1",
      "npm:sha.js@2.4.2/sha256",
      "npm:sha.js@2.4.2/sha512",
      "npm:events@1.0.2/events",
      "npm:isarray@0.0.1/index",
      "npm:core-util-is@1.0.1/lib/util",
      "npm:readable-stream@1.1.13/lib/_stream_writable",
      "npm:string_decoder@0.10.31/index",
      "npm:readable-stream@1.1.13/lib/_stream_transform",
      "npm:readable-stream@1.1.13/lib/_stream_passthrough",
      "npm:readable-stream@1.1.13/writable",
      "npm:readable-stream@1.1.13/duplex",
      "npm:readable-stream@1.1.13/transform",
      "npm:readable-stream@1.1.13/passthrough",
      "npm:create-hmac@1.1.3/browser",
      "npm:browserify-sign@3.0.2/algos",
      "npm:pbkdf2@3.0.4/browser",
      "npm:browserify-aes@1.0.1/aes",
      "npm:browserify-aes@1.0.1/cipherBase",
      "npm:browserify-aes@1.0.1/modes",
      "npm:browserify-aes@1.0.1/EVP_BytesToKey",
      "npm:browserify-aes@1.0.1/streamCipher",
      "npm:browserify-aes@1.0.1/ghash",
      "npm:browserify-aes@1.0.1/xor",
      "npm:browserify-aes@1.0.1/modes/ecb",
      "npm:browserify-aes@1.0.1/modes/cbc",
      "npm:browserify-aes@1.0.1/modes/cfb",
      "npm:browserify-aes@1.0.1/modes/cfb8",
      "npm:browserify-aes@1.0.1/modes/cfb1",
      "npm:browserify-aes@1.0.1/modes/ofb",
      "npm:browserify-aes@1.0.1/modes/ctr",
      "npm:browserify-aes@1.0.1/decrypter",
      "npm:bn.js@2.0.5/lib/bn",
      "npm:brorand@1.0.5/index",
      "npm:diffie-hellman@3.0.2/lib/primes.json!github:systemjs/plugin-json@0.1.0",
      "npm:diffie-hellman@3.0.2/lib/dh",
      "npm:indexof@0.0.1/index",
      "npm:asn1.js@2.0.3/lib/asn1/base/reporter",
      "npm:asn1.js@2.0.3/lib/asn1/base/buffer",
      "npm:minimalistic-assert@1.0.0/index",
      "npm:asn1.js@2.0.3/lib/asn1/constants/der",
      "npm:asn1.js@2.0.3/lib/asn1/decoders/der",
      "npm:asn1.js@2.0.3/lib/asn1/encoders/der",
      "npm:parse-asn1@3.0.1/aesid.json!github:systemjs/plugin-json@0.1.0",
      "npm:parse-asn1@3.0.1/EVP_BytesToKey",
      "npm:elliptic@3.0.4/package.json!github:systemjs/plugin-json@0.1.0",
      "npm:elliptic@3.0.4/lib/elliptic/utils",
      "npm:hash.js@1.0.3/lib/hash/utils",
      "npm:hash.js@1.0.3/lib/hash/common",
      "npm:hash.js@1.0.3/lib/hash/sha",
      "npm:hash.js@1.0.3/lib/hash/ripemd",
      "npm:hash.js@1.0.3/lib/hash/hmac",
      "npm:elliptic@3.0.4/lib/elliptic/curve/base",
      "npm:elliptic@3.0.4/lib/elliptic/curve/short",
      "npm:elliptic@3.0.4/lib/elliptic/curve/mont",
      "npm:elliptic@3.0.4/lib/elliptic/curve/edwards",
      "npm:elliptic@3.0.4/lib/elliptic/precomputed/secp256k1",
      "npm:elliptic@3.0.4/lib/elliptic/ec/key",
      "npm:elliptic@3.0.4/lib/elliptic/ec/signature",
      "npm:browserify-rsa@2.0.1/index",
      "npm:browserify-sign@3.0.2/curves",
      "npm:browserify-sign@3.0.2/verify",
      "npm:create-ecdh@2.0.1/browser",
      "npm:public-encrypt@2.0.1/mgf",
      "npm:public-encrypt@2.0.1/xor",
      "npm:public-encrypt@2.0.1/withPublic",
      "npm:public-encrypt@2.0.1/privateDecrypt",
      "angular2/src/facade/lang",
      "angular2/src/facade/collection",
      "angular2/src/di/annotations",
      "angular2/src/reflection/types",
      "angular2/src/reflection/reflection_capabilities",
      "angular2/src/di/key",
      "angular2/src/di/exceptions",
      "npm:rx@2.5.3/dist/rx",
      "npm:rx@2.5.3/dist/rx.aggregates",
      "npm:rx@2.5.3/dist/rx.async",
      "npm:rx@2.5.3/dist/rx.backpressure",
      "npm:rx@2.5.3/dist/rx.binding",
      "npm:rx@2.5.3/dist/rx.coincidence",
      "npm:rx@2.5.3/dist/rx.experimental",
      "npm:rx@2.5.3/dist/rx.joinpatterns",
      "npm:rx@2.5.3/dist/rx.sorting",
      "npm:rx@2.5.3/dist/rx.virtualtime",
      "npm:rx@2.5.3/dist/rx.testing",
      "npm:rx@2.5.3/dist/rx.time",
      "angular2/src/di/opaque_token",
      "angular2/src/change_detection/parser/parser",
      "angular2/src/change_detection/parser/locals",
      "angular2/src/change_detection/constants",
      "angular2/src/change_detection/interfaces",
      "angular2/src/change_detection/pipes/pipe",
      "angular2/src/change_detection/change_detector_ref",
      "angular2/src/change_detection/pipes/pipe_registry",
      "angular2/src/change_detection/change_detection_jit_generator",
      "angular2/src/change_detection/coalesce",
      "angular2/src/change_detection/pipes/iterable_changes",
      "angular2/src/change_detection/pipes/keyvalue_changes",
      "angular2/src/change_detection/pipes/async_pipe",
      "angular2/src/change_detection/pipes/null_pipe",
      "angular2/src/core/annotations_impl/visibility",
      "angular2/src/core/compiler/interfaces",
      "angular2/src/core/annotations_impl/view",
      "angular2/src/dom/dom_adapter",
      "angular2/src/dom/generic_browser_adapter",
      "angular2/src/core/annotations_impl/annotations",
      "angular2/src/core/compiler/directive_metadata",
      "angular2/src/facade/math",
      "angular2/src/core/annotations_impl/di",
      "angular2/src/render/api",
      "angular2/src/render/dom/view/view_container",
      "angular2/src/render/dom/view/element_binder",
      "angular2/src/render/dom/util",
      "angular2/src/render/dom/shadow_dom/content_tag",
      "angular2/src/render/dom/shadow_dom/shadow_dom_strategy",
      "angular2/src/core/zone/vm_turn_zone",
      "angular2/src/render/dom/view/view_hydrator",
      "angular2/src/render/dom/view/property_setter_factory",
      "angular2/src/render/dom/compiler/compile_step",
      "angular2/src/services/xhr",
      "angular2/src/services/url_resolver",
      "angular2/src/render/dom/compiler/property_binding_parser",
      "angular2/src/render/dom/compiler/text_interpolation_parser",
      "angular2/src/render/dom/compiler/selector",
      "angular2/src/render/dom/compiler/view_splitter",
      "angular2/src/render/dom/shadow_dom/shadow_dom_compile_step",
      "angular2/src/core/compiler/view_container_ref",
      "angular2/src/core/compiler/view_manager_utils",
      "angular2/src/core/compiler/view_pool",
      "angular2/src/core/compiler/base_query_list",
      "angular2/src/core/compiler/element_binder",
      "angular2/src/core/compiler/template_resolver",
      "angular2/src/core/compiler/component_url_mapper",
      "angular2/src/core/compiler/proto_view_factory",
      "angular2/src/core/exception_handler",
      "angular2/src/core/life_cycle/life_cycle",
      "angular2/src/render/dom/shadow_dom/style_url_resolver",
      "angular2/src/render/dom/shadow_dom/shadow_css",
      "angular2/src/services/xhr_impl",
      "angular2/src/render/dom/events/key_events",
      "angular2/src/render/dom/events/hammer_common",
      "angular2/src/render/dom/shadow_dom/style_inliner",
      "angular2/src/core/compiler/dynamic_component_loader",
      "angular2/src/core/testability/get_testability",
      "angular2/src/core/application_tokens",
      "angular2/src/core/annotations/di",
      "angular2/src/render/dom/shadow_dom/native_shadow_dom_strategy",
      "angular2/src/render/dom/shadow_dom/emulated_scoped_shadow_dom_strategy",
      "angular2/src/core/annotations/annotations",
      "angular2/src/core/decorators/decorators",
      "angular2/src/directives/class",
      "angular2/src/directives/for",
      "angular2/src/directives/if",
      "angular2/src/directives/non_bindable",
      "angular2/src/directives/switch",
      "angular2/src/forms/validators",
      "angular2/src/forms/directives",
      "angular2/src/forms/validator_directives",
      "angular2/src/forms/form_builder",
      "src/dc/api/Core.ts",
      "src/dc/log-config.es6",
      "src/entity-forge/Verify.es6",
      "src/rules-engine/datamocks/rule.mocks.es6",
      "npm:flux@2.0.3/lib/invariant",
      "src/rules-engine/actions/RuleEngineActionCreators.es6",
      "src/entity-forge/Validation.es6",
      "src/entity-forge/EntityBaseTypes.es6",
      "src/rules-engine/stores/RuleEngineStore.ts",
      "github:twbs/bootstrap@3.3.4/css/bootstrap.css!github:systemjs/plugin-css@0.1.12",
      "src/rules-engine-ng2/app/styles/rules-engine.css!github:systemjs/plugin-css@0.1.12",
      "src/rules-engine-ng2/app/styles/theme-dark.css!github:systemjs/plugin-css@0.1.12",
      "src/rules-engine-ng2/app/rules-engine-ng2.html!github:systemjs/plugin-text@0.0.2",
      "src/rules-engine-ng2/app/rule.tpl.html!github:systemjs/plugin-text@0.0.2",
      "src/rules-engine-ng2/app/rule-action.tpl.html!github:systemjs/plugin-text@0.0.2",
      "src/rules-engine-ng2/app/clause-group.tpl.html!github:systemjs/plugin-text@0.0.2",
      "src/rules-engine-ng2/app/clause.tpl.html!github:systemjs/plugin-text@0.0.2",
      "rtts_assert/rtts_assert",
      "npm:ms@0.7.1",
      "npm:base64-js@0.0.8",
      "npm:ieee754@1.1.5",
      "npm:is-array@1.0.1",
      "npm:process@0.10.1",
      "npm:inherits@2.0.1",
      "npm:create-hash@1.1.1/md5",
      "npm:ripemd160@1.0.1",
      "npm:sha.js@2.4.2/sha",
      "npm:sha.js@2.4.2/sha224",
      "npm:sha.js@2.4.2/sha384",
      "npm:events@1.0.2",
      "npm:isarray@0.0.1",
      "npm:core-util-is@1.0.1",
      "npm:readable-stream@1.1.13/lib/_stream_duplex",
      "npm:string_decoder@0.10.31",
      "npm:create-hmac@1.1.3",
      "npm:pbkdf2@3.0.4",
      "npm:browserify-aes@1.0.1/authCipher",
      "npm:bn.js@2.0.5",
      "npm:brorand@1.0.5",
      "npm:indexof@0.0.1",
      "npm:minimalistic-assert@1.0.0",
      "npm:asn1.js@2.0.3/lib/asn1/constants/index",
      "npm:asn1.js@2.0.3/lib/asn1/decoders/index",
      "npm:asn1.js@2.0.3/lib/asn1/encoders/index",
      "npm:parse-asn1@3.0.1/fixProc",
      "npm:hash.js@1.0.3/lib/hash",
      "npm:elliptic@3.0.4/lib/elliptic/curve/index",
      "npm:elliptic@3.0.4/lib/elliptic/curves",
      "npm:elliptic@3.0.4/lib/elliptic/ec/index",
      "npm:browserify-rsa@2.0.1",
      "npm:create-ecdh@2.0.1/index",
      "npm:public-encrypt@2.0.1/publicEncrypt",
      "angular2/src/change_detection/parser/ast",
      "angular2/src/reflection/reflector",
      "npm:rx@2.5.3/index",
      "angular2/src/change_detection/directive_record",
      "angular2/src/change_detection/change_detection_util",
      "angular2/src/change_detection/abstract_change_detector",
      "angular2/src/change_detection/change_detection",
      "angular2/src/core/annotations/visibility",
      "angular2/src/core/annotations/view",
      "angular2/src/dom/browser_adapter",
      "angular2/src/core/compiler/directive_metadata_reader",
      "angular2/src/core/compiler/view_ref",
      "angular2/src/render/dom/view/proto_view",
      "angular2/src/render/dom/shadow_dom/light_dom",
      "angular2/src/render/dom/events/event_manager",
      "angular2/src/render/dom/view/proto_view_builder",
      "angular2/src/render/dom/compiler/compile_control",
      "angular2/src/render/dom/compiler/template_loader",
      "angular2/src/render/dom/compiler/directive_parser",
      "angular2/src/core/compiler/query_list",
      "angular2/src/render/dom/shadow_dom/util",
      "angular2/src/render/dom/events/hammer_gestures",
      "angular2/src/core/testability/testability",
      "angular2/annotations",
      "angular2/directives",
      "angular2/src/forms/model",
      "src/dc/api/Check.ts",
      "npm:flux@2.0.3/lib/Dispatcher",
      "src/entity-forge/EntityForge.es6",
      "npm:debug@2.2.0/debug",
      "npm:buffer@3.2.2/index",
      "github:jspm/nodelibs-process@0.1.1/index",
      "npm:sha.js@2.4.2/index",
      "github:jspm/nodelibs-events@0.1.1/index",
      "npm:readable-stream@1.1.13/lib/_stream_readable",
      "npm:browserify-aes@1.0.1/encrypter",
      "npm:miller-rabin@2.0.1/lib/mr",
      "npm:vm-browserify@0.0.4/index",
      "npm:asn1.js@2.0.3/lib/asn1/base/node",
      "npm:hash.js@1.0.3",
      "npm:create-ecdh@2.0.1",
      "npm:public-encrypt@2.0.1/browser",
      "angular2/src/reflection/reflection",
      "npm:rx@2.5.3",
      "angular2/src/change_detection/binding_record",
      "angular2/src/change_detection/dynamic_change_detector",
      "angular2/src/render/dom/view/view",
      "angular2/src/render/dom/view/view_factory",
      "angular2/src/render/dom/compiler/compile_element",
      "angular2/src/render/dom/compiler/compile_step_factory",
      "angular2/src/render/dom/shadow_dom/emulated_unscoped_shadow_dom_strategy",
      "angular2/forms",
      "src/dc/index.es6",
      "npm:flux@2.0.3/index",
      "src/rules-engine/api/RuleEngineTypes.es6",
      "npm:debug@2.2.0/browser",
      "npm:buffer@3.2.2",
      "github:jspm/nodelibs-process@0.1.1",
      "npm:sha.js@2.4.2",
      "github:jspm/nodelibs-events@0.1.1",
      "npm:readable-stream@1.1.13/readable",
      "npm:browserify-aes@1.0.1/browser",
      "npm:miller-rabin@2.0.1",
      "npm:vm-browserify@0.0.4",
      "npm:asn1.js@2.0.3/lib/asn1/base/index",
      "npm:elliptic@3.0.4/lib/elliptic/hmac-drbg",
      "npm:public-encrypt@2.0.1",
      "angular2/src/di/binding",
      "angular2/src/facade/async",
      "angular2/src/change_detection/proto_record",
      "angular2/src/change_detection/proto_change_detector",
      "angular2/src/render/dom/compiler/compile_pipeline",
      "npm:flux@2.0.3",
      "npm:debug@2.2.0",
      "github:jspm/nodelibs-buffer@0.1.0/index",
      "npm:stream-browserify@1.0.0/index",
      "npm:browserify-aes@1.0.1",
      "npm:diffie-hellman@3.0.2/lib/generatePrime",
      "github:jspm/nodelibs-vm@0.1.0/index",
      "npm:elliptic@3.0.4/lib/elliptic",
      "angular2/src/di/injector",
      "angular2/src/change_detection/exceptions",
      "angular2/src/render/dom/compiler/compiler",
      "src/rules-engine/dispatcher/AppDispatcher.ts",
      "github:jspm/nodelibs-buffer@0.1.0",
      "npm:stream-browserify@1.0.0",
      "npm:diffie-hellman@3.0.2/browser",
      "github:jspm/nodelibs-vm@0.1.0",
      "npm:elliptic@3.0.4",
      "angular2/di",
      "angular2/src/render/dom/direct_dom_renderer",
      "src/rules-engine/api/RuleEngineAPI.ts",
      "npm:randombytes@2.0.1/browser",
      "github:jspm/nodelibs-stream@0.1.0/index",
      "npm:diffie-hellman@3.0.2",
      "npm:asn1.js@2.0.3/lib/asn1/api",
      "angular2/src/change_detection/parser/lexer",
      "angular2/src/core/compiler/element_ref",
      "src/rules-engine/RuleEngine.es6",
      "npm:randombytes@2.0.1",
      "github:jspm/nodelibs-stream@0.1.0",
      "npm:asn1.js@2.0.3/lib/asn1",
      "angular2/change_detection",
      "angular2/src/core/compiler/view_manager",
      "npm:create-hash@1.1.1/browser",
      "npm:asn1.js@2.0.3",
      "angular2/src/core/compiler/element_injector",
      "npm:create-hash@1.1.1",
      "npm:parse-asn1@3.0.1/asn1",
      "angular2/src/core/compiler/view",
      "npm:parse-asn1@3.0.1/index",
      "angular2/src/core/compiler/compiler",
      "npm:parse-asn1@3.0.1",
      "angular2/src/core/application",
      "npm:browserify-sign@3.0.2/sign",
      "angular2/core",
      "npm:browserify-sign@3.0.2/browser",
      "angular2/angular2",
      "npm:browserify-sign@3.0.2",
      "npm:crypto-browserify@3.9.14/index",
      "npm:crypto-browserify@3.9.14",
      "github:jspm/nodelibs-crypto@0.1.0/index",
      "github:jspm/nodelibs-crypto@0.1.0",
      "npm:reflect-metadata@0.1.0/Reflect",
      "npm:reflect-metadata@0.1.0",
      "src/rules-engine-ng2/app/rules-engine-ng2.ts",
      "src/rules-engine-ng2/index.es6"
    ],
    "jspm_bundles/core-web": [
      "rtts_assert/src/rtts_assert",
      "npm:ms@0.7.1/index",
      "npm:base64-js@0.0.8/lib/b64",
      "npm:ieee754@1.1.5/index",
      "npm:is-array@1.0.1/index",
      "npm:process@0.10.1/browser",
      "npm:inherits@2.0.1/inherits_browser",
      "npm:create-hash@1.1.1/helpers",
      "npm:ripemd160@1.0.1/lib/ripemd160",
      "npm:sha.js@2.4.2/hash",
      "npm:sha.js@2.4.2/sha1",
      "npm:sha.js@2.4.2/sha256",
      "npm:sha.js@2.4.2/sha512",
      "npm:events@1.0.2/events",
      "npm:isarray@0.0.1/index",
      "npm:core-util-is@1.0.1/lib/util",
      "npm:readable-stream@1.1.13/lib/_stream_writable",
      "npm:string_decoder@0.10.31/index",
      "npm:readable-stream@1.1.13/lib/_stream_transform",
      "npm:readable-stream@1.1.13/lib/_stream_passthrough",
      "npm:readable-stream@1.1.13/writable",
      "npm:readable-stream@1.1.13/duplex",
      "npm:readable-stream@1.1.13/transform",
      "npm:readable-stream@1.1.13/passthrough",
      "npm:create-hmac@1.1.3/browser",
      "npm:browserify-sign@3.0.2/algos",
      "npm:pbkdf2@3.0.4/browser",
      "npm:browserify-aes@1.0.1/aes",
      "npm:browserify-aes@1.0.1/cipherBase",
      "npm:browserify-aes@1.0.1/modes",
      "npm:browserify-aes@1.0.1/EVP_BytesToKey",
      "npm:browserify-aes@1.0.1/streamCipher",
      "npm:browserify-aes@1.0.1/ghash",
      "npm:browserify-aes@1.0.1/xor",
      "npm:browserify-aes@1.0.1/modes/ecb",
      "npm:browserify-aes@1.0.1/modes/cbc",
      "npm:browserify-aes@1.0.1/modes/cfb",
      "npm:browserify-aes@1.0.1/modes/cfb8",
      "npm:browserify-aes@1.0.1/modes/cfb1",
      "npm:browserify-aes@1.0.1/modes/ofb",
      "npm:browserify-aes@1.0.1/modes/ctr",
      "npm:browserify-aes@1.0.1/decrypter",
      "npm:bn.js@2.0.5/lib/bn",
      "npm:brorand@1.0.5/index",
      "npm:diffie-hellman@3.0.2/lib/primes.json!github:systemjs/plugin-json@0.1.0",
      "npm:diffie-hellman@3.0.2/lib/dh",
      "npm:indexof@0.0.1/index",
      "npm:asn1.js@2.0.3/lib/asn1/base/reporter",
      "npm:asn1.js@2.0.3/lib/asn1/base/buffer",
      "npm:minimalistic-assert@1.0.0/index",
      "npm:asn1.js@2.0.3/lib/asn1/constants/der",
      "npm:asn1.js@2.0.3/lib/asn1/decoders/der",
      "npm:asn1.js@2.0.3/lib/asn1/encoders/der",
      "npm:parse-asn1@3.0.1/aesid.json!github:systemjs/plugin-json@0.1.0",
      "npm:parse-asn1@3.0.1/EVP_BytesToKey",
      "npm:elliptic@3.0.4/package.json!github:systemjs/plugin-json@0.1.0",
      "npm:elliptic@3.0.4/lib/elliptic/utils",
      "npm:hash.js@1.0.3/lib/hash/utils",
      "npm:hash.js@1.0.3/lib/hash/common",
      "npm:hash.js@1.0.3/lib/hash/sha",
      "npm:hash.js@1.0.3/lib/hash/ripemd",
      "npm:hash.js@1.0.3/lib/hash/hmac",
      "npm:elliptic@3.0.4/lib/elliptic/curve/base",
      "npm:elliptic@3.0.4/lib/elliptic/curve/short",
      "npm:elliptic@3.0.4/lib/elliptic/curve/mont",
      "npm:elliptic@3.0.4/lib/elliptic/curve/edwards",
      "npm:elliptic@3.0.4/lib/elliptic/precomputed/secp256k1",
      "npm:elliptic@3.0.4/lib/elliptic/ec/key",
      "npm:elliptic@3.0.4/lib/elliptic/ec/signature",
      "npm:browserify-rsa@2.0.1/index",
      "npm:browserify-sign@3.0.2/curves",
      "npm:browserify-sign@3.0.2/verify",
      "npm:create-ecdh@2.0.1/browser",
      "npm:public-encrypt@2.0.1/mgf",
      "npm:public-encrypt@2.0.1/xor",
      "npm:public-encrypt@2.0.1/withPublic",
      "npm:public-encrypt@2.0.1/privateDecrypt",
      "angular2/src/facade/lang",
      "angular2/src/facade/collection",
      "angular2/src/di/annotations",
      "angular2/src/reflection/types",
      "angular2/src/reflection/reflection_capabilities",
      "angular2/src/di/key",
      "angular2/src/di/exceptions",
      "npm:rx@2.5.3/dist/rx",
      "npm:rx@2.5.3/dist/rx.aggregates",
      "npm:rx@2.5.3/dist/rx.async",
      "npm:rx@2.5.3/dist/rx.backpressure",
      "npm:rx@2.5.3/dist/rx.binding",
      "npm:rx@2.5.3/dist/rx.coincidence",
      "npm:rx@2.5.3/dist/rx.experimental",
      "npm:rx@2.5.3/dist/rx.joinpatterns",
      "npm:rx@2.5.3/dist/rx.sorting",
      "npm:rx@2.5.3/dist/rx.virtualtime",
      "npm:rx@2.5.3/dist/rx.testing",
      "npm:rx@2.5.3/dist/rx.time",
      "angular2/src/di/opaque_token",
      "angular2/src/change_detection/parser/parser",
      "angular2/src/change_detection/parser/locals",
      "angular2/src/change_detection/constants",
      "angular2/src/change_detection/interfaces",
      "angular2/src/change_detection/pipes/pipe",
      "angular2/src/change_detection/change_detector_ref",
      "angular2/src/change_detection/pipes/pipe_registry",
      "angular2/src/change_detection/change_detection_jit_generator",
      "angular2/src/change_detection/coalesce",
      "angular2/src/change_detection/pipes/iterable_changes",
      "angular2/src/change_detection/pipes/keyvalue_changes",
      "angular2/src/change_detection/pipes/async_pipe",
      "angular2/src/change_detection/pipes/null_pipe",
      "angular2/src/core/annotations_impl/visibility",
      "angular2/src/core/compiler/interfaces",
      "angular2/src/core/annotations_impl/view",
      "angular2/src/dom/dom_adapter",
      "angular2/src/dom/generic_browser_adapter",
      "angular2/src/core/annotations_impl/annotations",
      "angular2/src/core/compiler/directive_metadata",
      "angular2/src/facade/math",
      "angular2/src/core/annotations_impl/di",
      "angular2/src/render/api",
      "angular2/src/render/dom/view/view_container",
      "angular2/src/render/dom/view/element_binder",
      "angular2/src/render/dom/util",
      "angular2/src/render/dom/shadow_dom/content_tag",
      "angular2/src/render/dom/shadow_dom/shadow_dom_strategy",
      "angular2/src/core/zone/vm_turn_zone",
      "angular2/src/render/dom/view/view_hydrator",
      "angular2/src/render/dom/view/property_setter_factory",
      "angular2/src/render/dom/compiler/compile_step",
      "angular2/src/services/xhr",
      "angular2/src/services/url_resolver",
      "angular2/src/render/dom/compiler/property_binding_parser",
      "angular2/src/render/dom/compiler/text_interpolation_parser",
      "angular2/src/render/dom/compiler/selector",
      "angular2/src/render/dom/compiler/view_splitter",
      "angular2/src/render/dom/shadow_dom/shadow_dom_compile_step",
      "angular2/src/core/compiler/view_container_ref",
      "angular2/src/core/compiler/view_manager_utils",
      "angular2/src/core/compiler/view_pool",
      "angular2/src/core/compiler/base_query_list",
      "angular2/src/core/compiler/element_binder",
      "angular2/src/core/compiler/template_resolver",
      "angular2/src/core/compiler/component_url_mapper",
      "angular2/src/core/compiler/proto_view_factory",
      "angular2/src/core/exception_handler",
      "angular2/src/core/life_cycle/life_cycle",
      "angular2/src/render/dom/shadow_dom/style_url_resolver",
      "angular2/src/render/dom/shadow_dom/shadow_css",
      "angular2/src/services/xhr_impl",
      "angular2/src/render/dom/events/key_events",
      "angular2/src/render/dom/events/hammer_common",
      "angular2/src/render/dom/shadow_dom/style_inliner",
      "angular2/src/core/compiler/dynamic_component_loader",
      "angular2/src/core/testability/get_testability",
      "angular2/src/core/application_tokens",
      "angular2/src/core/annotations/di",
      "angular2/src/render/dom/shadow_dom/native_shadow_dom_strategy",
      "angular2/src/render/dom/shadow_dom/emulated_scoped_shadow_dom_strategy",
      "angular2/src/core/annotations/annotations",
      "angular2/src/core/decorators/decorators",
      "angular2/src/directives/class",
      "angular2/src/directives/for",
      "angular2/src/directives/if",
      "angular2/src/directives/non_bindable",
      "angular2/src/directives/switch",
      "angular2/src/forms/validators",
      "angular2/src/forms/directives",
      "angular2/src/forms/validator_directives",
      "angular2/src/forms/form_builder",
      "src/dc/api/Core.ts",
      "src/dc/log-config.es6",
      "src/entity-forge/Verify.es6",
      "src/rules-engine/datamocks/rule.mocks.es6",
      "npm:flux@2.0.3/lib/invariant",
      "src/rules-engine/actions/RuleEngineActionCreators.es6",
      "src/entity-forge/Validation.es6",
      "src/entity-forge/EntityBaseTypes.es6",
      "src/rules-engine/stores/RuleEngineStore.ts",
      "github:twbs/bootstrap@3.3.4/css/bootstrap.css!github:systemjs/plugin-css@0.1.12",
      "src/rules-engine-ng2/app/styles/rules-engine.css!github:systemjs/plugin-css@0.1.12",
      "src/rules-engine-ng2/app/styles/theme-dark.css!github:systemjs/plugin-css@0.1.12",
      "src/rules-engine-ng2/app/rules-engine-ng2.html!github:systemjs/plugin-text@0.0.2",
      "src/rules-engine-ng2/app/rule.tpl.html!github:systemjs/plugin-text@0.0.2",
      "src/rules-engine-ng2/app/rule-action.tpl.html!github:systemjs/plugin-text@0.0.2",
      "src/rules-engine-ng2/app/clause-group.tpl.html!github:systemjs/plugin-text@0.0.2",
      "src/rules-engine-ng2/app/clause.tpl.html!github:systemjs/plugin-text@0.0.2",
      "rtts_assert/rtts_assert",
      "npm:ms@0.7.1",
      "npm:base64-js@0.0.8",
      "npm:ieee754@1.1.5",
      "npm:is-array@1.0.1",
      "npm:process@0.10.1",
      "npm:inherits@2.0.1",
      "npm:create-hash@1.1.1/md5",
      "npm:ripemd160@1.0.1",
      "npm:sha.js@2.4.2/sha",
      "npm:sha.js@2.4.2/sha224",
      "npm:sha.js@2.4.2/sha384",
      "npm:events@1.0.2",
      "npm:isarray@0.0.1",
      "npm:core-util-is@1.0.1",
      "npm:readable-stream@1.1.13/lib/_stream_duplex",
      "npm:string_decoder@0.10.31",
      "npm:create-hmac@1.1.3",
      "npm:pbkdf2@3.0.4",
      "npm:browserify-aes@1.0.1/authCipher",
      "npm:bn.js@2.0.5",
      "npm:brorand@1.0.5",
      "npm:indexof@0.0.1",
      "npm:minimalistic-assert@1.0.0",
      "npm:asn1.js@2.0.3/lib/asn1/constants/index",
      "npm:asn1.js@2.0.3/lib/asn1/decoders/index",
      "npm:asn1.js@2.0.3/lib/asn1/encoders/index",
      "npm:parse-asn1@3.0.1/fixProc",
      "npm:hash.js@1.0.3/lib/hash",
      "npm:elliptic@3.0.4/lib/elliptic/curve/index",
      "npm:elliptic@3.0.4/lib/elliptic/curves",
      "npm:elliptic@3.0.4/lib/elliptic/ec/index",
      "npm:browserify-rsa@2.0.1",
      "npm:create-ecdh@2.0.1/index",
      "npm:public-encrypt@2.0.1/publicEncrypt",
      "angular2/src/change_detection/parser/ast",
      "angular2/src/reflection/reflector",
      "npm:rx@2.5.3/index",
      "angular2/src/change_detection/directive_record",
      "angular2/src/change_detection/change_detection_util",
      "angular2/src/change_detection/abstract_change_detector",
      "angular2/src/change_detection/change_detection",
      "angular2/src/core/annotations/visibility",
      "angular2/src/core/annotations/view",
      "angular2/src/dom/browser_adapter",
      "angular2/src/core/compiler/directive_metadata_reader",
      "angular2/src/core/compiler/view_ref",
      "angular2/src/render/dom/view/proto_view",
      "angular2/src/render/dom/shadow_dom/light_dom",
      "angular2/src/render/dom/events/event_manager",
      "angular2/src/render/dom/view/proto_view_builder",
      "angular2/src/render/dom/compiler/compile_control",
      "angular2/src/render/dom/compiler/template_loader",
      "angular2/src/render/dom/compiler/directive_parser",
      "angular2/src/core/compiler/query_list",
      "angular2/src/render/dom/shadow_dom/util",
      "angular2/src/render/dom/events/hammer_gestures",
      "angular2/src/core/testability/testability",
      "angular2/annotations",
      "angular2/directives",
      "angular2/src/forms/model",
      "src/dc/api/Check.ts",
      "npm:flux@2.0.3/lib/Dispatcher",
      "src/entity-forge/EntityForge.es6",
      "npm:debug@2.2.0/debug",
      "npm:buffer@3.2.2/index",
      "github:jspm/nodelibs-process@0.1.1/index",
      "npm:sha.js@2.4.2/index",
      "github:jspm/nodelibs-events@0.1.1/index",
      "npm:readable-stream@1.1.13/lib/_stream_readable",
      "npm:browserify-aes@1.0.1/encrypter",
      "npm:miller-rabin@2.0.1/lib/mr",
      "npm:vm-browserify@0.0.4/index",
      "npm:asn1.js@2.0.3/lib/asn1/base/node",
      "npm:hash.js@1.0.3",
      "npm:create-ecdh@2.0.1",
      "npm:public-encrypt@2.0.1/browser",
      "angular2/src/reflection/reflection",
      "npm:rx@2.5.3",
      "angular2/src/change_detection/binding_record",
      "angular2/src/change_detection/dynamic_change_detector",
      "angular2/src/render/dom/view/view",
      "angular2/src/render/dom/view/view_factory",
      "angular2/src/render/dom/compiler/compile_element",
      "angular2/src/render/dom/compiler/compile_step_factory",
      "angular2/src/render/dom/shadow_dom/emulated_unscoped_shadow_dom_strategy",
      "angular2/forms",
      "src/dc/index.es6",
      "npm:flux@2.0.3/index",
      "src/rules-engine/api/RuleEngineTypes.es6",
      "npm:debug@2.2.0/browser",
      "npm:buffer@3.2.2",
      "github:jspm/nodelibs-process@0.1.1",
      "npm:sha.js@2.4.2",
      "github:jspm/nodelibs-events@0.1.1",
      "npm:readable-stream@1.1.13/readable",
      "npm:browserify-aes@1.0.1/browser",
      "npm:miller-rabin@2.0.1",
      "npm:vm-browserify@0.0.4",
      "npm:asn1.js@2.0.3/lib/asn1/base/index",
      "npm:elliptic@3.0.4/lib/elliptic/hmac-drbg",
      "npm:public-encrypt@2.0.1",
      "angular2/src/di/binding",
      "angular2/src/facade/async",
      "angular2/src/change_detection/proto_record",
      "angular2/src/change_detection/proto_change_detector",
      "angular2/src/render/dom/compiler/compile_pipeline",
      "npm:flux@2.0.3",
      "npm:debug@2.2.0",
      "github:jspm/nodelibs-buffer@0.1.0/index",
      "npm:stream-browserify@1.0.0/index",
      "npm:browserify-aes@1.0.1",
      "npm:diffie-hellman@3.0.2/lib/generatePrime",
      "github:jspm/nodelibs-vm@0.1.0/index",
      "npm:elliptic@3.0.4/lib/elliptic",
      "angular2/src/di/injector",
      "angular2/src/change_detection/exceptions",
      "angular2/src/render/dom/compiler/compiler",
      "src/rules-engine/dispatcher/AppDispatcher.ts",
      "github:jspm/nodelibs-buffer@0.1.0",
      "npm:stream-browserify@1.0.0",
      "npm:diffie-hellman@3.0.2/browser",
      "github:jspm/nodelibs-vm@0.1.0",
      "npm:elliptic@3.0.4",
      "angular2/di",
      "angular2/src/render/dom/direct_dom_renderer",
      "src/rules-engine/api/RuleEngineAPI.ts",
      "npm:randombytes@2.0.1/browser",
      "github:jspm/nodelibs-stream@0.1.0/index",
      "npm:diffie-hellman@3.0.2",
      "npm:asn1.js@2.0.3/lib/asn1/api",
      "angular2/src/change_detection/parser/lexer",
      "angular2/src/core/compiler/element_ref",
      "src/rules-engine/RuleEngine.es6",
      "npm:randombytes@2.0.1",
      "github:jspm/nodelibs-stream@0.1.0",
      "npm:asn1.js@2.0.3/lib/asn1",
      "angular2/change_detection",
      "angular2/src/core/compiler/view_manager",
      "npm:create-hash@1.1.1/browser",
      "npm:asn1.js@2.0.3",
      "angular2/src/core/compiler/element_injector",
      "npm:create-hash@1.1.1",
      "npm:parse-asn1@3.0.1/asn1",
      "angular2/src/core/compiler/view",
      "npm:parse-asn1@3.0.1/index",
      "angular2/src/core/compiler/compiler",
      "npm:parse-asn1@3.0.1",
      "angular2/src/core/application",
      "npm:browserify-sign@3.0.2/sign",
      "angular2/core",
      "npm:browserify-sign@3.0.2/browser",
      "angular2/angular2",
      "npm:browserify-sign@3.0.2",
      "npm:crypto-browserify@3.9.14/index",
      "npm:crypto-browserify@3.9.14",
      "github:jspm/nodelibs-crypto@0.1.0/index",
      "github:jspm/nodelibs-crypto@0.1.0",
      "npm:reflect-metadata@0.1.0/Reflect",
      "npm:reflect-metadata@0.1.0",
      "src/rules-engine-ng2/app/rules-engine-ng2.ts",
      "src/rules-engine-ng2/index.es6"
    ]
  }
});

System.config({
  "meta": {
    "npm:zone.js@0.4.1/zone": {
      "format": "global"
    }
  }
});

System.config({
  "map": {
    "bootstrap": "github:twbs/bootstrap@3.3.4",
    "css": "github:systemjs/plugin-css@0.1.12",
    "debug": "npm:debug@2.2.0",
    "events": "github:jspm/nodelibs-events@0.1.1",
    "firebase": "github:firebase/firebase-bower@2.2.7",
    "flux": "npm:flux@2.0.3",
    "jsonp": "npm:jsonp@0.2.0",
    "reflect-metadata": "npm:reflect-metadata@0.1.0",
    "rest": "github:cujojs/rest@1.3.1",
    "rx": "npm:rx@2.5.3",
    "text": "github:systemjs/plugin-text@0.0.2",
    "traceur": "github:jmcriffey/bower-traceur@0.0.88",
    "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.88",
    "zone.js": "npm:zone.js@0.4.4",
    "github:cujojs/rest@1.3.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0",
      "when": "npm:when@3.7.3"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.2.2"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.9.14"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-net@0.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "timers": "github:jspm/nodelibs-timers@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-timers@0.1.0": {
      "timers-browserify": "npm:timers-browserify@1.4.1"
    },
    "github:jspm/nodelibs-tty@0.1.0": {
      "tty-browserify": "npm:tty-browserify@0.0.0"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "github:systemjs/plugin-css@0.1.12": {
      "clean-css": "npm:clean-css@3.1.9",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "github:twbs/bootstrap@3.3.4": {
      "jquery": "github:components/jquery@2.1.4"
    },
    "npm:amdefine@0.1.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:asn1.js@2.0.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@2.0.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:browserify-aes@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:browserify-rsa@2.0.1": {
      "bn.js": "npm:bn.js@2.0.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:browserify-sign@3.0.2": {
      "bn.js": "npm:bn.js@2.0.5",
      "browserify-rsa": "npm:browserify-rsa@2.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.1",
      "create-hmac": "npm:create-hmac@1.1.3",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@3.0.4",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@3.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:buffer@3.2.2": {
      "base64-js": "npm:base64-js@0.0.8",
      "ieee754": "npm:ieee754@1.1.5",
      "is-array": "npm:is-array@1.0.1"
    },
    "npm:clean-css@3.1.9": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "commander": "npm:commander@2.6.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "os": "github:jspm/nodelibs-os@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "source-map": "npm:source-map@0.1.43",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:commander@2.6.0": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@2.0.1": {
      "bn.js": "npm:bn.js@2.0.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@3.0.4"
    },
    "npm:create-hash@1.1.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:create-hmac@1.1.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.9.14": {
      "browserify-aes": "npm:browserify-aes@1.0.1",
      "browserify-sign": "npm:browserify-sign@3.0.2",
      "create-ecdh": "npm:create-ecdh@2.0.1",
      "create-hash": "npm:create-hash@1.1.1",
      "create-hmac": "npm:create-hmac@1.1.3",
      "diffie-hellman": "npm:diffie-hellman@3.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@2.0.1",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:debug@2.1.3": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ms": "npm:ms@0.7.0",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "tty": "github:jspm/nodelibs-tty@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:debug@2.2.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ms": "npm:ms@0.7.1",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "tty": "github:jspm/nodelibs-tty@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:diffie-hellman@3.0.2": {
      "bn.js": "npm:bn.js@2.0.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@2.0.1",
      "randombytes": "npm:randombytes@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:elliptic@3.0.4": {
      "bn.js": "npm:bn.js@2.0.5",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:jsonp@0.2.0": {
      "debug": "npm:debug@2.1.3"
    },
    "npm:miller-rabin@2.0.1": {
      "bn.js": "npm:bn.js@2.0.5",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:parse-asn1@3.0.1": {
      "asn1.js": "npm:asn1.js@2.0.3",
      "browserify-aes": "npm:browserify-aes@1.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.3",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:process@0.11.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:public-encrypt@2.0.1": {
      "bn.js": "npm:bn.js@2.0.5",
      "browserify-rsa": "npm:browserify-rsa@2.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@3.0.1",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:randombytes@2.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:readable-stream@1.1.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:reflect-metadata@0.1.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:rx@2.5.3": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:sha.js@2.4.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:source-map@0.1.43": {
      "amdefine": "npm:amdefine@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.13"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:timers-browserify@1.4.1": {
      "process": "npm:process@0.11.1"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:when@3.7.3": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    }
  }
});

