export const environment = {
  dotcmsUrl: 'https://staging-latest.dotcms.cloud/',
  authToken:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhcGk5Nzk0OTIwYi04NzJkLTQ0MTYtOWM1Yi00MzhkYWE2YmZiNWQiLCJ4bW9kIjoxNzY4NTg0NTE1MDAwLCJuYmYiOjE3Njg1ODQ1MTUsImlzcyI6InN0YWdpbmctbGF0ZXN0IiwibGFiZWwiOiJIZWFkbGVzcyBFeGFtcGxlcyBSZWFkLU9ubHkgVG9rZW4iLCJleHAiOjE4NjMyMzA0MDAsImlhdCI6MTc2ODU4NDUxNSwianRpIjoiMTNhZWNiMTYtZDUxMi00MmQ4LWFhYmYtMWJlMjQ4MTE2ODM3In0.eD93wAaKSCbaQA2RYoxM66z0uCPXesDBCiuj06ArNug',
  siteId: 'demo.dotcms.com',
};
