#!/bin/bash
set -e
. "$DOTCLI_WORKDIR/common"

help_push_content_type() {
  echo "
Command: content-type

This command takes a json file describing the CT that will be pushed/updated

Usage:
  ./dot-cli --content-type ~/code/etc/content-type.json
  or
  ./dot-cli --content-type ~/code/etc/content-type.json
   "
  exit 1
}

[[ ! -n "$1" ]] && help_push_content_type

cli_log "Pushing ContentType"

file="$1"

if [[ ! -f "$file" ]]; then
    echo " The file $file does not exist."
    exit 1
fi

jsonContentType=$(<$file)

contentTypeVar=$(jq -r  '.variable' <<< "$jsonContentType")

echo "Content-type Variable name loaded is $contentTypeVar verifying against remote host."

code=$(curl -s -o /dev/null --head -w "%{http_code}" --header "Authorization: Bearer ${JSON_WEB_TOKEN}" "${DOTCMS_BASE_URL}/api/v1/contenttype/id/${contentTypeVar}" )

if [[ $code = 404 ]]
then
   echo "Content-type does not exists on remote site. Add will be attempted."

   response=$(curl -s "${DOTCMS_BASE_URL}/api/v1/contenttype"  --header "Authorization: Bearer ${JSON_WEB_TOKEN}" --header 'Content-Type: application/json' --data-raw  "$jsonContentType"  --compressed)
   echo "$response"
   identifier=$(jq -r ' try .entity[].id' <<< "$response")

       if [[ -z ${identifier} ]];
       then
        echo "Unable to get identifier from response adding CT ${contentTypeVar}. Please check if there were any error messages."
       else
         echo "New content-type identifier :: $identifier"
         printf ${identifier} >> $publishMeFile
       fi

else
      echo "A content type named $contentTypeVar already exists. Update will be attempted."

      response=$(curl -s -X PUT "${DOTCMS_BASE_URL}/api/v1/contenttype/id/${contentTypeVar}"  --header "Authorization: Bearer ${JSON_WEB_TOKEN}" --header 'Content-Type: application/json' --data-raw  "$jsonContentType"  --compressed)
      echo "$response"

      identifier=$(jq -r ' try .entity[].id' <<< "$response")

      if [[ -z ${identifier} ]];
      then
        echo "Unable to get identifier from response updating CT ${contentTypeVar}. Please check if there were any error messages."

      else
       echo " Updated content-type identifier :: $identifier"
       printf ${identifier} >> $publishMeFile
      fi

fi


cli_log "done."
