#!/bin/bash
set -e
. "$DOTCLI_WORKDIR/common"

help_push_files() {
  echo "
Command: files

This command takes a directory that serves as the entry point for all the assets and files.

Usage:
  ./dot-cli --file  ~/code/etc/bundle/files/
  or
  ./dot-cli -f ~/code/etc/bundle/files/
   "
  exit 1
}

[[ ! -n "$1" ]] && help_push_files

cli_log "Pushing Files/Folder"

filesDir="$1"

if [[ ! -d "$filesDir" ]]; then
    echo " The directory $filesDir does not exist."
    exit 1
fi

langArray=();

# for the given working directory we need to explore and determine what folder was meant to hold content-types, what folder was meant to hold sites, files and so on.
for entry in "$filesDir"/*
do
     langArray[${#langArray[@]}]="$entry"
done


siteArray=();
for lang in "${langArray[@]}"
do
     #this will process the language directory
     bash "$DOTCLI_WORKDIR/commands/lang" "$lang"

     for site in "$lang"/*
     do
       siteArray[${#siteArray[@]}]="$site"
     done

done

#Now process the files under the sites
for siteFilesDir in "${siteArray[@]}"
do
   #echo $files
   for siteFiles in "$siteFilesDir"/*
   do
     echo " ::: $siteFiles"
   done

done

