#!/bin/bash
set -e
. "$DOTCLI_WORKDIR/common"

help_push_files() {
  echo "
Command: files

This command takes a directory that serves as the entry point for all the assets and files.

Usage:
  ./dot-cli --file  ~/code/etc/bundle/files/
  or
  ./dot-cli -f ~/code/etc/bundle/files/
   "
  exit 1
}

[[ ! -n "$1" ]] && help_push_files

cli_log "::: Pushing Files/Folder :::"

dir="$1"

if [[ ! -d "$dir" ]]; then
    cli_log "Files directory \"$dir\" does not exist.."
    exit 1
fi

for entry in "$dir"/*
do
     #echo "$entry"
     case ${entry} in
       *files)
       filesDir=${entry}
       ;;
     esac
done

if [[ ! -d "$filesDir" ]]; then
    cli_log " The directory $filesDir does not exist."
    exit 1
fi

langArray=();

for entry in "$filesDir"/*
do
     langArray[${#langArray[@]}]="$entry"
done

siteArray=();

for langDir in "${langArray[@]}"
do
     #this will process the language directory

    cli_log "::: Pushing language language $langDir :::"
    currentLangId=$(bash "$DOTCLI_WORKDIR/commands/push-lang" "$langDir")
    cli_log "::: Done pushing language returned id is $currentLangId  :::"

    if [[ -z ${currentLangId} ]]; then
      cli_log "Unable to determine last pushed language id"
    else
     for site in "$langDir"/*
     do
       if [[ -d "$site" ]]; then
           bash "$DOTCLI_WORKDIR/commands/push-site-contents" "$site" "$currentLangId"
       fi
     done
    fi
done

cli_log "::: Done pushing Files/Folder :::"