#!/bin/bash
set -e
. "$DOTCLI_WORKDIR/common"

help_push_site() {
  echo "
Command: content-type

Usage:
  ./dot-cli --site -f ~/code/etc/site.json
  or
  ./dot-cli --site --file ~/code/etc/site.json
   "
  exit 1
}

[[ ! -n "$1" ]] && help_push_site

cli_log "Pushing Site"

case $1 in
    --file|-F|-f)
    file="$2"
    shift # past argument
    shift # past value
    ;;
    *)
    help_push_site
    ;;
esac

if [[ ! -f "$file" ]]; then
    echo " The file $file does not exist."
    exit 1
fi

jsonSite=$(<$file)

siteName=$(jq -r  '.sitename' <<< "$jsonSite")

echo "Verifying $siteName against remote host."

code=$(curl -s -X POST "${DOTCMS_BASE_URL}/api/v1/site/_byname" -o /dev/null --header "Authorization: Bearer ${JSON_WEB_TOKEN}" -w "%{http_code}" --header 'Content-Type: application/json' --data-raw "{ \"sitename\":\"$siteName\" }")

echo " response code was $code"

if [[ $code = 404 ]]
then
   echo "A site named $siteName does not exist on the remote site. An Add will be attempted."

   response=$(curl -s -X POST "${DOTCMS_BASE_URL}/api/v1/site" --header "Authorization: Bearer ${JSON_WEB_TOKEN}" --header 'Content-Type: application/json' --data-raw  "$jsonSite"  --compressed)

   echo "$response"

  else
   echo "A site named $siteName already exists."
fi


cli_log "done."
