/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { DotCardContentletItem } from './models/dot-card-contentlet.model';
import { DotContentletItem } from './models/dot-contentlet-item.model';
export namespace Components {
    interface DotCardView {
        clearValue: () => Promise<void>;
        getValue: () => Promise<DotContentletItem[]>;
        items: DotCardContentletItem[];
        value: string;
    }
    interface DotHtmlToImage {
        height: string;
        value: string;
        width: string;
    }
}
export interface DotCardViewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDotCardViewElement;
}
export interface DotHtmlToImageCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDotHtmlToImageElement;
}
declare global {
    interface HTMLDotCardViewElement extends Components.DotCardView, HTMLStencilElement {}
    var HTMLDotCardViewElement: {
        prototype: HTMLDotCardViewElement;
        new (): HTMLDotCardViewElement;
    };
    interface HTMLDotHtmlToImageElement extends Components.DotHtmlToImage, HTMLStencilElement {}
    var HTMLDotHtmlToImageElement: {
        prototype: HTMLDotHtmlToImageElement;
        new (): HTMLDotHtmlToImageElement;
    };
    interface HTMLElementTagNameMap {
        'dot-card-view': HTMLDotCardViewElement;
        'dot-html-to-image': HTMLDotHtmlToImageElement;
    }
}
declare namespace LocalJSX {
    interface DotCardView {
        items?: DotCardContentletItem[];
        onCardClick?: (event: DotCardViewCustomEvent<any>) => void;
        onSelected?: (event: DotCardViewCustomEvent<any>) => void;
        value?: string;
    }
    interface DotHtmlToImage {
        height?: string;
        onPageThumbnail?: (event: DotHtmlToImageCustomEvent<File>) => void;
        value?: string;
        width?: string;
    }
    interface IntrinsicElements {
        'dot-card-view': DotCardView;
        'dot-html-to-image': DotHtmlToImage;
    }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
    export namespace JSX {
        interface IntrinsicElements {
            'dot-card-view': LocalJSX.DotCardView & JSXBase.HTMLAttributes<HTMLDotCardViewElement>;
            'dot-html-to-image': LocalJSX.DotHtmlToImage &
                JSXBase.HTMLAttributes<HTMLDotHtmlToImageElement>;
        }
    }
}
