-- ALTER TABLE TEMPLATE FOR ADDING DESIGN COLUMNS
--	GRAZIANO issue-12-dnd-template
ALTER TABLE TEMPLATE
ADD (
 	DRAWED tinyint,
 	DRAWED_BODY text,
 	ADD_CONTAINER_LINKS int,
 	CONTAINERS_ADDED int
);