-- ALTER TABLE TEMPLATE FOR ADDING DESIGN COLUMNS
--	GRAZIANO issue-12-dnd-template
ALTER TABLE TEMPLATE
ADD (
 	DRAWED tinyint(1),
 	DRAWED_BODY longtext,
 	ADD_CONTAINER_LINKS integer,
 	CONTAINERS_ADDED integer,
 	HEAD_CODE longtext
);

ALTER TABLE CONTAINERS
ADD (
 	FOR_METADATA tinyint(1)
);