-- ALTER TABLE TEMPLATE FOR ADDING DESIGN COLUMNS
--	GRAZIANO issue-12-dnd-template
ALTER TABLE TEMPLATE
ADD (
 	DRAWED number(1,0),
 	DRAWED_BODY nclob,
 	ADD_CONTAINER_LINKS number(10,0),
 	CONTAINERS_ADDED number(10,0)
);

ALTER TABLE CONTAINERS
ADD (
 	FOR_METADATA number(1,0)
);