-- ALTER TABLE TEMPLATE FOR ADDING DESIGN COLUMNS
--	GRAZIANO issue-12-dnd-template
ALTER TABLE TEMPLATE
ADD (
 	DRAWED bool,
 	DRAWED_BODY text,
 	ADD_CONTAINER_LINKS int4,
 	CONTAINERS_ADDED int4
);