### TESTING THE PUSH OF ASSETS WHERE LIVE==FALSE
###
< {%
    const hostName="test15"
    client.global.set("hostName", hostName)
%}
POST localhost:8080/api/v1/site
Content-Type: application/json
Authorization: Basic admin@dotcms.com admin

{
  "siteName":"{{hostName}}"
}
> {%
    client.global.set("siteId", response.body.entity.identifier);
%}

### Publishing the site
PUT localhost:8080/api/v1/site/{{siteId}}/_publish
Content-Type: application/json
Authorization: Basic admin@dotcms.com admin

### PUSHING A FILE WITH LIVE == FALSE
###  IT WORKS HERE, BUT WE NEED DEFAULT CODE IN THE API AS QUARKUS DOES NOT SENDS THE DEFAULT FOR BOOLEAN
PUT localhost:8080/api/v1/assets
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic admin@dotcms.com admin

--WebAppBoundary
Content-Disposition: form-data; name="detail"
Content-Type: application/json

{
  "assetPath":"//{{hostName}}/folder1/1.png",
  "language":"en_us"
}
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="1.png"
Content-Type: application/json

< /Users/fabrizzioaraya/Downloads/images/tiquicia.jpeg
--WebAppBoundary--