import {
    DotCMSBaseTypesContentTypes,
    DotCMSClazzes,
    DotCMSContentType
} from '@dotcms/dotcms-models';

export const MOCK_CONTENT_TYPES: DotCMSContentType[] = [
    {
        baseType: 'CONTENT',
        host: 'localhost',
        iDate: 1234567890,
        layout: [],
        name: 'Activity',
        icon: 'palette',
        id: '1',
        variable: 'activity',
        clazz: DotCMSClazzes.SIMPLE_CONTENT_TYPE,
        defaultType: false,
        contentType: 'Activity',
        description: 'Activity content type',
        fields: [],
        fixed: false,
        folder: 'Content',
        modDate: 1234567890,
        multilingualable: true,
        nEntries: 0,
        owner: 'system',
        system: true,
        versionable: true,
        workflows: []
    },
    {
        baseType: 'CONTENT',
        host: 'localhost',
        iDate: 1234567890,
        layout: [],
        name: 'Blog Post',
        icon: 'article',
        id: '2',
        variable: 'blog-post',
        clazz: DotCMSClazzes.SIMPLE_CONTENT_TYPE,
        defaultType: false,
        contentType: 'Blog Post',
        description: 'Blog post content type',
        fields: [],
        fixed: false,
        folder: 'Content',
        modDate: 1234567890,
        multilingualable: true,
        nEntries: 0,
        owner: 'system',
        system: true,
        versionable: true,
        workflows: []
    },
    {
        baseType: 'CONTENT',
        host: 'localhost',
        iDate: 1234567890,
        layout: [],
        name: 'Product',
        icon: 'shopping_cart',
        id: '3',
        variable: 'product',
        clazz: DotCMSClazzes.SIMPLE_CONTENT_TYPE,
        defaultType: false,
        contentType: 'Product',
        description: 'Product content type',
        fields: [],
        fixed: false,
        folder: 'Content',
        modDate: 1234567890,
        multilingualable: true,
        nEntries: 0,
        owner: 'system',
        system: true,
        versionable: true,
        workflows: []
    },
    {
        baseType: 'CONTENT',
        host: 'localhost',
        iDate: 1234567890,
        layout: [],
        name: 'Event',
        icon: 'event',
        id: '4',
        variable: 'event',
        clazz: DotCMSClazzes.SIMPLE_CONTENT_TYPE,
        defaultType: false,
        contentType: 'Event',
        description: 'Event content type',
        fields: [],
        fixed: false,
        folder: 'Content',
        modDate: 1234567890,
        multilingualable: true,
        nEntries: 0,
        owner: 'system',
        system: true,
        versionable: true,
        workflows: []
    },
    {
        baseType: 'CONTENT',
        host: 'localhost',
        iDate: 1234567890,
        layout: [],
        name: 'News',
        icon: 'newspaper',
        id: '5',
        variable: 'news',
        clazz: DotCMSClazzes.SIMPLE_CONTENT_TYPE,
        defaultType: false,
        contentType: 'News',
        description: 'News content type',
        fields: [],
        fixed: false,
        folder: 'Content',
        modDate: 1234567890,
        multilingualable: true,
        nEntries: 0,
        owner: 'system',
        system: true,
        versionable: true,
        workflows: []
    },
    {
        baseType: 'CONTENT',
        host: 'localhost',
        iDate: 1234567890,
        layout: [],
        name: 'Gallery',
        icon: 'photo_library',
        id: '6',
        variable: 'gallery',
        clazz: DotCMSClazzes.SIMPLE_CONTENT_TYPE,
        defaultType: false,
        contentType: 'Gallery',
        description: 'Gallery content type',
        fields: [],
        fixed: false,
        folder: 'Content',
        modDate: 1234567890,
        multilingualable: true,
        nEntries: 0,
        owner: 'system',
        system: true,
        versionable: true,
        workflows: []
    }
];

export const BASETYPES_FOR_CONTENT = [
    DotCMSBaseTypesContentTypes.CONTENT,
    DotCMSBaseTypesContentTypes.FILEASSET,
    DotCMSBaseTypesContentTypes.DOTASSET
];

export const BASETYPES_FOR_WIDGET = [DotCMSBaseTypesContentTypes.WIDGET];
