const isCi = process.env.CI !== undefined;
if (!isCi) {
    const { execSync } = require('child_process');
    const { writeFileSync } = require('fs');
    const path = require('path');

    const repoRoot = path.resolve(__dirname, '..');

    // Undo husky's core.hooksPath so git uses the default .git/hooks/ location.
    try {
        execSync('git config --unset core.hooksPath', { stdio: 'ignore' });
    } catch (_) {
        // Already unset — fine
    }

    let gitHooksDir;
    try {
        const gitCommonDir = execSync('git rev-parse --git-common-dir', {
            cwd: repoRoot,
            encoding: 'utf8'
        }).trim();
        // git-common-dir is absolute in linked worktrees; path.join(repo, absPath) is wrong on Node.
        gitHooksDir = path.isAbsolute(gitCommonDir)
            ? path.join(gitCommonDir, 'hooks')
            : path.join(repoRoot, gitCommonDir, 'hooks');
    } catch (_) {
        process.exit(0);
    }

    // Hooks used by lefthook.yml — keep in sync with that file.
    const hooks = ['pre-commit', 'pre-push', 'post-merge'];

    for (const hookName of hooks) {
        const script = `#!/bin/sh
# Generated by core-web/prepare.js — do not edit directly.
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
cd "$REPO_ROOT" || exit 0

if [ "$LEFTHOOK" = "0" ]; then
  exit 0
fi

if [ -f "$REPO_ROOT/lefthook.yml" ] || [ -f "$REPO_ROOT/lefthook.yaml" ]; then
  if command -v lefthook >/dev/null 2>&1; then
    exec lefthook run ${hookName} "$@"
  fi
  if command -v mise >/dev/null 2>&1 && mise exec -- lefthook version >/dev/null 2>&1; then
    exec mise exec -- lefthook run ${hookName} "$@"
  fi
  echo "WARNING: lefthook not found — ${hookName} hooks skipped. Run: just setup" >&2
  exit 0
fi

for dir in "$REPO_ROOT/.husky" "$REPO_ROOT/core-web/.husky"; do
  if [ -f "$dir/${hookName}" ]; then
    exec sh "$dir/${hookName}" "$@"
  fi
done

exit 0
`;
        try {
            writeFileSync(path.join(gitHooksDir, hookName), script, { mode: 0o755 });
        } catch (_) {
            // Unwritable .git (e.g. some CI) — ignore
        }
    }
}
