drop TABLE abcontact ;
drop TABLE abcontacts_ablists ;
drop TABLE ablist ;
drop TABLE address ;
drop TABLE adminconfig ;
drop TABLE bjentries_bjtopics ;
drop TABLE bjentries_bjverses ;
drop TABLE bjentry ;
drop TABLE bjtopic ;
drop TABLE bjverse ;
drop TABLE blogscategory ;
drop TABLE blogscomments ;
drop TABLE blogsentry ;
drop TABLE blogslink ;
drop TABLE blogsprops ;
drop TABLE blogsreferer ;
drop TABLE blogsuser ;
drop TABLE bookmarksentry ;
drop TABLE bookmarksfolder ;
drop TABLE calevent ;
drop TABLE caltask ;
drop TABLE company ;
drop TABLE counter ;
drop TABLE cyrususer ;
drop TABLE cyrusvirtual ;
drop TABLE dlfileprofile ;
drop TABLE dlfilerank ;
drop TABLE dlfileversion ;
drop TABLE dlrepository ;
drop TABLE group_ ;
drop TABLE groups_roles ;
drop TABLE igfolder ;
drop TABLE igimage ;
drop TABLE image ;
drop TABLE journalarticle ;
drop TABLE journalstructure ;
drop TABLE journaltemplate ;
drop TABLE layer ;
drop TABLE layout ;
drop TABLE mailreceipt ;
drop TABLE mbmessage ;
drop TABLE mbmessageflag ;
drop TABLE mbthread ;
drop TABLE mbtopic ;
drop TABLE networkaddress ;
drop TABLE note ;
drop TABLE passwordtracker ;
drop TABLE pollschoice ;
drop TABLE pollsdisplay ;
drop TABLE pollsquestion ;
drop TABLE pollsvote ;
drop TABLE portlet ;
drop TABLE portletpreferences ;
drop TABLE projfirm ;
drop TABLE projproject ;
drop TABLE projtask ;
drop TABLE projtime ;
drop TABLE release_ ;
drop TABLE role_ ;
drop TABLE skin ;
drop TABLE shoppingcart ;
drop TABLE shoppingcategory ;
drop TABLE shoppingcoupon ;
drop TABLE shoppingitem ;
drop TABLE shoppingitemfield ;
drop TABLE shoppingitemprice ;
drop TABLE shoppingorder ;
drop TABLE shoppingorderitem ;
drop TABLE user_ ;
drop TABLE users_groups ;
drop TABLE users_projprojects ;
drop TABLE users_projtasks ;
drop TABLE users_roles ;
drop TABLE usertracker ;
drop TABLE usertrackerpath ;
drop TABLE wikidisplay ;
drop TABLE wikinode ;
drop TABLE wikipage ;








drop sequence workflow_seq;
drop TABLE action ;
drop TABLE "action" ;
drop sequence action_sequence;
drop TABLE cache_ ;
drop TABLE campaign ;
drop TABLE category ;
drop TABLE click ;
drop TABLE clickstream ;
drop SEQUENCE clickstream_seq;
drop TABLE clickstream_request ;
drop SEQUENCE clickstream_request_seq;
drop TABLE containers ;
drop TABLE entity ;
drop TABLE facility ;
drop TABLE file_asset ;
drop TABLE file_upload ;
drop TABLE folder;
drop TABLE geometry_columns ;
drop TABLE guestbook ;
drop TABLE htmlpage ;
drop TABLE identifier ;
drop TABLE inode ;
drop SEQUENCE inode_seq;
drop TABLE language ;
drop SEQUENCE language_seq;
drop TABLE links;
drop TABLE mailing_list ;
drop TABLE multi_tree;
drop TABLE permission ;
drop SEQUENCE permission_seq;
drop TABLE recipient ;
drop TABLE recurance ;
drop TABLE relation ;
drop TABLE status ;

drop sequence workflow_seq;
drop TABLE template ;
drop TABLE tree ;
drop TABLE user_comments ;
drop SEQUENCE user_comments_seq;
drop TABLE user_preferences ;
drop SEQUENCE user_preferences_seq;
drop TABLE user_proxy ;
drop TABLE virtual_link;
drop TABLE workflow_messages ;
drop TABLE workflow_queue ;
drop TABLE host ;
drop TABLE jobs ;
drop TABLE searchfirm ;
drop TABLE resume ;
drop TABLE banner ;
drop TABLE event_registration ;
drop TABLE event ;
drop TABLE subscriber;
drop TABLE structure ;
drop TABLE field;
drop TABLE contentlet ;
drop table indexation;

drop table qrtz_job_listeners;
drop table qrtz_trigger_listeners;
drop table qrtz_fired_triggers;
DROP TABLE QRTZ_PAUSED_TRIGGER_GRPS;
DROP TABLE QRTZ_SCHEDULER_STATE;
DROP TABLE QRTZ_LOCKS;
drop table qrtz_simple_triggers;
drop table qrtz_cron_triggers;
DROP TABLE QRTZ_BLOB_TRIGGERS;
drop table qrtz_triggers;
drop table qrtz_job_details;
drop table qrtz_calendars;

purge recyclebin;