package com.dotcms.featureflag;

/**
 * This class is in charge of encapsulating all the feature flag names
 * @author jsanca
 */
public interface FeatureFlagName {

    // Experiments and Analytics
    String TELEMETRY_API_METRICS_ENABLED = "TELEMETRY_API_METRICS_ENABLED";

    String FEATURE_FLAG_EXPERIMENTS = "FEATURE_FLAG_EXPERIMENTS";

    String FEATURE_FLAG_TELEMETRY_CORE_ENABLED = "FEATURE_FLAG_TELEMETRY_CORE_ENABLED";

    String FEATURE_FLAG_CONTENT_ANALYTICS = "FEATURE_FLAG_CONTENT_ANALYTICS";

    String FEATURE_FLAG_CONTENT_ANALYTICS_AUTO_INJECT = "FEATURE_FLAG_CONTENT_ANALYTICS_AUTO_INJECT";

    // Unique Fields
    String FEATURE_FLAG_DB_UNIQUE_FIELD_VALIDATION = "FEATURE_FLAG_DB_UNIQUE_FIELD_VALIDATION";

    // others
    String FULLSCREEN_FIELD_FEATURE_FLAG = "content.edit.ui.fullscreen";

    String FEATURE_FLAG_LOCALES_HIDE_OLD_LANGUAGES_PORTLET = "FEATURE_FLAG_LOCALES_HIDE_OLD_LANGUAGES_PORTLET";

    String DOTFAVORITEPAGE_FEATURE_ENABLE = "DOTFAVORITEPAGE_FEATURE_ENABLE";

    String FEATURE_FLAG_TEMPLATE_BUILDER_2 = "FEATURE_FLAG_TEMPLATE_BUILDER_2";

    String FEATURE_FLAG_SEO_IMPROVEMENTS = "FEATURE_FLAG_SEO_IMPROVEMENTS";

    String FEATURE_FLAG_SEO_PAGE_TOOLS = "FEATURE_FLAG_SEO_PAGE_TOOLS";

    String FEATURE_FLAG_EDIT_URL_CONTENT_MAP = "FEATURE_FLAG_EDIT_URL_CONTENT_MAP";

    String FEATURE_FLAG_NEW_BINARY_FIELD = "FEATURE_FLAG_NEW_BINARY_FIELD";

    String FEATURE_FLAG_ANNOUNCEMENTS = "FEATURE_FLAG_ANNOUNCEMENTS";

    String FEATURE_FLAG_NEW_EDIT_PAGE = "FEATURE_FLAG_NEW_EDIT_PAGE";

    String FEATURE_FLAG_UVE_PREVIEW_MODE = "FEATURE_FLAG_UVE_PREVIEW_MODE";

    String FEATURE_FLAG_UVE_TOGGLE_LOCK = "FEATURE_FLAG_UVE_TOGGLE_LOCK";

    String FEATURE_FLAG_UVE_STYLE_EDITOR = "FEATURE_FLAG_UVE_STYLE_EDITOR";

    // Open Search Related
    String FEATURE_FLAG_OPEN_SEARCH_WRITE = "FEATURE_FLAG_OPEN_SEARCH_WRITE";

    String FEATURE_FLAG_OPEN_SEARCH_READ = "FEATURE_FLAG_OPEN_SEARCH_READ";
}
