#!/usr/bin/env just --justfile

# maven build without tests
build:
   mvn -DskipTests clean package

# dump compile dependencies to dependencies.txt
dependencies:
  mvn dependency:tree -Dscope=compile > dependencies.txt

# dump dependencies updates to updates.txt
updates:
  mvn versions:display-dependency-updates > updates.txt    