/**
 * Picks the configuration(s) that actually include a changed file.
 *
 * Selection is by RESOLVED FILE LIST, never by filename convention, and the acceptance case shows
 * why in the bluntest possible way: two of its five violations live in a `.spec.ts`, and checking
 * sdk-create-app's tsconfig.lib.json reports ZERO. A "lib first" heuristic would have found
 * nothing while looking perfectly healthy, and the spike would have shipped a false number.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { parseConfigFile } from './resolve-tools.mjs';

const TSCONFIG_NAME = /^tsconfig\..*\.json$|^tsconfig\.json$/;

/**
 * `tsconfig.editor.json` is generated by Nx for IDE language services. It globs the whole project,
 * so it will happily claim any file — and it carries no `angularCompilerOptions`, which makes
 * template strictness unreachable for anything it swallows. A last resort, never a stand-in for
 * the build config.
 */
const isIdeOnly = (configPath) => path.basename(configPath) === 'tsconfig.editor.json';

/**
 * Preference order among configs that could host a file none of them names outright.
 *
 * The spec config is ranked LAST on purpose. Angular colocates `x.component.ts`,
 * `x.component.html` and `x.component.spec.ts`, so any "owns TypeScript in this directory"
 * rule matches the spec config as readily as the build config — and the spec config carries no
 * `angularCompilerOptions`, so a template routed there goes unchecked behind a reported target
 * and a PASS.
 */
const CONFIG_RANK = [
    'tsconfig.app.json',
    'tsconfig.lib.json',
    'tsconfig.json',
    'tsconfig.spec.json',
    'tsconfig.editor.json'
];

/** Unknown config names rank alongside the spec config: plausible host, never a preferred one. */
const rankOf = (configPath) => {
    const index = CONFIG_RANK.indexOf(path.basename(configPath));
    return index === -1 ? CONFIG_RANK.indexOf('tsconfig.spec.json') : index;
};

/**
 * Templates need a different rule from sources: a tsconfig's resolved file list contains only
 * TypeScript, so a `.html` is never in it. Matching sources by file list and then dropping
 * templates would make a template-only pull request resolve zero configs and pass silently —
 * which reads exactly like "nothing to check".
 */
const isTemplate = (f) => path.extname(f) === '.html';

/**
 * @param {{ workspaceDir: string, project: {name:string,root:string}, files: string[], repoDir?: string }} input
 * @returns {Promise<{project:string,root:string,configPath:string,files:string[]}[]>}
 */
export async function selectConfigs({ workspaceDir, project, files, repoDir = workspaceDir }) {
    const projectDir = path.resolve(repoDir, project.root);

    const candidates = (await fs.readdir(projectDir))
        .filter((name) => TSCONFIG_NAME.test(name))
        .map((name) => path.join(projectDir, name))
        .sort();

    const sources = files.filter((f) => !isTemplate(f));
    const templates = files.filter(isTemplate);

    const wanted = new Set(sources.map((f) => path.resolve(repoDir, f)));
    const parsedConfigs = [];

    for (const configPath of candidates) {
        const parsed = await parseConfigFile(configPath);
        // A references-only config resolves to zero files and excludes itself with no special-casing.
        if (!parsed || parsed.fileNames.length === 0) continue;
        parsedConfigs.push({ configPath, fileNames: parsed.fileNames.map((f) => path.resolve(f)) });
    }

    const owned = new Map();
    const claim = (configPath, file) => {
        if (!owned.has(configPath)) owned.set(configPath, new Set());
        owned.get(configPath).add(file);
    };

    // An IDE-only config globs the whole project, so it matches everything a build config also
    // covers — and it carries no `angularCompilerOptions`, which makes template strictness
    // unreachable for anything it swallows. Whenever the project has a real build config, the
    // IDE one is ignored outright and its files are routed through the ranking below.
    const hasBuildConfig = parsedConfigs.some((c) => !isIdeOnly(c.configPath));
    const eligible = hasBuildConfig ? parsedConfigs.filter((c) => !isIdeOnly(c.configPath)) : parsedConfigs;

    const matchedSources = new Set();
    for (const { configPath, fileNames } of eligible) {
        for (const file of fileNames) {
            if (wanted.has(file)) {
                claim(configPath, path.relative(repoDir, file));
                matchedSources.add(file);
            }
        }
    }

    /**
     * Ranks the configs that could plausibly host a file none of them names outright.
     *
     * An app config that declares `files: ["src/main.ts"]` reaches every component through the
     * import graph, so its resolved list names two entries while its PROGRAM contains thousands.
     * Building the program to find out would cost the very compilation this step exists to scope.
     */
    const hostFor = (absolutePath) => {
        const dir = path.dirname(absolutePath);
        const byRank = (a, b) =>
            rankOf(a.configPath) - rankOf(b.configPath) || b.fileNames.length - a.fileNames.length;

        // Siblings are ranked too, not taken in directory-listing order: the first match is as
        // likely to be the spec config as the build config.
        const siblings = eligible
            .filter((c) => c.fileNames.some((f) => path.dirname(f) === dir))
            .sort(byRank);
        if (siblings.length > 0 && rankOf(siblings[0].configPath) < rankOf('tsconfig.spec.json')) {
            return siblings[0];
        }

        // `siblings` is a subset of `eligible`, so if it had an entry so does `ranked`.
        const ranked = [...eligible].sort(byRank);
        return ranked[0] ?? null;
    };

    // Sources an entry-point config owns transitively but never names.
    for (const source of sources) {
        const absolute = path.resolve(repoDir, source);
        if (matchedSources.has(absolute)) continue;
        const host = hostFor(absolute);
        if (host) claim(host.configPath, source);
    }

    // A template belongs to the component that references it, and Angular convention colocates the
    // two. Attaching it to the config that owns TypeScript in the same directory is cheap and right
    // in practice; resolving `templateUrl` properly would mean compiling in order to decide what to
    // compile. Falling back to the config with the widest file list keeps an orphan template
    // visible rather than dropping it.
    for (const template of templates) {
        const host = hostFor(path.resolve(repoDir, template));
        if (host) claim(host.configPath, template);
    }

    return [...owned.entries()].map(([configPath, fileSet]) => ({
        project: project.name,
        root: project.root,
        configPath,
        files: [...fileSet]
    }));
}
