import {
  AutoCompleteModule,
  BreadcrumbModule,
  ButtonModule,
  CalendarModule,
  CheckboxModule,
  ConfirmDialogModule,
  DataTableModule, SharedModule,
  DialogModule,
  DropdownModule,
  InputTextModule,
  InputTextareaModule,
  PasswordModule,
  RadioButtonModule,
  SplitButtonModule,
  TabViewModule,
  ToolbarModule,
  TreeTableModule
} from 'primeng/primeng';

export const NGFACES_MODULES = [
  AutoCompleteModule,
  BreadcrumbModule,
  ButtonModule,
  CalendarModule,
  CheckboxModule,
  ConfirmDialogModule,
  DataTableModule,
  DialogModule,
  DropdownModule,
  InputTextModule,
  InputTextareaModule,
  PasswordModule,
  RadioButtonModule,
  SharedModule,
  SplitButtonModule,
  TabViewModule,
  ToolbarModule,
  TreeTableModule
];
