import { DotPersona } from '@models/dot-persona/dot-persona.model';

export const mockDotPersona: DotPersona = {
    archived: false,
    baseType: 'PERSONA',
    contentType: 'persona',
    folder: 'SYSTEM_FOLDER',
    hasTitleImage: false,
    host: 'SYSTEM_HOST',
    hostFolder: 'SYSTEM_HOST',
    hostName: 'System Host',
    identifier: '1c56ba62-1f41-4b81-bd62-b6eacff3ad23',
    inode: '',
    keyTag: 'dot:persona',
    languageId: 1,
    live: false,
    locked: false,
    modDate: '0',
    modUser: 'system',
    modUserName: 'system user system user',
    name: 'Global Investor',
    personalized: true,
    photo: '/url',
    sortOrder: 0,
    stInode: 'c938b15f-bcb6-49ef-8651-14d455a97045',
    title: 'Default Visitor',
    titleImage: 'TITLE_IMAGE_NOT_FOUND',
    working: false,
    owner: 'me',
    url: '/root'
};
