import { DotCMSContentTypeField, DotCMSContentType } from 'dotcms-models';

export const dotcmsContentTypeBasicMock: DotCMSContentType = {
    baseType: '',
    clazz: '',
    defaultType: false,
    description: '',
    detailPage: '',
    expireDateVar: '',
    fields: [],
    fixed: false,
    folder: '',
    host: '',
    iDate: null,
    id: '',
    layout: [],
    modDate: null,
    multilingualable: false,
    nEntries: null,
    name: '',
    owner: '',
    publishDateVar: '',
    system: false,
    urlMapPattern: '',
    variable: '',
    versionable: false,
    workflows: [],
};

export const dotcmsContentTypeFieldBasicMock: DotCMSContentTypeField = {
    clazz: '',
    contentTypeId: '',
    dataType: '',
    defaultValue: '',
    fieldType: '',
    fieldTypeLabel: '',
    fieldVariables: [],
    fixed: true,
    hint: '',
    iDate: 100,
    id: '',
    indexed: true,
    listed: true,
    modDate: 100,
    name: '',
    readOnly: true,
    regexCheck: '',
    required: true,
    searchable: true,
    sortOrder: 100,
    unique: true,
    values: '',
    variable: ''
};
