#!/usr/bin/env bash
#
# verify-customizations.sh — assert that the dotCMS customizations of the vendored
# Spec-Kit tree are present AND effective.
#
# Why this exists: every customization this repo layers on Spec-Kit fails by ABSENCE.
# A regeneration that quietly drops the template overrides, the ADR hook or the TDD
# gates produces no error, no failing build and no visible symptom — the flow keeps
# working and simply stops asking for the dotCMS-specific content. "It ran without
# error" is therefore not evidence of anything; this script is.
#
# The name is net-new — upstream ships nothing called this — so the checker itself
# survives `specify init --here --force` without a re-apply step, exactly like the
# customizations it checks. See .specify/CUSTOMIZATIONS.md.
#
# Usage:
#   .specify/scripts/bash/verify-customizations.sh [--verbose]
#
# Exit status: 0 when every check passes, 1 when any check fails.

set -uo pipefail

SCRIPT_DIR="$(CDPATH="" cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(CDPATH="" cd -- "$SCRIPT_DIR/../../.." && pwd)"

VERBOSE=false
for arg in "$@"; do
    case "$arg" in
        --verbose|-v) VERBOSE=true ;;
        --help|-h)
            echo "Usage: $0 [--verbose]"
            echo
            echo "Asserts the dotCMS Spec-Kit customizations are present and effective."
            echo "Exits 0 when every check passes, 1 when any check fails."
            exit 0
            ;;
        *)
            echo "ERROR: Unknown option '$arg'" >&2
            exit 2
            ;;
    esac
done

PASS_COUNT=0
FAIL_COUNT=0
FAILED_NAMES=()

# Each check function prints its own explanation on failure and returns non-zero.
# `check` runs one and records the outcome. The requirement id travels with the
# description so a failure says which requirement it belongs to without a lookup.
# Read one top-level string key out of a small JSON file. Prefers jq, falls back to
# grep/sed the way common.sh does for feature.json — every other script in this
# directory provides a jq-free path, and a verifier that cannot run without jq is a
# verifier that reports false failures on a perfectly valid installation.
json_string_value() {
    local file="$1" key="$2"
    [ -f "$file" ] || { printf ''; return 0; }
    if command -v jq >/dev/null 2>&1; then
        jq -r --arg k "$key" '.[$k] // empty' "$file" 2>/dev/null
        return 0
    fi
    { grep -E "\"$key\"[[:space:]]*:" "$file" 2>/dev/null || true; } \
        | head -n 1 \
        | sed -E 's/^[^:]*:[[:space:]]*"([^"]*)".*$/\1/'
}

# Content fingerprint of every file under a directory, used to prove a read-only
# operation wrote nothing. Deliberately does not use `stat`: its format flag is -f on
# BSD and -c on GNU, and getting that wrong fails silently rather than loudly.
fingerprint_dir() {
    find "$1" -type f -exec cksum {} \; 2>/dev/null | sort
}

check() {
    local name="$1" requirement="$2" description="$3"
    shift 3
    local output status
    output="$("$@" 2>&1)"
    status=$?
    if [ $status -eq 0 ]; then
        PASS_COUNT=$((PASS_COUNT + 1))
        printf 'PASS  %-34s %s (%s)\n' "$name" "$description" "$requirement"
        if [ "$VERBOSE" = true ] && [ -n "$output" ]; then
            printf '%s\n' "$output" | sed 's/^/        /'
        fi
    else
        FAIL_COUNT=$((FAIL_COUNT + 1))
        FAILED_NAMES+=("$name")
        printf 'FAIL  %-34s %s (%s)\n' "$name" "$description" "$requirement"
        if [ -n "$output" ]; then
            printf '%s\n' "$output" | sed 's/^/        /'
        fi
    fi
}

# ---------------------------------------------------------------------------
# Checks
# ---------------------------------------------------------------------------

# T007 — the pin, the tree and the CLI that generated it must name one release.
# Today they name three, which is the drift SC-008 exists to remove.
check_version_agreement() {
    local pinned installed
    pinned=$(json_string_value "$REPO_ROOT/.specify/init-options.json" speckit_version)
    if [ -z "$pinned" ]; then
        echo "no speckit_version recorded in .specify/init-options.json"
        return 1
    fi
    if ! command -v specify >/dev/null 2>&1; then
        echo "the specify CLI is not on PATH, so the recorded version cannot be corroborated"
        return 1
    fi
    installed=$(specify --version 2>/dev/null | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | head -n1)
    if [ -z "$installed" ]; then
        echo "could not read a version from 'specify --version'"
        return 1
    fi
    if [ "$pinned" != "$installed" ]; then
        echo "the tree records $pinned but the installed CLI is $installed — a tree generated by neither"
        return 1
    fi
    # Sort-based comparison: the lowest version must be the floor for the pin to clear it.
    if [ "$(printf '%s\n1.0.9\n' "$pinned" | sort -V | head -n1)" != "1.0.9" ]; then
        echo "$pinned is older than the 1.0.9 floor this upgrade targets"
        return 1
    fi
    echo "pin, CLI and floor all agree on $pinned"
}

# T008 — v1.0.9 ships a managed .specify/.gitignore keeping machine-local state
# untracked. Its presence is how we know the regeneration reached the shared
# scaffolding and not only the skills.
check_managed_gitignore() {
    local f="$REPO_ROOT/.specify/.gitignore"
    if [ ! -f "$f" ]; then
        echo "$f does not exist — upstream ships it from v1.0.9 onward"
        return 1
    fi
    if ! grep -Eq '^[[:space:]]*feature\.json[[:space:]]*$' "$f"; then
        echo "$f exists but does not ignore feature.json, the per-checkout pointer it is meant to keep untracked"
        return 1
    fi
    echo "present and ignoring feature.json"
}

# T009 — patch #6. Upstream resolves feature paths by printing %q-quoted KEY=value
# lines that callers eval; Semgrep flags that as command injection. This is the
# regression guard: `--force` restores upstream's version, and nothing else fails.
check_no_eval_of_produced_strings() {
    local dir="$REPO_ROOT/.specify/scripts/bash"
    local offenders=""
    # An `eval` applied to a variable or command substitution — not the word in prose.
    offenders=$(grep -rnE '^[[:space:]]*eval[[:space:]]+["'"'"']?\$' "$dir" 2>/dev/null || true)
    if [ -n "$offenders" ]; then
        echo "a produced string is re-parsed as code:"
        echo "$offenders"
        return 1
    fi
    # The emission side: get_feature_paths() printing KEY=%q lines for a caller to eval.
    local emitters
    emitters=$(grep -rnE "printf[[:space:]]+'[A-Z_]+=%q" "$dir" 2>/dev/null || true)
    if [ -n "$emitters" ]; then
        echo "feature paths are emitted as %q-quoted assignments for a caller to eval:"
        echo "$emitters"
        return 1
    fi
    echo "no script under .specify/scripts/bash re-parses a produced string as code"
}

# T017 — customization #3. Resolve the templates through the override stack rather
# than stat the files: an override that still exists but no longer WINS the
# resolution is the silent failure FR-007 was written to reject, and only the
# resolving form of the check can tell the two apart.
check_overrides_win_resolution() {
    local resolver="$REPO_ROOT/.specify/scripts/bash/resolve-template.sh"
    if [ ! -x "$resolver" ]; then
        echo "$resolver is missing or not executable, so the override stack cannot be exercised"
        return 1
    fi
    local failures=0 content
    # template name -> a heading only the dotCMS override carries
    local -a names=(plan-template plan-template spec-template tasks-template)
    local -a markers=("## Legacy Impact" "## ADR Alignment (Gate)" "## Legacy Considerations" "[GATE] **Developer approval**")
    local i
    for i in "${!names[@]}"; do
        # Pin the resolver to THIS tree. resolve-template.sh derives its own root by
        # walking up from the working directory, so without SPECIFY_INIT_DIR it would
        # happily resolve against whatever .specify/ the caller happens to stand in —
        # and report a healthy override stack belonging to a different checkout.
        content=$(SPECIFY_INIT_DIR="$REPO_ROOT" "$resolver" "${names[$i]}" 2>/dev/null)
        if [ -z "$content" ]; then
            echo "resolving ${names[$i]} produced nothing"
            failures=$((failures + 1))
            continue
        fi
        if ! printf '%s' "$content" | grep -qF "${markers[$i]}"; then
            echo "${names[$i]} resolved, but without '${markers[$i]}' — the shipped template won instead of ours"
            failures=$((failures + 1))
        fi
    done
    [ "$failures" -eq 0 ] || return 1
    echo "plan, spec and tasks templates all resolve to the dotCMS overrides"
}

# T018 — customization #1. The constitution is preserved rather than regenerated
# by init, so this guards against a reset, not against an edit.
check_constitution_intact() {
    local f="$REPO_ROOT/.specify/memory/constitution.md"
    if [ ! -f "$f" ]; then
        echo "$f does not exist — the constitution was reset or removed"
        return 1
    fi
    local failures=0
    grep -qF "V. Test-First / TDD (NON-NEGOTIABLE)" "$f" || { echo "Principle V is no longer present as NON-NEGOTIABLE"; failures=$((failures + 1)); }
    grep -qF "Tests are confirmed to FAIL" "$f" || { echo "Principle V no longer requires a confirmed Red phase"; failures=$((failures + 1)); }
    grep -qF "Spec-Kit MUST NOT create, edit, or commit ADRs" "$f" || { echo "the guardrail against Spec-Kit creating ADRs is gone"; failures=$((failures + 1)); }
    [ "$failures" -eq 0 ] || return 1
    echo "Principle V and the never-create-ADRs guardrail are both intact"
}

# T019 — customizations #2, #7 and #8. A hook naming a skill that does not exist
# fails silently: the shipped skill reads extensions.yml, finds an entry, and
# dispatches a command nothing answers.
check_hooks_resolve_to_skills() {
    local f="$REPO_ROOT/.specify/extensions.yml"
    if [ ! -f "$f" ]; then
        echo "$f does not exist — all three registered hooks are gone"
        return 1
    fi
    local failures=0 hook command skill_dir
    # hook name -> command it dispatches -> whether it must be mandatory
    while IFS='|' read -r hook command optional; do
        [ -n "$hook" ] || continue
        if ! grep -qE "^[[:space:]]*${hook}:" "$f"; then
            echo "the $hook hook is not registered"
            failures=$((failures + 1))
            continue
        fi
        skill_dir="$REPO_ROOT/.claude/skills/${command//./-}"
        if [ ! -d "$skill_dir" ]; then
            echo "the $hook hook dispatches $command but $skill_dir does not exist"
            failures=$((failures + 1))
        fi
        # The flag matters as much as the name: a mandatory hook silently turned
        # optional stops firing by itself, which is exactly FR-008's failure mode.
        if ! awk -v h="$hook" '
            $0 ~ "^[[:space:]]*"h":" {found=1}
            found && /optional:/ {print; exit}
        ' "$f" | grep -qF "optional: $optional"; then
            echo "the $hook hook is no longer 'optional: $optional'"
            failures=$((failures + 1))
        fi
    done <<'HOOKS'
before_plan|speckit.adr-context|false
after_implement|speckit.converge|true
after_converge|speckit.docs-converge|false
HOOKS
    [ "$failures" -eq 0 ] || return 1
    echo "all three hooks are registered, name skills that exist, and keep their mandatory/optional flag"
}

# T020 — customizations #2, #4 and #8. These carry names upstream never ships, so
# --force cannot reach them. "Cannot" still has to be verified rather than trusted.
check_net_new_customizations_survived() {
    local failures=0 p
    for p in \
        ".claude/skills/speckit-adr-context/SKILL.md" \
        ".claude/skills/speckit-specify-fix/SKILL.md" \
        ".claude/skills/speckit-docs-converge/SKILL.md" \
        ".specify/templates/spec-issue-template.md" \
        ".specify/scripts/bash/adr-context.sh" \
        ".specify/extensions.yml" \
        ".specify/CUSTOMIZATIONS.md" \
        ".specify/templates/overrides/plan-template.md" \
        ".specify/templates/overrides/spec-template.md" \
        ".specify/templates/overrides/tasks-template.md"
    do
        if [ ! -f "$REPO_ROOT/$p" ]; then
            echo "$p was destroyed by the regeneration, although upstream ships nothing under that name"
            failures=$((failures + 1))
        fi
    done
    if [ ! -x "$REPO_ROOT/.specify/scripts/bash/adr-context.sh" ]; then
        echo "adr-context.sh exists but is not executable, so the ADR hook cannot run it"
        failures=$((failures + 1))
    fi
    [ "$failures" -eq 0 ] || return 1
    echo "all ten net-new files survived the regeneration"
}

# T021 — FR-016a. A developer returning to work started before the upgrade must
# still reach their own directory, and finding out must not modify it.
check_preexisting_feature_dir_resolves() {
    local feature="specs/37649-speckit-upgrade-latest"
    local dir="$REPO_ROOT/$feature"
    if [ ! -d "$dir" ]; then
        echo "$feature does not exist, so nothing pre-existing was exercised"
        return 1
    fi
    local before after out
    # Fingerprint with cksum rather than stat. `stat -f` is a FORMAT string on BSD and
    # means --file-system on GNU, where the format is then read as a path and every call
    # errors — so on Linux both fingerprints came back empty, the comparison was true,
    # and this check reported PASS without having compared anything. cksum is POSIX and
    # prints checksum, size and name on both; the algorithm does not matter because the
    # two runs are always on the same machine. It also compares CONTENT, which is what
    # "was this directory written to" actually means.
    before=$(fingerprint_dir "$dir")
    # An empty fingerprint must never be mistaken for "nothing changed". This guard is
    # the durable half of the fix: whatever tool is used, a fingerprint that produces
    # nothing fails the check instead of silently satisfying it.
    if [ -z "$before" ]; then
        echo "could not fingerprint $feature — it contains $(find "$dir" -type f | wc -l | tr -d ' ') files but the fingerprint came back empty, so the read-only property cannot be checked"
        return 1
    fi
    out=$(cd "$REPO_ROOT" && SPECIFY_FEATURE_DIRECTORY="$feature" \
        .specify/scripts/bash/check-prerequisites.sh --json --paths-only 2>&1)
    if ! printf '%s' "$out" | grep -qF "$feature/spec.md"; then
        echo "resolving the pre-existing directory did not return its own spec.md:"
        echo "$out"
        return 1
    fi
    after=$(fingerprint_dir "$dir")
    if [ "$before" != "$after" ]; then
        echo "resolution modified the pre-existing feature directory; it must be read-only"
        diff <(printf '%s\n' "$before") <(printf '%s\n' "$after") | head -10
        return 1
    fi
    echo "a spec directory created before the upgrade still resolves, and resolution wrote nothing"
}

# T034 — FR-013/FR-013a. The shipped skill set is DERIVED from the tree, never
# hard-coded at ten: a release that adds, removes or renames a shipped skill must
# still be fully covered, and a review record silently missing its new row is the
# failure this guards against.
check_shipped_skills_all_reviewed() {
    local record="$REPO_ROOT/specs/37649-speckit-upgrade-latest/shipped-skills-review.md"
    if [ ! -f "$record" ]; then
        echo "$record does not exist — no shipped skill has a reviewed diff on record"
        return 1
    fi
    local skills_dir="$REPO_ROOT/.claude/skills"
    local failures=0 reviewed=0 name
    for dir in "$skills_dir"/speckit-*/; do
        [ -d "$dir" ] || continue
        name=$(basename "$dir")
        # Ours, not upstream's — these are net-new names and are not part of the
        # shipped set FR-013 requires a row for.
        case "$name" in
            speckit-adr-context|speckit-specify-fix|speckit-docs-converge) continue ;;
        esac
        # A row for the skill, carrying a verdict in its last column.
        local row
        row=$(grep -E "^\|[[:space:]]*\`?${name}\`?[[:space:]]*\|" "$record" | head -n1)
        if [ -z "$row" ]; then
            echo "$name has no row in the review record — an omitted row and an unreviewed skill are indistinguishable"
            failures=$((failures + 1))
            continue
        fi
        # Last non-empty cell is the verdict; refuse a row that was left blank.
        local verdict
        verdict=$(printf '%s' "$row" | awk -F'|' '{gsub(/^[ \t]+|[ \t]+$/, "", $(NF-1)); print $(NF-1)}')
        if [ -z "$verdict" ]; then
            echo "$name has a row but no verdict — silence is not an acceptable entry"
            failures=$((failures + 1))
            continue
        fi
        reviewed=$((reviewed + 1))
    done
    if [ "$reviewed" -eq 0 ] && [ "$failures" -eq 0 ]; then
        echo "no shipped skills were found to review, which cannot be right"
        return 1
    fi
    [ "$failures" -eq 0 ] || return 1
    echo "all $reviewed shipped skills in this release have a row with a verdict"
}

# T041 — FR-006. Timestamp numbering is collision-free by construction, so the
# branch-aware patch is retired rather than re-applied. Two things must hold, and the
# second is the one that keeps SC-007's count of upstream-owned files we modify at one.
check_numbering_is_collision_free() {
    local opts="$REPO_ROOT/.specify/init-options.json"
    local script="$REPO_ROOT/.specify/scripts/bash/create-new-feature.sh"
    local failures=0 numbering
    numbering=$(json_string_value "$opts" feature_numbering)
    if [ "$numbering" != "timestamp" ]; then
        echo "feature_numbering is '${numbering:-unset}', not 'timestamp' — sequential numbering in this repo derives its next number from the issue-numbered spec directories and produces a value that looks like a GitHub issue number and is not one"
        failures=$((failures + 1))
    fi
    # Patch #5 retired: the branch scan it added must be gone, not partially re-applied.
    if grep -q 'get_highest_from_branches' "$script" 2>/dev/null; then
        echo "create-new-feature.sh still carries get_highest_from_branches — the branch-aware patch was re-applied, which raises the count of upstream-owned files we modify back to two"
        failures=$((failures + 1))
    fi
    # Strongest available statement, when a reference checkout of the release is at hand.
    # Optional by design: a developer verifying a year from now will not have one.
    if [ -n "${SPECKIT_UPSTREAM_DIR:-}" ] && [ -f "$SPECKIT_UPSTREAM_DIR/scripts/bash/create-new-feature.sh" ]; then
        if ! diff -q "$script" "$SPECKIT_UPSTREAM_DIR/scripts/bash/create-new-feature.sh" >/dev/null 2>&1; then
            echo "create-new-feature.sh differs from the release source at $SPECKIT_UPSTREAM_DIR"
            diff "$script" "$SPECKIT_UPSTREAM_DIR/scripts/bash/create-new-feature.sh" | head -10
            failures=$((failures + 1))
        else
            echo "byte-identical to the release source as well"
        fi
    fi
    [ "$failures" -eq 0 ] || return 1
    echo "numbering is timestamp and create-new-feature.sh carries no local patch"
}

# T045 — the numbering setting only reaches the flow through whoever reads it.
# create-new-feature.sh does NOT read init-options.json; it only accepts --timestamp.
# The shipped /speckit-specify honours feature_numbering itself, but our fix skill
# delegates to the script, so it has to pass the flag or the fix flow silently keeps
# numbering sequentially — collisions intact, with nothing to show for the setting.
check_fix_flow_honours_numbering() {
    local skill="$REPO_ROOT/.claude/skills/speckit-specify-fix/SKILL.md"
    local numbering
    numbering=$(json_string_value "$REPO_ROOT/.specify/init-options.json" feature_numbering)
    if [ ! -f "$skill" ]; then
        echo "$skill does not exist"
        return 1
    fi
    if [ "$numbering" != "timestamp" ]; then
        echo "feature_numbering is '${numbering:-unset}'; this check covers the timestamp setting only"
        return 1
    fi
    if ! grep -qF 'feature_numbering' "$skill"; then
        echo "the fix skill never consults feature_numbering, so it delegates to create-new-feature.sh with whatever the script defaults to — sequential — and the setting has no effect on the fix flow"
        return 1
    fi
    if ! grep -qF -- '--timestamp' "$skill"; then
        echo "the fix skill mentions feature_numbering but never passes --timestamp, which is the only way create-new-feature.sh can honour it"
        return 1
    fi
    echo "the fix flow reads feature_numbering and passes --timestamp, so both spec flows number the same way"
}

# T047 — FR-020/FR-021/SC-006. A reader must be able to learn, from CUSTOMIZATIONS.md
# alone, which version we are on and what a future upgrade has to re-apply — and every
# statement they read must match the tree.
check_customizations_describes_this_tree() {
    local doc="$REPO_ROOT/.specify/CUSTOMIZATIONS.md"
    local opts="$REPO_ROOT/.specify/init-options.json"
    if [ ! -f "$doc" ]; then
        echo "$doc does not exist"
        return 1
    fi
    local failures=0 version
    version=$(json_string_value "$opts" speckit_version)

    # 1. It names the version the tree actually records.
    if ! grep -qF "$version" "$doc"; then
        echo "the document never names $version, the version the tree records"
        failures=$((failures + 1))
    fi

    # 2. Superseded-version mentions are history, not claims about the present.
    #    A blanket ban on the string would forbid the sentence explaining what we
    #    upgraded FROM, which is exactly what the next upgrader needs. So the check
    #    targets present-tense claims instead: a line may mention 0.12.4 freely, but
    #    not while asserting that it is what we are on.
    #    Tense is the discriminator, so the present-tense marker must not be sitting
    #    inside a past-tense sentence: "it was previously pinned to v0.12.4" is the
    #    clearest way to write the history and must not be forbidden.
    local stale
    stale=$(grep -nE '0\.12\.4' "$doc" \
        | grep -iE 'pinned to|we are on|currently|is pinned' \
        | grep -ivE 'was |were |previously|used to|until the upgrade|before the upgrade' || true)
    if [ -n "$stale" ]; then
        echo "0.12.4 is still presented as the current state rather than as history:"
        echo "$stale"
        failures=$((failures + 1))
    fi

    # 3. The re-apply table no longer carries a row for the retired patch.
    if grep -qE '^\|.*create-new-feature\.sh.*\|' "$doc"; then
        echo "the re-apply table still has a create-new-feature.sh row, but patch #5 was retired"
        failures=$((failures + 1))
    fi

    # 4. The net-new custom skills are counted as three, not two.
    if grep -qiE 'two (net-new )?custom skills|adds (two|2) customizations' "$doc"; then
        echo "the document still enumerates two net-new custom skills; there are three"
        failures=$((failures + 1))
    fi
    if ! grep -qiE 'three (net-new )?(custom )?skills' "$doc"; then
        echo "the document never states that there are three net-new custom skills"
        failures=$((failures + 1))
    fi

    [ "$failures" -eq 0 ] || return 1
    echo "the document names $version, treats 0.12.4 as history, drops the retired patch row, and counts three net-new skills"
}

# >>> CHECKS END (new check functions are inserted above this line)

# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------

run_all_checks() {
    :
    check version-agreement       "FR-002, SC-008"        "pin, installed CLI and 1.0.9 floor agree" check_version_agreement
    check managed-gitignore       "research.md R6"        "v1.0.9 .specify/.gitignore keeps feature.json untracked" check_managed_gitignore
    check no-eval                 "FR-004, FR-005, SC-003" "no vendored script re-parses a produced string as code" check_no_eval_of_produced_strings
    check overrides-win           "FR-007"                "the three dotCMS template overrides win resolution" check_overrides_win_resolution
    check constitution-intact     "FR-009"                "Principle V and the never-create-ADRs guardrail survive" check_constitution_intact
    check hooks-resolve           "FR-012"                "all three hooks name skills that exist" check_hooks_resolve_to_skills
    check net-new-survived        "FR-010, FR-011"        "files upstream never ships survived --force" check_net_new_customizations_survived
    check preexisting-feature-dir "FR-016a, SC-009"       "a pre-upgrade spec directory still resolves, read-only" check_preexisting_feature_dir_resolves
    check shipped-skills-reviewed "FR-013, FR-013a, SC-005" "every shipped skill has a reviewed diff on record" check_shipped_skills_all_reviewed
    check numbering-collision-free "FR-006, SC-004, SC-007" "timestamp numbering, branch-aware patch retired" check_numbering_is_collision_free
    check fix-flow-numbering      "FR-006, FR-019, SC-004" "the fix flow numbers the same way as the feature flow" check_fix_flow_honours_numbering
    check customizations-current  "FR-020, FR-021, SC-006" "CUSTOMIZATIONS.md describes the tree that exists" check_customizations_describes_this_tree
    # >>> RUNNER END (new check invocations are inserted above this line)
}

echo "Verifying dotCMS Spec-Kit customizations in $REPO_ROOT"
echo

run_all_checks

echo
TOTAL=$((PASS_COUNT + FAIL_COUNT))
if [ "$TOTAL" -eq 0 ]; then
    echo "No checks registered."
    exit 0
fi

if [ "$FAIL_COUNT" -eq 0 ]; then
    echo "$PASS_COUNT/$TOTAL checks passed."
    exit 0
fi

echo "$PASS_COUNT/$TOTAL checks passed, $FAIL_COUNT failed: ${FAILED_NAMES[*]}"
exit 1
