const { withNx } = require('@nx/rollup/with-nx');

const { typesFirstPlugin } = require('../../../tools/rollup/types-first.cjs');

// Same build as @dotcms/client: ESM and CJS, compiled with tsc, exports field generated by
// Nx. Three entries: the root one (events and its config type), ./markup (experimentMarkup)
// and ./react (the React adapter). The root entry shares only the constants with the other
// two, so pages that load the engine never download the boot script builder. React stays
// external: it is an optional peer.
const options = {
    format: ['esm', 'cjs'],
    compiler: 'tsc',
    generateExportsField: true,
    outputPath: '../../../dist/libs/sdk/events',
    // Only the README ships: CLAUDE.md is for working on this repo, not for the package's users
    assets: [
        {
            input: 'libs/sdk/events',
            output: '.',
            glob: 'README.md'
        }
    ],
    main: './src/index.ts',
    additionalEntryPoints: ['./src/markup.ts', './src/react.ts'],
    tsConfig: './tsconfig.lib.json'
};

const config = withNx(options, {
    // Provide additional rollup configuration here. See: https://rollupjs.org/configuration-options
});

// Nx writes `module` before `types`, and conditions are order-sensitive, so TypeScript never
// reaches the declarations. Reorders keys only — every target is left as Nx set it.
const outputDir = Array.isArray(config.output) ? config.output[0]?.dir : config.output?.dir;

config.plugins = [
    ...(Array.isArray(config.plugins) ? config.plugins : []),
    typesFirstPlugin(outputDir)
];

module.exports = config;
