// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 
:manmanual: Content-type Manual
:mansource: 
:man-linkstyle: pass:[blue R < >]
= content-type-pull(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

content-type-pull - *Retrieves Content-types descriptors*

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*content-type pull* [*-h*] [*-fmt*=_<inputOutputFormat>_] [*--workspace*=_<file>_]
                  [_idOrName_]

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

  This command fetches and saves the descriptor information
  for Content-types within the dotCMS instance. By default, it
  retrieves descriptors for all Content-types, unless a specific
  Content-type's name or ID is provided as an argument.
  The descriptors are saved into files named after each Content-type's
  variable name.

  When a Content-type is pulled more than once, the existing descriptor file
  is overwritten. All descriptor files are saved within the 'content-types'
  folder located in the dotCMS workspace, which is created in the
  current directory by default, unless an alternative workspace is specified.

  The output format for the descriptor files is JSON by default. However,
  you can specify the YAML format using the --format option
  if YAML is preferred.


// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
== Options

*-fmt, --format*=_<inputOutputFormat>_::
  Enum values: JSON, YAML, YML

*-h*, *--help*::
  Display this help message.

*--workspace*=_<file>_::
  The workspace directory.
+
Current directory is used if not specified

// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
== Arguments

[_idOrName_]::
  Identifier or Name.

// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
