// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 
:manmanual: Content-type Manual
:mansource: 
:man-linkstyle: pass:[blue R < >]
= content-type-pull(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

content-type-pull - *Retrieves Content-types descriptors*

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*content-type pull* [*-h*] [*-ff*] [*--dotcms-url*=_<remoteURL>_]
                  [*-fmt*=_<inputOutputFormat>_] [*--retry-attempts*=_<retryAttempts>_]
                  [*-tk*=_<token>_] [*--workspace*=_<file>_] [_idOrName_]

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

  This command fetches and saves the descriptor information
  for Content-types within the dotCMS instance. By default, it
  retrieves descriptors for all Content-types, unless a specific
  Content-type's name or ID is provided as an argument.
  The descriptors are saved into files named after each Content-type's
  variable name.

  When a Content-type is pulled more than once, the existing descriptor file
  is overwritten. All descriptor files are saved within the 'content-types'
  folder located in the dotCMS workspace, which is created in the
  current directory by default, unless an alternative workspace is specified.

  The output format for the descriptor files is JSON by default. However,
  you can specify the YAML format using the --format option
  if YAML is preferred.


// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
== Options

*--dotcms-url*=_<remoteURL>_::
  The dotCMS URL to connect to. This option must be used along with the token option, which provides the token for the specified dotCMS URL.

*-ff, --fail-fast*::
  Stop at first failure and exit the command. By default, this option is disabled, and the command will continue on error.

*-fmt, --format*=_<inputOutputFormat>_::
  Format for the pulled descriptor files. 
+
Supported values: JSON, YAML, YML

*-h*, *--help*::
  Display this help message.

*--retry-attempts*=_<retryAttempts>_::
  Number of retry attempts on errors. By default, this option is disabled, and the command will not retry on error.

*-tk, --token*=_<token>_::
  A dotCMS token to use for authentication. 

*--workspace*=_<file>_::
  The workspace directory.
+
Current directory is used if not specified

// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
== Arguments

[_idOrName_]::
  Identifier or Name.

// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
