// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 
:manmanual: Language Manual
:mansource: 
:man-linkstyle: pass:[blue R < >]
= language-push(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

language-push - *Push languages*

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*language push* [*-h*] [*-dau*] [*--dry-run*] [*-ff*] [*-rl*] [*-w*[=_watch_]]
              [*--byIso*=_<languageIso>_] [*--dotcms-url*=_<remoteURL>_]
              [*--retry-attempts*=_<retryAttempts>_] [*-tk*=_<token>_] [_path_]

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

This command enables the pushing of languages to the server. It accommodates the specification of either a language file or a folder path. In addition to these options, it also facilitates the creation of a new language through the provision of a language iso code (e.g.: en-us).


// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
== Options

*--byIso*=_<languageIso>_::
  Code to be used to create a new language. Used when no file is specified. For example: en-us

*-dau, --disable-auto-update*::
  Disable the default behaviour of updating the local file descriptor with the 
+
response from the server after a push. When this option is used, the 
+
local file will remain in its initial state even after a successful push.

*--dotcms-url*=_<remoteURL>_::
  The dotCMS URL to connect to. This option must be used along with the token option, which provides the token for the specified dotCMS URL.

*--dry-run*::
  When this option is enabled, the push process displays information about the changes that would be made on 
+
the remote server without actually pushing those changes. No modifications will be made to the remote server. 
+
By default, this option is disabled, and the changes will be applied to the remote server.

*-ff, --fail-fast*::
  Stop at first failure and exit the command. By default, this option is disabled, 
+
and the command will continue on error.

*-h*, *--help*::
  Display this help message.

*--retry-attempts*=_<retryAttempts>_::
  Number of retry attempts on errors. By default, this option is disabled, 
+
and the command will not retry on error.

*-rl, --removeLanguages*::
  When this option is enabled, the push process allows the deletion of languages in the remote server. By default, this option is disabled, and languages will not be removed on the remote server.

*-tk, --token*=_<token>_::
  A dotCMS token to use for authentication. 

*-w*, *--watch*[=_watch_]::
  When this option is enabled the tool observes changes in the file system within the push path
+
If a change is detected the push command being executed gets triggered. 
+
The auto-update feature is disabled when watch mode is on
+
The default watch interval is 2 seconds, but it can be specified passing an integer value with this option.
+
e.g. --watch 5

// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
== Arguments

[_path_]::
  local directory or file to push

// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
