export const FIELD_ICONS = {
    'com.dotcms.contenttype.model.field.ImmutableBinaryField': 'fa-file',
    'com.dotcms.contenttype.model.field.ImmutableCategoryField': 'fa-list',
    'com.dotcms.contenttype.model.field.ImmutableCheckboxField': 'fa-check-square-o',
    'com.dotcms.contenttype.model.field.ImmutableConstantField': 'fa-square-o',
    'com.dotcms.contenttype.model.field.ImmutableCustomField': 'fa-code',
    'com.dotcms.contenttype.model.field.ImmutableDateField': 'fa-calendar',
    'com.dotcms.contenttype.model.field.ImmutableDateTimeField': 'fa-calendar-o',
    'com.dotcms.contenttype.model.field.ImmutableFileField': 'fa-file',
    'com.dotcms.contenttype.model.field.ImmutableHiddenField': 'fa-eye-slash',
    'com.dotcms.contenttype.model.field.ImmutableHostFolderField': 'fa-server',
    'com.dotcms.contenttype.model.field.ImmutableImageField': 'fa-picture-o',
    'com.dotcms.contenttype.model.field.ImmutableKeyValueField': 'fa-key',
    'com.dotcms.contenttype.model.field.ImmutableMultiSelectField': 'fa-bars',
    'com.dotcms.contenttype.model.field.ImmutablePermissionTabField': 'fa-lock',
    'com.dotcms.contenttype.model.field.ImmutableRadioField': 'fa-dot-circle-o',
    'com.dotcms.contenttype.model.field.ImmutableRelationshipsTabField': 'fa-clone',
    'com.dotcms.contenttype.model.field.ImmutableSelectField': 'fa-circle',
    'com.dotcms.contenttype.model.field.ImmutableTagField': 'fa-tag',
    'com.dotcms.contenttype.model.field.ImmutableTextAreaField': 'fa-paragraph',
    'com.dotcms.contenttype.model.field.ImmutableTextField': 'fa-font',
    'com.dotcms.contenttype.model.field.ImmutableTimeField': 'fa-clock-o',
    'com.dotcms.contenttype.model.field.ImmutableWysiwygField': 'fa-eye'
 };
