/**
 * Pure spec-transform logic (no I/O), so it can be unit-tested without a network fetch.
 *
 * Given a raw dotCMS OpenAPI document, produce a smaller, model-facing spec:
 *   - keep only allowed endpoints (ALLOWED_PREFIXES minus EXCLUDED_PATTERNS), drop deprecated ops
 *   - replace ONLY Jersey-autogenerated multipart schemas with a simple placeholder (curated,
 *     hand-annotated multipart schemas are kept)
 *   - keep request/response `$ref`s as-is (NOT dereferenced) — this dedupes shared schemas and
 *     is naturally acyclic, so the model can read a small ref-labelled endpoint and then resolve
 *     only the schemas it actually needs (progressive disclosure via the `resolveRef` sandbox helper)
 *   - emit `components.schemas` pruned to just the schemas transitively referenced by kept paths
 */

export const ALLOWED_PREFIXES = [
    '/api/v1/contenttype',
    '/api/v1/page',
    '/api/v1/page-scanner/a11y/check',
    '/api/v1/page-scanner/geo/check',
    '/api/v1/nav',
    '/api/v1/workflow',
    '/api/v1/categories',
    '/api/v2/tags',
    '/api/v1/folder',
    '/api/v1/site',
    '/api/v2/languages',
    '/api/v1/roles',
    '/api/v1/user',
    '/api/v1/containers',
    '/api/v1/themes',
    '/api/v1/templates',
    '/api/v1/content/_search',
    '/api/v2/assets'
];

export const EXCLUDED_PATTERNS = [
    '/api/v1/workflow/tasks/**',
    '/api/v1/contenttype/page',
    '/api/v1/contenttype/render/id/**',
    '/api/v1/categories/_export',
    '/api/v1/categories/_sort',
    '/api/v1/folder/{id}/file-browser-selected',
    '/api/v1/folder/siteId/{siteId}/path/{path}',
    '/api/v1/site/{siteId}/setup_progress',
    '/api/v1/site/thumbnails',
    '/api/v1/site/variable/{siteId}',
    '/api/v1/site/switch',
    '/api/v1/languages/i18n',
    '/api/v1/roles/{roleId}/layouts',
    '/api/v1/roles/{roleid}/rolehierarchyanduserroles',
    '/api/v1/roles/layouts',
    '/api/v1/containers/{containerId}/content/{contentletId}',
    '/api/v1/containers/{containerId}/form/{formId}',
    '/api/v1/containers/form/{formId}',
    '/api/v1/containers/live',
    '/api/v1/containers/working',
    '/api/v1/templates/_savepublish',
    '/api/v1/templates/{templateId}/live',
    '/api/v1/templates/{templateId}/working',
    '/api/v1/templates/image',
    '/api/v1/workflow/actions/separator',
    '/api/v1/sites/{siteId}/ruleengine/'
];

const SCHEMA_REF_PREFIX = '#/components/schemas/';

/**
 * Matches a path against a pattern. Pattern syntax:
 *   - `{name}` or `*` — matches a single path segment (anything except `/`)
 *   - `**` — matches any number of segments
 *   - everything else is matched literally
 * Match is exact (anchored at both ends).
 */
export function matchesPattern(pathKey: string, pattern: string): boolean {
    const regex = new RegExp(
        '^' +
            pattern
                .replace(/[.+?^$()|[\]\\]/g, '\\$&')
                .replace(/\{[^}]+\}/g, '[^/]+')
                .replace(/\*\*/g, '.*')
                .replace(/(?<!\.)\*/g, '[^/]+') +
            '$'
    );
    return regex.test(pathKey);
}

/** A Jersey-autogenerated multipart body, either as the `FormDataMultiPart` $ref or its inline shape. */
function isJerseyMultipart(schema: Record<string, unknown> | undefined): boolean {
    if (!schema) return true; // no schema at all — nothing worth keeping
    const ref = schema.$ref;
    if (typeof ref === 'string' && ref.endsWith('/FormDataMultiPart')) return true;
    const props = schema.properties as Record<string, unknown> | undefined;
    return !!props && ('bodyParts' in props || 'messageBodyWorkers' in props);
}

const MULTIPART_PLACEHOLDER = {
    schema: {
        type: 'object',
        description: 'Multipart form. See endpoint description for fields.',
        properties: {
            file: { type: 'string', format: 'binary' }
        }
    }
};

export interface TransformStats {
    pathCount: number;
    schemaCount: number;
    /** Schema names referenced by kept paths but missing from `components.schemas`. */
    danglingRefs: string[];
}

export interface TransformResult {
    spec: Record<string, unknown>;
    stats: TransformStats;
}

/**
 * Collect every schema name transitively reachable from `node` via `$ref`. Follows
 * schema→schema references (an `allOf`/`items`/`properties` ref is just a nested object,
 * so the generic walk covers it). The `needed` guard makes ref cycles terminate.
 */
function collectSchemaRefs(
    node: unknown,
    allSchemas: Record<string, unknown>,
    needed: Set<string>,
    dangling: Set<string>
): void {
    if (Array.isArray(node)) {
        for (const item of node) collectSchemaRefs(item, allSchemas, needed, dangling);
        return;
    }
    if (!node || typeof node !== 'object') return;

    const obj = node as Record<string, unknown>;
    const ref = obj.$ref;
    if (typeof ref === 'string') {
        if (!ref.startsWith(SCHEMA_REF_PREFIX)) {
            // Future-proofing: today the dotCMS spec only uses #/components/schemas refs.
            console.warn(`[generate-spec] Skipping non-schema $ref: ${ref}`);
            return;
        }
        const name = ref.slice(SCHEMA_REF_PREFIX.length);
        if (!needed.has(name)) {
            if (allSchemas[name] === undefined) {
                dangling.add(name);
                return;
            }
            needed.add(name);
            collectSchemaRefs(allSchemas[name], allSchemas, needed, dangling);
        }
        return;
    }

    for (const value of Object.values(obj)) {
        collectSchemaRefs(value, allSchemas, needed, dangling);
    }
}

/** Transform a raw OpenAPI document into the pruned, ref-preserving model-facing spec. */
export function transformSpec(raw: Record<string, unknown>): TransformResult {
    const allPaths = (raw.paths || {}) as Record<string, unknown>;
    const allSchemas = ((raw.components as Record<string, unknown> | undefined)?.schemas ||
        {}) as Record<string, unknown>;

    const filteredPaths: Record<string, unknown> = {};

    for (const [pathKey, pathValue] of Object.entries(allPaths)) {
        const isAllowed = ALLOWED_PREFIXES.some((prefix) => pathKey.startsWith(prefix));
        const isExcluded = EXCLUDED_PATTERNS.some((pattern) => matchesPattern(pathKey, pattern));
        if (!isAllowed || isExcluded) continue;

        const methods = pathValue as Record<string, unknown>;
        const keptMethods: Record<string, unknown> = {};

        for (const [method, methodValue] of Object.entries(methods)) {
            if (typeof methodValue !== 'object' || methodValue === null) {
                keptMethods[method] = methodValue;
                continue;
            }
            if ((methodValue as Record<string, unknown>).deprecated === true) {
                continue;
            }

            const op = { ...(methodValue as Record<string, unknown>) };

            // Replace ONLY Jersey-autogenerated multipart schemas (noisy internal types like
            // bodyParts/messageBodyWorkers) with a placeholder. Curated, hand-annotated multipart
            // schemas (WorkflowActionMultipartSchema, CategoryImportFormSchema, inline asset forms)
            // are kept — they carry the field descriptions this change exists to preserve. Runs
            // BEFORE the ref walk so Jersey subtrees never enter components.schemas.
            const requestBody = op.requestBody as Record<string, unknown> | undefined;
            const requestContent = requestBody?.content as Record<string, unknown> | undefined;
            const multipart = requestContent?.['multipart/form-data'] as
                | Record<string, unknown>
                | undefined;
            if (
                requestContent &&
                multipart &&
                isJerseyMultipart(multipart.schema as Record<string, unknown> | undefined)
            ) {
                requestContent['multipart/form-data'] = MULTIPART_PLACEHOLDER;
            }

            keptMethods[method] = op;
        }

        if (Object.keys(keptMethods).length > 0) {
            filteredPaths[pathKey] = keptMethods;
        }
    }

    // Walk the kept paths to find every transitively-referenced schema, then emit only those.
    const needed = new Set<string>();
    const danglingSet = new Set<string>();
    collectSchemaRefs(filteredPaths, allSchemas, needed, danglingSet);

    const schemas: Record<string, unknown> = {};
    for (const name of [...needed].sort()) {
        schemas[name] = allSchemas[name];
    }

    const spec: Record<string, unknown> = {
        openapi: raw.openapi,
        info: raw.info,
        paths: filteredPaths,
        components: { schemas }
    };
    if (raw.servers) {
        spec.servers = raw.servers;
    }

    return {
        spec,
        stats: {
            pathCount: Object.keys(filteredPaths).length,
            schemaCount: Object.keys(schemas).length,
            danglingRefs: [...danglingSet].sort()
        }
    };
}
