/// <reference types="vitest" />
import angular from '@analogjs/vite-plugin-angular';
import { defineConfig } from 'vite';
import tsconfigPaths from 'vite-tsconfig-paths';

import { resolve } from 'path';

/**
 * GENERATED by tools/generate-vite-configs.mjs from this project's jest.config.ts.
 * Regenerate rather than hand-editing where possible; see research.md R-16 for why
 * each block is here and which failure it prevents.
 */
const WORKSPACE = resolve(import.meta.dirname, '../..');
const PROJECT = 'libs/utils';

export default defineConfig({
    // The workspace, not the project: sibling libs resolve through tsconfig paths to
    // their TypeScript source, and the Angular plugin only compiles under root.
    root: WORKSPACE,
    plugins: [
        angular({
            tsconfig: resolve(import.meta.dirname, 'tsconfig.spec.json'),
            workspaceRoot: WORKSPACE
        }),
        // Pinned to the base tsconfig AND this project's spec tsconfig. Pinning only
        // the base broke sibling-alias resolution: @dotcms/types resolved to a
        // root-relative '/libs/sdk/types/src/index.ts' (no core-web prefix) and cost
        // sdk-uve 94 of its 103 tests. Pinning nothing fixes that too, but then the
        // plugin crawls every tsconfig in the monorepo and segfaults the native
        // resolver on CI — the failure the original pin existed to prevent. Two
        // entries keep both properties.
        tsconfigPaths({
            root: WORKSPACE,
            // ABSOLUTE, not relative. `nx test` runs bare `vitest` with cwd set to the
            // project directory, so relative entries here resolve against the wrong
            // place and the plugin silently loads no tsconfig at all — sibling aliases
            // then fail and the project reports green on a fraction of its tests
            // (sdk-uve: 9 of 103 via `nx test`, 103 of 103 via `vitest --config`).
            // Validating a config through a different invocation than production uses
            // is how that went unnoticed for a full cycle.
            projects: [
                resolve(WORKSPACE, 'tsconfig.base.json'),
                resolve(WORKSPACE, PROJECT, 'tsconfig.spec.json')
            ]
        })
    ],
    // No `mainFields: ['module']` here, deliberately. Forcing that single field made
    // Vite skip packages that only declare `main` — @analogjs/vitest-angular among them
    // — and resolution fell back to a bogus root-relative path
    // (`/node_modules/.pnpm/…/setup-zone.js`), taking down 16 projects with an error
    // that named the package but not the cause.
    resolve: {},
    test: {
        root: WORKSPACE,
        globals: true,
        // Carried across from jest.config.ts (FR-007). Without pinning it the project
        // would silently adopt Vitest's default instead.
        environment: 'jsdom',
        setupFiles: ['libs/utils/src/test-setup.ts'],
        include: [
            `${PROJECT}/src/**/*.spec.ts`,
            `${PROJECT}/src/**/*.spec.tsx`,
            `${PROJECT}/src/**/*.test.ts`,
            `${PROJECT}/src/**/*.test.tsx`
        ],
        // Jest gave each spec file a fresh module registry; state this rather than
        // inherit it, so the semantics the specs were written under stay explicit.
        isolate: true,
        server: {
            // A LIST, not `true`. Both were measured. `inline: true` clears the 420
            // NG0203 errors in dotcms-ui but is slower and inlines dependencies that
            // do not need it; the list keeps resolution closer to how Jest behaved.
            // Everything that imports @angular/core must resolve to ONE instance —
            // Angular, Spectator, zone.js, PrimeNG, @primeuix, @ngrx — plus the ESM
            // chain each project's jest.config.ts already listed in
            // transformIgnorePatterns.
            //
            // NOT the cause of the 16 projects that currently fail to load: those fail
            // identically under both settings (sdk-ai: "Cannot find module
            // './define-adapter'"; dot-users: "Cannot use import statement outside a
            // module"), so the cause is elsewhere in the generated config and is still
            // open.
            deps: {
                inline: [
                    /@angular\//,
                    /@openng\/spectator/,
                    /zone\.js/,
                    /primeng/,
                    /@primeuix/,
                    /@ngrx/,
                    /y-protocols/,
                    /y-prosemirror/,
                    /lib0/,
                    /@tiptap/,
                    /marked/,
                    /lowlight/,
                    /devlop/
                ]
            }
        },
        reporters: [
            'default',
            'github-actions',
            ['junit', { outputFile: 'target/core-web-reports/utils.xml' }]
        ],
        coverage: {
            provider: 'v8',
            reporter: ['html', 'lcov', 'text'],
            reportsDirectory: 'coverage/libs/utils'
        }
    }
});
