import { Extension } from '@tiptap/core';
import { Node as PMNode } from '@tiptap/pm/model';
import { EditorState, Plugin, PluginKey, Transaction } from '@tiptap/pm/state';

const PLUGIN_KEY = new PluginKey('tableScopeAutoAssign');

/**
 * Walks every `<table>` in the document and stages `scope` attribute updates on `<th>` cells
 * whose `scope` is still unset. Returns the transaction when at least one cell was updated,
 * or `null` when the doc is already in a consistent state (so callers can skip dispatching).
 */
function buildAutoScopeTransaction(state: EditorState): Transaction | null {
    const tr = state.tr;
    let changed = false;

    state.doc.descendants((node, pos): boolean => {
        if (node.type.name !== 'table') return true;

        node.forEach((row, rowOffset, rowIndex) => {
            const isFirstRow = rowIndex === 0;
            const rowStart = pos + 1 + rowOffset;

            row.forEach((cell, cellOffset, cellIndex) => {
                if (cell.type.name !== 'tableHeader') return;

                const existing = cell.attrs['scope'];
                if (existing != null && existing !== '') return;

                const desired = isFirstRow ? 'col' : cellIndex === 0 ? 'row' : null;
                if (!desired) return;

                const cellPos = rowStart + 1 + cellOffset;
                tr.setNodeAttribute(cellPos, 'scope', desired);
                changed = true;
            });
        });

        // Children visited via node.forEach above — no need to descend further.
        return false;
    });

    if (!changed) return null;
    tr.setMeta(PLUGIN_KEY, true);
    return tr;
}

/**
 * Auto-fills `scope` on `<th>` cells based on their position so screen readers can
 * resolve column-vs-row header relationships (WCAG 1.3.1).
 *
 *   - first row → `scope="col"`
 *   - first column (when the cell is a `<th>`) → `scope="row"`
 *
 * Runs in `appendTransaction` only after doc-changing transactions, and is **idempotent**:
 * it never touches a cell whose `scope` is already a non-null string. That preserves any
 * value the author set explicitly (e.g. `colgroup`, `rowgroup`) via the toolbar select.
 *
 * Skipped when the previous transaction was generated by this plugin (`tr.getMeta` guard)
 * to avoid recursive amplification when several tables exist in the same doc.
 */
export const TableScopeAutoAssign = Extension.create({
    name: 'tableScopeAutoAssign',

    addProseMirrorPlugins() {
        return [
            new Plugin({
                key: PLUGIN_KEY,
                /**
                 * Runs once when the editor view mounts. ProseMirror builds the initial
                 * state directly from the schema — that build does not flow through any
                 * transaction, so `appendTransaction` would otherwise never see legacy
                 * tables already in the doc.
                 */
                view: (view) => {
                    const tr = buildAutoScopeTransaction(view.state);
                    if (tr) view.dispatch(tr);
                    return {};
                },
                appendTransaction: (transactions, _oldState, newState) => {
                    if (!transactions.some((tr) => tr.docChanged)) return null;
                    if (transactions.some((tr) => tr.getMeta(PLUGIN_KEY))) return null;
                    return buildAutoScopeTransaction(newState);
                }
            })
        ];
    }
});

/**
 * Exposed for unit-testing: returns the position-derived scope for a given cell
 * inside a table node, mirroring the plugin's logic. `null` means leave untouched.
 */
export function computeAutoScope(
    table: PMNode,
    rowIndex: number,
    cellIndex: number
): 'col' | 'row' | null {
    if (rowIndex < 0 || rowIndex >= table.childCount) return null;
    const row = table.child(rowIndex);
    if (cellIndex < 0 || cellIndex >= row.childCount) return null;
    const cell = row.child(cellIndex);
    if (cell.type.name !== 'tableHeader') return null;
    if (rowIndex === 0) return 'col';
    if (cellIndex === 0) return 'row';
    return null;
}
