/// <reference types='vitest' />
import angular from '@analogjs/vite-plugin-angular';
import tsconfigPaths from 'vite-tsconfig-paths';
import { defineConfig } from 'vite';

import { resolve } from 'path';

/**
 * GENERATED by tools/generate-vite-configs.mjs. Regenerate rather than hand-editing.
 *
 * Shaped after what nx g @nx/angular:library --unitTestRunner=vitest-analog produces, so migrated projects match the
 * generators and the workspace keeps ONE convention instead of a migration-specific
 * one. Deviations from that base, each with its reason:
 *
 *   environment: 'happy-dom'  carried from this project's jest.config.ts so its DOM
 *                          surface does not change (FR-007). Nx defaults to jsdom.
 *   reporters / coverage   reproduce the CI artifacts the pipeline already consumes
 *                          (FR-008). Nx emits 'default' only.
 *   deps.inline            everything importing @angular/core must resolve to one
 *                          instance; without it components fail on 'ngModule' of
 *                          null. See the generator for the measurement.
 */
export default defineConfig(() => ({
    root: __dirname,
    cacheDir: '../../../../node_modules/.vite/libs/portlets/dot-locales/portlet',
    // tsconfigPaths(), with BOTH options supplied. Nx deprecated nxViteTsPaths (removal
    // in v24) and points here, and the two are interchangeable only if this plugin is
    // told where to look: a bare tsconfigPaths() resolves nothing across projects,
    // which is what made an earlier attempt report 0 tests for edit-content.
    //
    //   root      the workspace, not the project. Vite's own root is __dirname, so
    //             without this the plugin only sees this project's tsconfig and every
    //             `@dotcms/*` sibling stays unresolved.
    //   projects  tsconfig.base.json ONLY, and that is a fix rather than a
    //             simplification: nxViteTsPaths picked the project tsconfig by a fixed
    //             preference (app, else lib, else json) and never looked at
    //             tsconfig.spec.json, so sdk-experiments' build-only paths into dist/
    //             leaked into its test run and two spec files died on
    //             "Cannot find module '@dotcms/types'". Naming the base config takes
    //             the source paths and nothing else.
    plugins: [
        angular(),
        tsconfigPaths({ root: resolve(__dirname, '../../../..'), projects: ['tsconfig.base.json'] })
    ],
    test: {
        name: 'portlets-dot-locales-portlet',
        watch: false,
        globals: true,
        // Jest routed every .css/.scss/.sass/.less import through identity-obj-proxy
        // (@nx/jest/plugins/resolver), so a CSS-module class came back as its own name.
        // Vitest's default 'stable' strategy returns _name_hash instead, and
        // sdk-react's Column test — which asserts toHaveClass('col-start-2') on a class
        // read out of a *.module.css — failed on the hash. 'non-scoped' restores the
        // Jest reading.
        //
        // 'include: []' is load-bearing, not decoration: an object under 'css' turns CSS
        // PROCESSING on, and processing a .scss file starts sass-embedded, whose dart
        // subprocess outlives the run — content-drive finished all 30 files and then
        // hung indefinitely without printing a summary. An empty include leaves every
        // file unprocessed while the module-name strategy still applies.
        css: { include: [], modules: { classNameStrategy: 'non-scoped' } },
        environment: 'happy-dom',
        environmentOptions: { happyDOM: { url: 'http://localhost/' } },
        include: ['{src,tests}/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
        setupFiles: ['src/test-setup.ts'],
        server: {
            deps: {
                inline: [
                    /[\\/](libs|apps)[\\/]/,
                    /zone\.js/,
                    /@primeuix/,
                    /@analogjs\/vite-plugin-angular/,
                    /@angular\/animations/,
                    /@angular\/cdk/,
                    /@angular\/common/,
                    /@angular\/core/,
                    /@angular\/elements/,
                    /@angular\/forms/,
                    /@angular\/platform-browser/,
                    /@angular\/platform-browser-dynamic/,
                    /@angular\/router/,
                    /@materia-ui\/ngx-monaco-editor/,
                    /@ngrx\/component-store/,
                    /@ngrx\/signals/,
                    /@openng\/spectator/,
                    /@tinymce\/tinymce-angular/,
                    /ng-mocks/,
                    /ng2-dragula/,
                    /ngx-markdown/,
                    /ngx-tiptap/,
                    /primeng/
                ]
            }
        },
        // 'github-actions' is GATED, not dropped: an explicit reporters array replaces
        // Vitest's environment-based auto-selection, so deleting the entry would take
        // the CI annotations with it — while leaving it in emitted ::error commands on
        // every local run, where nothing parses them. junit stays unconditional; CI
        // consumes those XML files (generates_test_results in .github/test-matrix.yml).
        reporters: process.env.GITHUB_ACTIONS
            ? [
                  'default',
                  'github-actions',
                  [
                      'junit',
                      {
                          outputFile:
                              '../../../../target/core-web-reports/portlets-dot-locales-portlet.xml'
                      }
                  ]
              ]
            : [
                  'default',
                  [
                      'junit',
                      {
                          outputFile:
                              '../../../../target/core-web-reports/portlets-dot-locales-portlet.xml'
                      }
                  ]
              ],
        coverage: {
            reportsDirectory: '../../../../target/core-web-reports/',
            reporter: ['html', 'lcov', 'text'],
            provider: 'v8' as const
        }
    }
}));
