#!/bin/bash
set -e
export DOTCLI_WORKDIR=$(cd $(dirname $0) && pwd)
# shellcheck source=common
. "$DOTCLI_WORKDIR/common"

cli_help() {
  cli_name=${0##*/}
  echo -e "
$cli_name
dotCMS CLI
Version: $(cat $DOTCLI_WORKDIR/VERSION)
https://github.com/dotCMS/core

Usage: `basename "$0"` [command]

${LIGHT_CYAN} Commands: ${NC}
  ${GREEN}--bundle${NC} Imports a bundle like directory into dotCMS
  ${GREEN}--content-type${NC} Imports content type described in json format into dotCMS
  ${GREEN}--site${NC} Imports a site described in json format into dotCMS
  ${GREEN}--files${NC} Imports files following the directory structure

  ${GREEN}*${NC} Help
"
  exit 1
}

cli_log "Exporting config ..."
[ ! -f "$DOTCLI_WORKDIR/config" ] \
  && echo "ERROR: No $DOTCLI_WORKDIR/config file found. " \
  && exit 1

# export so these values become available for all commands
export $(cat "$DOTCLI_WORKDIR/config" | xargs)

#if no password is provided we rely on the json web token
if [[ -z ${PASS} ]]; then
 export PASS=${JSON_WEB_TOKEN}
fi

identifiersFile=$(mktemp) || exit 1;

export identifiersFile;

case "$1" in
  --bundle|-b|-B)
    "$DOTCLI_WORKDIR/commands/push-bundle" "$2"  | tee -ia "$DOTCLI_WORKDIR/logs/bundle.log"
    ;;
  --content-type|-ct|-CT)
    "$DOTCLI_WORKDIR/commands/content-type" "$2" | tee -ia "$DOTCLI_WORKDIR/logs/content-type.log"
    ;;
  --site|-S)
    "$DOTCLI_WORKDIR/commands/site" "$2" | tee -ia "$DOTCLI_WORKDIR/logs/site.log"
    ;;
  --files|-F)
    "$DOTCLI_WORKDIR/commands/push-files" "$2" | tee -ia "$DOTCLI_WORKDIR/logs/files.log"
    ;;
  *)
    cli_help
    ;;
esac


if [[  -f ${identifiersFile} ]]; then
  rm "${identifiersFile}"
fi

unset identifiersFile