import {
    DotPaletteState,
    EditEmaPaletteStoreStatus,
    PALETTE_TYPES
} from '../store/edit-ema-palette.store';

export const CONTENT_TYPE_MOCK = [
    {
        baseType: 'CONTENT',
        clazz: 'com.dotcms.contenttype.model.type.ImmutableSimpleContentType',
        defaultType: false,
        description: 'Activities available at desitnations',
        detailPage: 'e5f131d2-1952-4596-bbbf-28fb28021b68',
        fixed: false,
        folder: 'SYSTEM_FOLDER',
        folderPath: '/',
        host: '48190c8c-42c4-46af-8d1a-0cd5db894797',
        iDate: 1567778770000,
        icon: 'paragliding',
        id: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
        layout: [
            {
                divider: {
                    clazz: 'com.dotcms.contenttype.model.field.ImmutableRowField',
                    contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                    dataType: 'SYSTEM',
                    fieldContentTypeProperties: [],
                    fieldType: 'Row',
                    fieldTypeLabel: 'Row',
                    fieldVariables: [],
                    fixed: false,
                    forceIncludeInApi: false,
                    iDate: 1567778770000,
                    id: '92660884-13cf-47d1-88aa-cae114e74f3e',
                    indexed: false,
                    listed: false,
                    modDate: 1703020623000,
                    name: 'fields-0',
                    readOnly: false,
                    required: false,
                    searchable: false,
                    sortOrder: 0,
                    unique: false,
                    variable: 'fields0'
                },
                columns: [
                    {
                        columnDivider: {
                            clazz: 'com.dotcms.contenttype.model.field.ImmutableColumnField',
                            contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                            dataType: 'SYSTEM',
                            fieldContentTypeProperties: [],
                            fieldType: 'Column',
                            fieldTypeLabel: 'Column',
                            fieldVariables: [],
                            fixed: false,
                            forceIncludeInApi: false,
                            iDate: 1567778770000,
                            id: 'a70e9c49-d33b-46dd-b44b-3e9e6669cccb',
                            indexed: false,
                            listed: false,
                            modDate: 1703020623000,
                            name: 'fields-1',
                            readOnly: false,
                            required: false,
                            searchable: false,
                            sortOrder: 1,
                            unique: false,
                            variable: 'fields1'
                        },
                        fields: [
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableHostFolderField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'SYSTEM',
                                fieldType: 'Host-Folder',
                                fieldTypeLabel: 'Site or Folder',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567778788000,
                                id: '3589acb1-a542-49d3-b794-21c1780d34fe',
                                indexed: true,
                                listed: false,
                                modDate: 1703020623000,
                                name: 'Host',
                                readOnly: false,
                                required: true,
                                searchable: false,
                                sortOrder: 2,
                                unique: false,
                                variable: 'contentHost'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableTextField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'TEXT',
                                fieldType: 'Text',
                                fieldTypeLabel: 'Text',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567778844000,
                                id: 'e1f99107-fd0e-49d4-a099-1cc10aa284d8',
                                indexed: true,
                                listed: true,
                                modDate: 1703020623000,
                                name: 'Title',
                                readOnly: false,
                                required: true,
                                searchable: true,
                                sortOrder: 3,
                                unique: false,
                                variable: 'title'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableCustomField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'LONG_TEXT',
                                fieldType: 'Custom-Field',
                                fieldTypeLabel: 'Custom Field',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567778884000,
                                id: '9ae4fc76-0d0f-4612-88d1-e178fa1a4a11',
                                indexed: true,
                                listed: false,
                                modDate: 1703020623000,
                                name: 'URL Title',
                                readOnly: false,
                                required: true,
                                searchable: false,
                                sortOrder: 4,
                                unique: true,
                                values: "#dotParse('/application/vtl/custom-fields/url-title.vtl')",
                                variable: 'urlTitle'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableTextAreaField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'LONG_TEXT',
                                fieldType: 'Textarea',
                                fieldTypeLabel: 'Textarea',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567778909000,
                                id: '806f5a87-48d5-40b3-8df8-8e1f8dbfc6ea',
                                indexed: false,
                                listed: false,
                                modDate: 1703020624000,
                                name: 'Description',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 5,
                                unique: false,
                                variable: 'description'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableTagField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'SYSTEM',
                                fieldType: 'Tag',
                                fieldTypeLabel: 'Tag',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567778923000,
                                id: 'cbca2814-9f43-42df-bc6f-8ce1a151390b',
                                indexed: true,
                                listed: false,
                                modDate: 1703020624000,
                                name: 'Tags',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 6,
                                unique: false,
                                variable: 'tags'
                            }
                        ]
                    },
                    {
                        columnDivider: {
                            clazz: 'com.dotcms.contenttype.model.field.ImmutableColumnField',
                            contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                            dataType: 'SYSTEM',
                            fieldContentTypeProperties: [],
                            fieldType: 'Column',
                            fieldTypeLabel: 'Column',
                            fieldVariables: [],
                            fixed: false,
                            forceIncludeInApi: false,
                            iDate: 1567778801000,
                            id: 'd80efc2d-d968-42f8-a15c-067c2447a20e',
                            indexed: false,
                            listed: false,
                            modDate: 1703020624000,
                            name: 'fields-2',
                            readOnly: false,
                            required: false,
                            searchable: false,
                            sortOrder: 7,
                            unique: false,
                            variable: 'fields2'
                        },
                        fields: [
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableBinaryField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'SYSTEM',
                                fieldType: 'Binary',
                                fieldTypeLabel: 'Binary',
                                fieldVariables: [
                                    {
                                        clazz: 'com.dotcms.contenttype.model.field.ImmutableFieldVariable',
                                        fieldId: 'd4a6bff9-7459-417a-ac57-8c0f9d2dc6d1',
                                        id: '50f8dfdc-08c6-44fc-bbd5-85ca5a54d9b7',
                                        key: 'accept',
                                        value: 'image/*'
                                    }
                                ],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567778809000,
                                id: 'd4a6bff9-7459-417a-ac57-8c0f9d2dc6d1',
                                indexed: false,
                                listed: false,
                                modDate: 1703020624000,
                                name: 'Image',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 8,
                                unique: false,
                                variable: 'image'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableTextField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'TEXT',
                                fieldType: 'Text',
                                fieldTypeLabel: 'Text',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567778825000,
                                id: 'e977f782-53e7-4c5c-a8ed-ba15bf1d4f45',
                                indexed: false,
                                listed: false,
                                modDate: 1703020624000,
                                name: 'Alt Tag',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 9,
                                unique: false,
                                variable: 'altTag'
                            }
                        ]
                    }
                ]
            },
            {
                divider: {
                    clazz: 'com.dotcms.contenttype.model.field.ImmutableRowField',
                    contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                    dataType: 'SYSTEM',
                    fieldContentTypeProperties: [],
                    fieldType: 'Row',
                    fieldTypeLabel: 'Row',
                    fieldVariables: [],
                    fixed: false,
                    forceIncludeInApi: false,
                    iDate: 1568315901000,
                    id: '7dad4390-3fad-498d-ae91-20aee43d5b19',
                    indexed: false,
                    listed: false,
                    modDate: 1703020624000,
                    name: 'fields-3',
                    readOnly: false,
                    required: false,
                    searchable: false,
                    sortOrder: 10,
                    unique: false,
                    variable: 'fields3'
                },
                columns: [
                    {
                        columnDivider: {
                            clazz: 'com.dotcms.contenttype.model.field.ImmutableColumnField',
                            contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                            dataType: 'SYSTEM',
                            fieldContentTypeProperties: [],
                            fieldType: 'Column',
                            fieldTypeLabel: 'Column',
                            fieldVariables: [],
                            fixed: false,
                            forceIncludeInApi: false,
                            iDate: 1568315901000,
                            id: '54699dae-f65a-477d-875e-06019a544fd4',
                            indexed: false,
                            listed: false,
                            modDate: 1703020624000,
                            name: 'fields-4',
                            readOnly: false,
                            required: false,
                            searchable: false,
                            sortOrder: 11,
                            unique: false,
                            variable: 'fields4'
                        },
                        fields: [
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableWysiwygField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'LONG_TEXT',
                                fieldType: 'WYSIWYG',
                                fieldTypeLabel: 'WYSIWYG',
                                fieldVariables: [
                                    {
                                        clazz: 'com.dotcms.contenttype.model.field.ImmutableFieldVariable',
                                        fieldId: 'b3b7d7c2-3dcd-4fca-af31-8eda00363eab',
                                        id: 'e7e6144a-e4b2-47ad-aa17-555293aaa36a',
                                        key: 'tinymceprops',
                                        value: "#set($dontShowIcon=true) #dotParse('/application/wysiwyg/wysiwyg-minimal.vtl')"
                                    }
                                ],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1568315854000,
                                id: 'b3b7d7c2-3dcd-4fca-af31-8eda00363eab',
                                indexed: false,
                                listed: false,
                                modDate: 1703020624000,
                                name: 'Body',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 12,
                                unique: false,
                                variable: 'body'
                            }
                        ]
                    }
                ]
            }
        ],
        modDate: 1703020624000,
        multilingualable: false,
        nEntries: 10,
        name: 'Activity',
        siteName: 'demo.dotcms.com',
        sortOrder: 0,
        system: false,
        systemActionMappings: [
            {
                archived: false,
                creationDate: 1703026814428,
                defaultScheme: false,
                description: '',
                entryActionId: null,
                id: 'd61a59e1-a49c-46f2-a929-db2b4bfa88b2',
                mandatory: false,
                modDate: 1703020631984,
                name: 'System Workflow',
                system: true
            }
        ],
        urlMapPattern: '/activities/{urlTitle}',
        variable: 'Activity',
        versionable: true,
        workflows: [
            {
                archived: false,
                creationDate: 1703026814428,
                defaultScheme: false,
                description: '',
                entryActionId: null,
                id: 'd61a59e1-a49c-46f2-a929-db2b4bfa88b2',
                mandatory: false,
                modDate: 1703020631984,
                name: 'System Workflow',
                system: true
            }
        ]
    }
];

export const CONTENTLETS_MOCK = [
    {
        hostName: 'demo.dotcms.com',
        modDate: '2021-04-08 13:53:32.618',
        imageMetaData: {
            modDate: 1703020595125,
            sha256: '01bed04a0807b45245d38188da3bece44e42fcdd0cf8e8bfe0585e8bd7a61913',
            length: 15613,
            title: 'box-info-2-270x270.jpg',
            version: 20220201,
            isImage: true,
            fileSize: 15613,
            name: 'box-info-2-270x270.jpg',
            width: 270,
            contentType: 'image/jpeg',
            height: 270
        },
        publishDate: '2021-04-08 13:53:32.681',
        description:
            "Snowboarding, once a prime route for teen rebellion, today is definitely mainstream. Those teens — both guys and Shred Bettys, who took up snowboarding in the late '80s and '90s now are riding with their kids.",
        title: 'Snowboarding',
        body: "<p>As with skiing, there are different styles of riding. Free-riding is all-mountain snowboarding on the slopes, in the trees, down the steeps and through the moguls. Freestyle is snowboarding in a pipe or park filled with rails, fun boxes and other features.<br /><br />Snowboarding parks are designed for specific skill levels, from beginner parks with tiny rails hugging the ground to terrain parks with roller-coaster rails, fun boxes and tabletops for more experienced snowboarders.<br /><br />Whether you're a first-timer or already comfortable going lip-to-lip in a pipe, there are classes and special clinics for you at our ski and snowboard resorts. Our resorts offer multiday clinics, so if you're headed to ski this winter, consider wrapping your vacation dates around a snowboarding clinic.</p>",
        baseType: 'CONTENT',
        inode: 'd77576ce-6e3a-4cf3-b412-8e5209f56cae',
        archived: false,
        host: '48190c8c-42c4-46af-8d1a-0cd5db894797',
        working: true,
        locked: false,
        stInode: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
        contentType: 'Activity',
        live: true,
        altTag: 'Snowboarding',
        owner: 'dotcms.org.1',
        imageVersion: '/dA/d77576ce-6e3a-4cf3-b412-8e5209f56cae/image/box-info-2-270x270.jpg',
        identifier: '574f0aec-185a-4160-9c17-6d037b298318',
        image: '/dA/574f0aec-185a-4160-9c17-6d037b298318/image/box-info-2-270x270.jpg',
        imageContentAsset: '574f0aec-185a-4160-9c17-6d037b298318/image',
        urlTitle: 'snowboarding',
        languageId: 1,
        URL_MAP_FOR_CONTENT: '/activities/snowboarding',
        url: '/content.2f6fe5b8-a2cc-4ecb-a868-db632d695fca',
        tags: 'snowboarding,winterenthusiast',
        titleImage: 'image',
        modUserName: 'Admin User',
        urlMap: '/activities/snowboarding',
        hasLiveVersion: true,
        folder: 'SYSTEM_FOLDER',
        hasTitleImage: true,
        sortOrder: 0,
        modUser: 'dotcms.org.1',
        __icon__: 'contentIcon',
        contentTypeIcon: 'paragliding',
        variant: 'DEFAULT'
    },
    {
        hostName: 'demo.dotcms.com',
        modDate: '2020-09-02 16:42:10.049',
        imageMetaData: {
            modDate: 1703020594791,
            sha256: '7e1cf9d3c8c144f592af72658456031c8283bfe4a5ecce3e188c71aa7b1e590e',
            length: 37207,
            title: 'zip-line.jpg',
            version: 20220201,
            isImage: true,
            fileSize: 37207,
            name: 'zip-line.jpg',
            width: 270,
            contentType: 'image/jpeg',
            height: 270
        },
        publishDate: '2020-09-02 16:42:10.101',
        description:
            'Ever wondered what it is like to fly through the forest canopy? Zip-lining ais the best way to explore the forest canopy, where thick branches serve as platforms for the adventurous traveler, more than 100 feet above the forest floor.',
        title: 'Zip-Lining',
        body: '<p>Ever wondered what it is a monkey finds so fascinating about the forest canopy? Costa Rica is a pioneer in canopy exploration, where thick branches serve as platforms for the adventurous traveler, more than 100 feet above the jungle floor. If you&rsquo;re wondering why you&rsquo;d want to head to the top of a tree just to look around, remember that 90% of Costa Rica animals and 50% of plant species in rainforests live in the upper levels of the trees. When you explore that far off the ground, the view is something you&rsquo;ll never forget! A Costa Rica zip line tour, hanging bridges hike, or aerial tram tour are all fantastic ways to take advantage of Costa Rica&rsquo;s stunning forest canopy views.</p>\n<p>Almost anyone of any age and physical condition can enjoy a Costa Rica zip line adventure as it is not strenuous. Secured into a harness and attached to a sturdy cable, you will have the opportunity to fly through the rainforest canopy and experience a bird&rsquo;s eye view of the lively forest below. A Costa Rica zip line is about a five hour adventure that operates rain or shine all year and is led by bilingual guides. For the non-adrenaline junkie, the aerial tram can take you through the rainforest in comfort and safety. Prefer to linger? Hanging bridges offer panoramic views for acres, and an experienced guide will be happy to point out a variety of birds and animals.</p>',
        baseType: 'CONTENT',
        inode: '8df9a375-0386-401c-b5d6-da21c1c5c301',
        archived: false,
        host: '48190c8c-42c4-46af-8d1a-0cd5db894797',
        working: true,
        locked: false,
        stInode: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
        contentType: 'Activity',
        live: true,
        altTag: 'Zip-line',
        owner: 'dotcms.org.1',
        imageVersion: '/dA/8df9a375-0386-401c-b5d6-da21c1c5c301/image/zip-line.jpg',
        identifier: '50757fb4-75df-4e2c-8335-35d36bdb944b',
        image: '/dA/50757fb4-75df-4e2c-8335-35d36bdb944b/image/zip-line.jpg',
        imageContentAsset: '50757fb4-75df-4e2c-8335-35d36bdb944b/image',
        urlTitle: 'zip-lining',
        languageId: 1,
        URL_MAP_FOR_CONTENT: '/activities/zip-lining',
        url: '/content.c17f9c4c-ad14-4777-ae61-334ee6c9fcbf',
        tags: 'ecoenthusiast,zip-lining',
        titleImage: 'image',
        modUserName: 'Admin User',
        urlMap: '/activities/zip-lining',
        hasLiveVersion: true,
        folder: 'SYSTEM_FOLDER',
        hasTitleImage: true,
        sortOrder: 0,
        modUser: 'dotcms.org.1',
        __icon__: 'contentIcon',
        contentTypeIcon: 'paragliding',
        variant: 'DEFAULT'
    },
    {
        hostName: 'demo.dotcms.com',
        modDate: '2020-09-02 16:42:10.543',
        imageMetaData: {
            modDate: 1703020594610,
            sha256: '2719112e3d36c3e229e6f8a78d07a2612b6d863d7a8d3382c20fb81c29e3d10e',
            length: 27870,
            title: 'hiking.jpg',
            version: 20220201,
            isImage: true,
            fileSize: 27870,
            name: 'hiking.jpg',
            width: 270,
            contentType: 'image/jpeg',
            height: 270
        },
        publishDate: '2020-09-02 16:42:10.587',
        description:
            'Guided hiking tours where our guides use their training as naturalists to point out animals, unique plants and nature itself.',
        title: 'Hiking',
        body: '<p>Everywhere we look, we are greeted with peaceful waterfalls, tropical rainforests and stretches of ocean surf. These are the perfect conditions for zip lining, rafting, canyoning, cycling and hiking. A leader in wildlife and sustainability initiatives, Costa Rica is rich with interesting creatures. Our guides use their training as naturalists to point out white-faced capuchins, howler monkeys and maybe even a sloth camouflaged in a tree.<br /><br />Our journey begins at Arenal Volcano National Park, where we spend three days hiking volcanoes, canyoning deep in the tropical rainforest and zip lining high above the jungle canopy. Get a glimpse of the majestic Arenal volcano and then soak up natural thermal hot springs with fellow adventurers after the day&rsquo;s explorations. Take in the wild and beautiful Rio Pacuare for two days of heart-pounding whitewater rafting. Spend our final day cycling through the quaint towns and fertile slopes of the Turrialba region.</p>',
        baseType: 'CONTENT',
        inode: '64ddfdd1-c155-402e-b670-576fed17d722',
        archived: false,
        host: '48190c8c-42c4-46af-8d1a-0cd5db894797',
        working: true,
        locked: false,
        stInode: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
        contentType: 'Activity',
        live: true,
        altTag: 'Hiking in Costa Rica',
        owner: 'dotcms.org.1',
        imageVersion: '/dA/64ddfdd1-c155-402e-b670-576fed17d722/image/hiking.jpg',
        identifier: '6bbead53-3908-471c-966d-9e76c5dd9eba',
        image: '/dA/6bbead53-3908-471c-966d-9e76c5dd9eba/image/hiking.jpg',
        imageContentAsset: '6bbead53-3908-471c-966d-9e76c5dd9eba/image',
        urlTitle: 'hiking',
        languageId: 1,
        URL_MAP_FOR_CONTENT: '/activities/hiking',
        url: '/content.fbf02abe-ec2d-4a21-a42f-12c4b0707f71',
        tags: 'ecoenthusiast,hiking',
        titleImage: 'image',
        modUserName: 'Admin User',
        urlMap: '/activities/hiking',
        hasLiveVersion: true,
        folder: 'SYSTEM_FOLDER',
        hasTitleImage: true,
        sortOrder: 0,
        modUser: 'dotcms.org.1',
        __icon__: 'contentIcon',
        contentTypeIcon: 'paragliding',
        variant: 'DEFAULT'
    },
    {
        hostName: 'demo.dotcms.com',
        modDate: '2020-09-02 16:42:09.56',
        imageMetaData: {
            modDate: 1703020594947,
            sha256: '041e8f2a721bf85fc833db50666a892ca9c5fcf816091cb6b6123a08ca701085',
            length: 33386,
            title: 'diving.jpg',
            version: 20220201,
            isImage: true,
            fileSize: 33386,
            name: 'diving.jpg',
            width: 270,
            contentType: 'image/jpeg',
            height: 270
        },
        publishDate: '2020-09-02 16:42:09.608',
        description:
            'World-class diving is at your doorstep. From shore or by boat, you have exclusive access to miles of pristine reefs, where diverse and dramatic undersea landscapes harbor the highest level of marine biodiversity on the planet.',
        title: 'Diving',
        body: '<p>Our dive destinations where created to deliver the ultimate dive experience and was established following an extensive search to identify the perfect location for a dive resort in terms of geography, climate, oceanic topography and marine biodiversity. Having identified the premier location, we developed resorts that, despite its remote position, offers a plenitude of facilities and comforts to make a dive trip, and all that surrounds it, an experience that you will cherish.</p>\n<p><strong>Scuba</strong><br />Unlimited diving on pristine, protected coral reefs for all divers be they open-circuit, technical or rebreather.</p>\n<p><strong>Snorkeling</strong><br />Ideal place for snorkelers. The house reef and many dive sites have beautiful shallows on the coral tops.</p>\n<p><strong>Private Dive/Snorkel Guides</strong><br />Let us fulfill your innermost wishes and tailor an exclusive, personalised diving experience to fit your individual needs and desires.</p>\n<p><strong>Underwater photography</strong><br />The photo opportunities here are stupendous and we offer support and equipment of a level that satisfies the many pros who visit us.</p>',
        baseType: 'CONTENT',
        inode: 'b77151f2-7206-4b03-862d-68217432d54d',
        archived: false,
        host: '48190c8c-42c4-46af-8d1a-0cd5db894797',
        working: true,
        locked: false,
        stInode: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
        contentType: 'Activity',
        live: true,
        owner: 'dotcms.org.1',
        imageVersion: '/dA/b77151f2-7206-4b03-862d-68217432d54d/image/diving.jpg',
        identifier: '4694d40b-d9be-4e09-b031-64ee3e7c9642',
        image: '/dA/4694d40b-d9be-4e09-b031-64ee3e7c9642/image/diving.jpg',
        imageContentAsset: '4694d40b-d9be-4e09-b031-64ee3e7c9642/image',
        urlTitle: 'diving',
        languageId: 1,
        URL_MAP_FOR_CONTENT: '/activities/diving',
        url: '/content.e9332c43-dfc2-4aa1-b0d6-60ca3df7cb76',
        tags: 'snorkeling,waterenthusiast,diving,scuba',
        titleImage: 'image',
        modUserName: 'Admin User',
        urlMap: '/activities/diving',
        hasLiveVersion: true,
        folder: 'SYSTEM_FOLDER',
        hasTitleImage: true,
        sortOrder: 0,
        modUser: 'dotcms.org.1',
        __icon__: 'contentIcon',
        contentTypeIcon: 'paragliding',
        variant: 'DEFAULT'
    },
    {
        hostName: 'demo.dotcms.com',
        modDate: '2020-09-02 16:42:09.068',
        imageMetaData: {
            modDate: 1703020594347,
            sha256: '028e5fa94f67eecdac5616925246dfd713c8ddbe710fc1a6349512f1c59f378d',
            length: 14358,
            title: 'box-info-1-270x270.jpg',
            version: 20220201,
            isImage: true,
            fileSize: 14358,
            name: 'box-info-1-270x270.jpg',
            width: 270,
            contentType: 'image/jpeg',
            height: 270
        },
        publishDate: '2020-09-02 16:42:09.116',
        description:
            "Skiing is the best family sport because it's so much more than a sport: it's a medium of shared experiences in a living, breathing culture of connection.",
        title: 'Skiing',
        body: "<p>Admiring the dramatic mountain landscape from atop the ski lift, feeling the cold air nipping at your cheeks, experiencing the rush of adrenaline as you carve the snow &ndash; there's nothing quite like a day on the slopes. And while the mountain conditions are top priority, our ski vacation spots also boast charming towns and lively apr&egrave;s-ski scenes to explore. Factors like resort variety, scenic beauty, annual snowfall and overall atmosphere, we have the world's best places to ski. Wondering where to go? Take a peek at the destinations, and don't forget to vote for your favorites.</p>",
        baseType: 'CONTENT',
        inode: '278aa6dc-57cd-4cf6-ac18-df48c2430cb1',
        archived: false,
        host: '48190c8c-42c4-46af-8d1a-0cd5db894797',
        working: true,
        locked: false,
        stInode: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
        contentType: 'Activity',
        live: true,
        altTag: 'Skiing',
        owner: 'dotcms.org.1',
        imageVersion: '/dA/278aa6dc-57cd-4cf6-ac18-df48c2430cb1/image/box-info-1-270x270.jpg',
        identifier: '6a8102b5-fdb0-4ad5-9a5d-e982bcdb54c8',
        image: '/dA/6a8102b5-fdb0-4ad5-9a5d-e982bcdb54c8/image/box-info-1-270x270.jpg',
        imageContentAsset: '6a8102b5-fdb0-4ad5-9a5d-e982bcdb54c8/image',
        urlTitle: 'skiing',
        languageId: 1,
        URL_MAP_FOR_CONTENT: '/activities/skiing',
        url: '/content.97dded8a-f260-4730-aa99-56c9ea01c16d',
        tags: 'skiing,winterenthusiast',
        titleImage: 'image',
        modUserName: 'Admin User',
        urlMap: '/activities/skiing',
        hasLiveVersion: true,
        folder: 'SYSTEM_FOLDER',
        hasTitleImage: true,
        sortOrder: 0,
        modUser: 'dotcms.org.1',
        __icon__: 'contentIcon',
        contentTypeIcon: 'paragliding',
        variant: 'DEFAULT'
    },
    {
        hostName: 'demo.dotcms.com',
        modDate: '2020-09-02 16:42:08.089',
        imageMetaData: {
            modDate: 1703020594454,
            sha256: '07b3d78da174c14744c865ac82e34cdada87f846f8e48cf55f9cc6731da0dc1b',
            length: 18643,
            title: 'surfing.jpg',
            version: 20220201,
            isImage: true,
            fileSize: 18643,
            name: 'surfing.jpg',
            width: 270,
            contentType: 'image/jpeg',
            height: 270
        },
        publishDate: '2020-09-02 16:42:08.14',
        description:
            'The search for the perfect wave is never-ending, but the journey itself is incredibly fulfilling. Visit one of our surf resorts and get one step closer to finding nirvana.',
        title: 'Surfing',
        body: '<p>Is your surfboard always leaning against the wall next to the door, waiting to be grabbed on the run? Do you organize your whole week around those hours spent outdoors doing what you love most? Are you happy when there&rsquo;s an offshore wind and do you feel irritated when wind conditions are not quite right? Well, my friend, I&rsquo;m afraid that you may already be addicted to surfing.<br /><br />Regardless of your level, whether you&rsquo;re into big wave surfing or still a kook, there&rsquo;s no denying that surfing gives you quite the adrenaline rush. But it&rsquo;s not necessarily the danger that gets you hooked, there are a bunch of other factors that contribute to the natural high: the setting, the anticipation, the rewards, all result in a surge of feel-good chemicals &ndash; endorphins, dopamine, and serotonin.</p>',
        baseType: 'CONTENT',
        inode: '3bf914e1-1f42-4ee1-8264-9e7b807af712',
        archived: false,
        host: '48190c8c-42c4-46af-8d1a-0cd5db894797',
        working: true,
        locked: false,
        stInode: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
        contentType: 'Activity',
        live: true,
        altTag: 'Surfing Vactions',
        owner: 'dotcms.org.1',
        imageVersion: '/dA/3bf914e1-1f42-4ee1-8264-9e7b807af712/image/surfing.jpg',
        identifier: '8ccfa397-4369-44bb-b450-33151387eb02',
        image: '/dA/8ccfa397-4369-44bb-b450-33151387eb02/image/surfing.jpg',
        imageContentAsset: '8ccfa397-4369-44bb-b450-33151387eb02/image',
        urlTitle: 'surfing',
        languageId: 1,
        URL_MAP_FOR_CONTENT: '/activities/surfing',
        url: '/content.6def68a6-67f4-4f56-b8fc-118b3daab841',
        tags: 'surfing,waterenthusiast',
        titleImage: 'image',
        modUserName: 'Admin User',
        urlMap: '/activities/surfing',
        hasLiveVersion: true,
        folder: 'SYSTEM_FOLDER',
        hasTitleImage: true,
        sortOrder: 0,
        modUser: 'dotcms.org.1',
        __icon__: 'contentIcon',
        contentTypeIcon: 'paragliding',
        variant: 'DEFAULT'
    },
    {
        hostName: 'demo.dotcms.com',
        modDate: '2020-09-02 16:42:08.581',
        imageMetaData: {
            modDate: 1703020595001,
            sha256: '4cfeea66800ea90921d311c342ce98223786fa5eb31dc04871bcfe8dc4515800',
            length: 21426,
            title: 'box-info-3-270x270.jpg',
            version: 20220201,
            isImage: true,
            fileSize: 21426,
            name: 'box-info-3-270x270.jpg',
            width: 270,
            contentType: 'image/jpeg',
            height: 270
        },
        publishDate: '2020-09-02 16:42:08.624',
        description:
            'All winter locations have a variety of snowmobiles available for rent to all our registered guests.',
        title: 'Snowmobiling',
        body: '<p>Experience the rush of snowmobiling through spectacular terrain. With thousands of miles of groomed and ungroomed trails to choose from, you&rsquo;ll never run out of new places to ride. When you&rsquo;ve had your fill of thrills in the unmatched scenery, head back to town and warm up with hot cocoa&mdash;or a local brew&mdash;by a crackling fire.</p>\n<p>Discover the scenic backwoods with our experienced guides! Use one of our machines or bring you own!<br /><br />A full service vacation that includes all meals, lodging, amenities, and guide service to 1500+ miles of groomed, secondary, and mountain snowmobile trails from your cabin door. There is also ample opportunity for you to enjoy &ldquo;off trail &rdquo; play areas. Guests enjoy our hideaway location - with lots of places to snowmobile, awesome scenery, abundant wildlife, and no crowds. From our ranch you can access over 600 miles of groomed trails - with another1000 miles of secondary trails - and lots of off-trail play areas.<br /><br />You could easily spend a week here and ride different country every day. Annual snowfall ranges from 140&rdquo; at the ranch and up to 500&rdquo; in the surrounding mountains!</p>',
        baseType: 'CONTENT',
        inode: 'bec05965-653e-4148-a59c-ac9682d91e54',
        archived: false,
        host: '48190c8c-42c4-46af-8d1a-0cd5db894797',
        working: true,
        locked: false,
        stInode: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
        contentType: 'Activity',
        live: true,
        altTag: 'Snowmobiling',
        owner: 'dotcms.org.1',
        imageVersion: '/dA/bec05965-653e-4148-a59c-ac9682d91e54/image/box-info-3-270x270.jpg',
        identifier: '6ac5921e-e062-49a6-9808-f41aff9343c5',
        image: '/dA/6ac5921e-e062-49a6-9808-f41aff9343c5/image/box-info-3-270x270.jpg',
        imageContentAsset: '6ac5921e-e062-49a6-9808-f41aff9343c5/image',
        urlTitle: 'snowmobiling',
        languageId: 1,
        URL_MAP_FOR_CONTENT: '/activities/snowmobiling',
        url: '/content.3614c9b2-f329-4d94-9c8e-143d5b254870',
        tags: 'snowmobile,winterenthusiast',
        titleImage: 'image',
        modUserName: 'Admin User',
        urlMap: '/activities/snowmobiling',
        hasLiveVersion: true,
        folder: 'SYSTEM_FOLDER',
        hasTitleImage: true,
        sortOrder: 0,
        modUser: 'dotcms.org.1',
        __icon__: 'contentIcon',
        contentTypeIcon: 'paragliding',
        variant: 'DEFAULT'
    },
    {
        hostName: 'demo.dotcms.com',
        modDate: '2020-09-02 16:42:07.114',
        imageMetaData: {
            modDate: 1703020594918,
            sha256: 'd87e67d27c4f1b431d44ef5fdcadc2b1f816d55e60796bba0ae0dd9b90cfe02c',
            length: 22168,
            title: 'costa-rica-fishing.jpg',
            version: 20220201,
            isImage: true,
            fileSize: 22168,
            name: 'costa-rica-fishing.jpg',
            width: 270,
            contentType: 'image/jpeg',
            height: 270
        },
        publishDate: '2020-09-02 16:42:07.161',
        description:
            'Do you know exactly which fish you are trying to catch? If not, you can learn about all the different types of fish you can catch in Costa Rica. Plus we let you know where the best places to catch them.',
        title: 'Sport Fishing',
        body: '<p>Encompassing an area as vast as the European continent, French Polynesia is a playground for amateur sport fishermen. French Polynesian fishermen head out armed only with a fishing pole and a harness to the great blue where they confront species known for their fighting qualities: tuna, swordfish and of course the Marlin (Haura,in Tahitian). The largest of the catch can weigh over 500 kilos!</p>\n<p>The fact that Polynesian waters harbor so many of these giants, draws in many sport fishermen. At the end of March, the 11th Tahitian Billfish Tournament will bring together over 60 fishing boats and expects to attract many foreign crews. During the four-day tournament, the boats will search out these huge fish along the coasts of Tahiti for a truly adrenalin charged experience.</p>',
        baseType: 'CONTENT',
        inode: 'aeb77b14-02ab-42ec-aea6-499c8e0bcba1',
        archived: false,
        host: '48190c8c-42c4-46af-8d1a-0cd5db894797',
        working: true,
        locked: false,
        stInode: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
        contentType: 'Activity',
        live: true,
        altTag: 'Costa Rica boasts some of the best sportfishing',
        owner: 'dotcms.org.1',
        imageVersion: '/dA/aeb77b14-02ab-42ec-aea6-499c8e0bcba1/image/costa-rica-fishing.jpg',
        identifier: '50351143-3ba6-4c54-9e9b-0d8a90d2f9b0',
        image: '/dA/50351143-3ba6-4c54-9e9b-0d8a90d2f9b0/image/costa-rica-fishing.jpg',
        imageContentAsset: '50351143-3ba6-4c54-9e9b-0d8a90d2f9b0/image',
        urlTitle: 'sport-fishing',
        languageId: 1,
        URL_MAP_FOR_CONTENT: '/activities/sport-fishing',
        url: '/content.b1dcbe8a-d81f-405e-a176-4aa4a6a0b0a3',
        tags: 'sport fishing,fishing',
        titleImage: 'image',
        modUserName: 'Admin User',
        urlMap: '/activities/sport-fishing',
        hasLiveVersion: true,
        folder: 'SYSTEM_FOLDER',
        hasTitleImage: true,
        sortOrder: 0,
        modUser: 'dotcms.org.1',
        __icon__: 'contentIcon',
        contentTypeIcon: 'paragliding',
        variant: 'DEFAULT'
    },
    {
        hostName: 'demo.dotcms.com',
        modDate: '2020-09-02 16:42:06.137',
        imageMetaData: {
            modDate: 1703020594658,
            sha256: '729049464994cc3b93b27f9478e907107e7407a14544c619d6efa90dd19a16f3',
            length: 24219,
            title: 'white-water-raft-2.jpg',
            version: 20220201,
            isImage: true,
            fileSize: 24219,
            name: 'white-water-raft-2.jpg',
            width: 270,
            contentType: 'image/jpeg',
            height: 270
        },
        publishDate: '2020-09-02 16:42:06.184',
        description:
            'For those looking for a thrill, we offer some of the worlds bets white water rafting. Class II - IV rivers.',
        title: 'White Water Rafting',
        body: '<p>Between the year-round warm water and the natural beauty the country has to offer, a trip to Costa Rica presents the opportunity for world-class rafting in a tropical paradise. Costa Rica has 14 major river systems that begin in the volcanic mountain ranges and flow out towards the Caribbean Sea, the Pacific Ocean, the San Juan River, or Lake Nicaragua &mdash; with plenty of waterfalls along the way. These rivers produce world-famous white-water rapids, as well as beautiful scenery along the banks.<br /><br /><strong>Choose Your White Water Rafting Adventure.</strong><br />We have a wide range of options when it comes to rafting adventures, with both single day tours and multi-day white water excursions available, and river difficulties varying from the calm stroll of Class I rivers to the extreme thrill of Class V rivers. So, whether you&rsquo;d like to take an easy float down the river to spot wildlife with the whole family, or you&rsquo;re interested in challenging yourself on adrenaline-packed rapids with nicknames such as &ldquo;La Boca del Diablo,&rdquo; there&rsquo;s a whitewater rafting trip for you.</p>',
        baseType: 'CONTENT',
        inode: '72736205-e217-4f69-a28c-4e3496512d73',
        archived: false,
        host: '48190c8c-42c4-46af-8d1a-0cd5db894797',
        working: true,
        locked: false,
        stInode: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
        contentType: 'Activity',
        live: true,
        altTag: 'White Water Rafting in Tropical Rain Forests',
        owner: 'dotcms.org.1',
        imageVersion: '/dA/72736205-e217-4f69-a28c-4e3496512d73/image/white-water-raft-2.jpg',
        identifier: '0e9340f8-08d2-46e3-ae25-be0137c575d0',
        image: '/dA/0e9340f8-08d2-46e3-ae25-be0137c575d0/image/white-water-raft-2.jpg',
        imageContentAsset: '0e9340f8-08d2-46e3-ae25-be0137c575d0/image',
        urlTitle: 'white-water-rafting',
        languageId: 1,
        URL_MAP_FOR_CONTENT: '/activities/white-water-rafting',
        url: '/content.a5f36908-8c57-46c0-9ee5-c37e065087d9',
        tags: 'white water rafting,ecoenthusiast',
        titleImage: 'image',
        modUserName: 'Admin User',
        urlMap: '/activities/white-water-rafting',
        hasLiveVersion: true,
        folder: 'SYSTEM_FOLDER',
        hasTitleImage: true,
        sortOrder: 0,
        modUser: 'dotcms.org.1',
        __icon__: 'contentIcon',
        contentTypeIcon: 'paragliding',
        variant: 'DEFAULT'
    },
    {
        hostName: 'demo.dotcms.com',
        modDate: '2020-09-02 16:42:06.624',
        imageMetaData: {
            modDate: 1703020594641,
            sha256: '77c2ab67803b4013f07f724000019c8034fda97c010ba53ddcc9d91adca9ad59',
            length: 43692,
            title: 'nordic-skiing.jpg',
            version: 20220201,
            isImage: true,
            fileSize: 43692,
            name: 'nordic-skiing.jpg',
            width: 270,
            contentType: 'image/jpeg',
            height: 270
        },
        publishDate: '2020-09-02 16:42:06.672',
        description:
            'Visit a cross-country ski center with groomed trails, rent some gear, and try it out. These carved tracks eliminate 90 percent of your worries about sailing off into the woods because they keep your skis pointed forward.',
        title: 'Cross-country Skiing',
        body: '<p>Cross country, or Nordic skiing, can be a lot like walking on skis, but proficient skiers stride and glide with ease and speed. Only the Nordic skier\'s toe is attached to the ski, permitting that striding glide that carries you "cross country." Flat terrain is best for novices, and there\'s plenty of that at our resort areas.<br /><br />Nordic skiers usually use a "step turn," like ice skaters, but with the classic telemark turn, advanced skiers tackle the winding trails, downhill ski slopes, even isolated backcountry areas drifted deep with snow.</p>',
        baseType: 'CONTENT',
        inode: '6c81e3b5-b776-4bb5-bf81-82898159adb3',
        archived: false,
        host: '48190c8c-42c4-46af-8d1a-0cd5db894797',
        working: true,
        locked: false,
        stInode: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
        contentType: 'Activity',
        live: true,
        altTag: 'Nordic Skiing',
        owner: 'dotcms.org.1',
        imageVersion: '/dA/6c81e3b5-b776-4bb5-bf81-82898159adb3/image/nordic-skiing.jpg',
        identifier: 'af5d2a9d-86ed-421d-a9e6-5e5dae0e484a',
        image: '/dA/af5d2a9d-86ed-421d-a9e6-5e5dae0e484a/image/nordic-skiing.jpg',
        imageContentAsset: 'af5d2a9d-86ed-421d-a9e6-5e5dae0e484a/image',
        urlTitle: 'nordic-skiing',
        languageId: 1,
        URL_MAP_FOR_CONTENT: '/activities/nordic-skiing',
        url: '/content.796de41e-3fb9-4192-8b21-71baf72b8922',
        tags: 'nordic,cross-country skiing,skiing,winterenthusiast',
        titleImage: 'image',
        modUserName: 'Admin User',
        urlMap: '/activities/nordic-skiing',
        hasLiveVersion: true,
        folder: 'SYSTEM_FOLDER',
        hasTitleImage: true,
        sortOrder: 0,
        modUser: 'dotcms.org.1',
        __icon__: 'contentIcon',
        contentTypeIcon: 'paragliding',
        variant: 'DEFAULT'
    }
];

export const INITIAL_STATE_PALETTE_CONTENTTYPE_MOCK: DotPaletteState = {
    contentlets: {
        filter: {
            query: '',
            contentTypeVarName: ''
        },
        items: [],
        totalRecords: 0,
        itemsPerPage: 10
    },
    contenttypes: {
        items: [],
        filter: ''
    },
    status: EditEmaPaletteStoreStatus.LOADED,
    currentPaletteType: PALETTE_TYPES.CONTENTTYPE,
    allowedTypes: []
};

export const INITIAL_STATE_PALETTE_CONTENTLET_MOCK: DotPaletteState = {
    contentlets: {
        filter: {
            query: '',
            contentTypeVarName: 'Test'
        },
        items: CONTENTLETS_MOCK,
        totalRecords: CONTENTLETS_MOCK.length,
        itemsPerPage: 10
    },
    contenttypes: {
        items: [],
        filter: ''
    },
    status: EditEmaPaletteStoreStatus.LOADED,
    currentPaletteType: PALETTE_TYPES.CONTENTLET,
    allowedTypes: []
};
