import {
    DotPaletteState,
    EditEmaPaletteStoreStatus,
    PALETTE_TYPES
} from '../store/edit-ema-palette.store';

export const CONTENT_TYPE_MOCK = [
    {
        baseType: 'CONTENT',
        clazz: 'com.dotcms.contenttype.model.type.ImmutableSimpleContentType',
        defaultType: false,
        description: 'Activities available at desitnations',
        detailPage: 'e5f131d2-1952-4596-bbbf-28fb28021b68',
        fixed: false,
        folder: 'SYSTEM_FOLDER',
        folderPath: '/',
        host: '48190c8c-42c4-46af-8d1a-0cd5db894797',
        iDate: 1567778770000,
        icon: 'paragliding',
        id: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
        layout: [
            {
                divider: {
                    clazz: 'com.dotcms.contenttype.model.field.ImmutableRowField',
                    contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                    dataType: 'SYSTEM',
                    fieldContentTypeProperties: [],
                    fieldType: 'Row',
                    fieldTypeLabel: 'Row',
                    fieldVariables: [],
                    fixed: false,
                    forceIncludeInApi: false,
                    iDate: 1567778770000,
                    id: '92660884-13cf-47d1-88aa-cae114e74f3e',
                    indexed: false,
                    listed: false,
                    modDate: 1703020623000,
                    name: 'fields-0',
                    readOnly: false,
                    required: false,
                    searchable: false,
                    sortOrder: 0,
                    unique: false,
                    variable: 'fields0'
                },
                columns: [
                    {
                        columnDivider: {
                            clazz: 'com.dotcms.contenttype.model.field.ImmutableColumnField',
                            contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                            dataType: 'SYSTEM',
                            fieldContentTypeProperties: [],
                            fieldType: 'Column',
                            fieldTypeLabel: 'Column',
                            fieldVariables: [],
                            fixed: false,
                            forceIncludeInApi: false,
                            iDate: 1567778770000,
                            id: 'a70e9c49-d33b-46dd-b44b-3e9e6669cccb',
                            indexed: false,
                            listed: false,
                            modDate: 1703020623000,
                            name: 'fields-1',
                            readOnly: false,
                            required: false,
                            searchable: false,
                            sortOrder: 1,
                            unique: false,
                            variable: 'fields1'
                        },
                        fields: [
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableHostFolderField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'SYSTEM',
                                fieldType: 'Host-Folder',
                                fieldTypeLabel: 'Site or Folder',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567778788000,
                                id: '3589acb1-a542-49d3-b794-21c1780d34fe',
                                indexed: true,
                                listed: false,
                                modDate: 1703020623000,
                                name: 'Host',
                                readOnly: false,
                                required: true,
                                searchable: false,
                                sortOrder: 2,
                                unique: false,
                                variable: 'contentHost'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableTextField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'TEXT',
                                fieldType: 'Text',
                                fieldTypeLabel: 'Text',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567778844000,
                                id: 'e1f99107-fd0e-49d4-a099-1cc10aa284d8',
                                indexed: true,
                                listed: true,
                                modDate: 1703020623000,
                                name: 'Title',
                                readOnly: false,
                                required: true,
                                searchable: true,
                                sortOrder: 3,
                                unique: false,
                                variable: 'title'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableCustomField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'LONG_TEXT',
                                fieldType: 'Custom-Field',
                                fieldTypeLabel: 'Custom Field',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567778884000,
                                id: '9ae4fc76-0d0f-4612-88d1-e178fa1a4a11',
                                indexed: true,
                                listed: false,
                                modDate: 1703020623000,
                                name: 'URL Title',
                                readOnly: false,
                                required: true,
                                searchable: false,
                                sortOrder: 4,
                                unique: true,
                                values: "#dotParse('/application/vtl/custom-fields/url-title.vtl')",
                                variable: 'urlTitle'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableTextAreaField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'LONG_TEXT',
                                fieldType: 'Textarea',
                                fieldTypeLabel: 'Textarea',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567778909000,
                                id: '806f5a87-48d5-40b3-8df8-8e1f8dbfc6ea',
                                indexed: false,
                                listed: false,
                                modDate: 1703020624000,
                                name: 'Description',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 5,
                                unique: false,
                                variable: 'description'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableTagField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'SYSTEM',
                                fieldType: 'Tag',
                                fieldTypeLabel: 'Tag',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567778923000,
                                id: 'cbca2814-9f43-42df-bc6f-8ce1a151390b',
                                indexed: true,
                                listed: false,
                                modDate: 1703020624000,
                                name: 'Tags',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 6,
                                unique: false,
                                variable: 'tags'
                            }
                        ]
                    },
                    {
                        columnDivider: {
                            clazz: 'com.dotcms.contenttype.model.field.ImmutableColumnField',
                            contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                            dataType: 'SYSTEM',
                            fieldContentTypeProperties: [],
                            fieldType: 'Column',
                            fieldTypeLabel: 'Column',
                            fieldVariables: [],
                            fixed: false,
                            forceIncludeInApi: false,
                            iDate: 1567778801000,
                            id: 'd80efc2d-d968-42f8-a15c-067c2447a20e',
                            indexed: false,
                            listed: false,
                            modDate: 1703020624000,
                            name: 'fields-2',
                            readOnly: false,
                            required: false,
                            searchable: false,
                            sortOrder: 7,
                            unique: false,
                            variable: 'fields2'
                        },
                        fields: [
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableBinaryField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'SYSTEM',
                                fieldType: 'Binary',
                                fieldTypeLabel: 'Binary',
                                fieldVariables: [
                                    {
                                        clazz: 'com.dotcms.contenttype.model.field.ImmutableFieldVariable',
                                        fieldId: 'd4a6bff9-7459-417a-ac57-8c0f9d2dc6d1',
                                        id: '50f8dfdc-08c6-44fc-bbd5-85ca5a54d9b7',
                                        key: 'accept',
                                        value: 'image/*'
                                    }
                                ],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567778809000,
                                id: 'd4a6bff9-7459-417a-ac57-8c0f9d2dc6d1',
                                indexed: false,
                                listed: false,
                                modDate: 1703020624000,
                                name: 'Image',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 8,
                                unique: false,
                                variable: 'image'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableTextField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'TEXT',
                                fieldType: 'Text',
                                fieldTypeLabel: 'Text',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567778825000,
                                id: 'e977f782-53e7-4c5c-a8ed-ba15bf1d4f45',
                                indexed: false,
                                listed: false,
                                modDate: 1703020624000,
                                name: 'Alt Tag',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 9,
                                unique: false,
                                variable: 'altTag'
                            }
                        ]
                    }
                ]
            },
            {
                divider: {
                    clazz: 'com.dotcms.contenttype.model.field.ImmutableRowField',
                    contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                    dataType: 'SYSTEM',
                    fieldContentTypeProperties: [],
                    fieldType: 'Row',
                    fieldTypeLabel: 'Row',
                    fieldVariables: [],
                    fixed: false,
                    forceIncludeInApi: false,
                    iDate: 1568315901000,
                    id: '7dad4390-3fad-498d-ae91-20aee43d5b19',
                    indexed: false,
                    listed: false,
                    modDate: 1703020624000,
                    name: 'fields-3',
                    readOnly: false,
                    required: false,
                    searchable: false,
                    sortOrder: 10,
                    unique: false,
                    variable: 'fields3'
                },
                columns: [
                    {
                        columnDivider: {
                            clazz: 'com.dotcms.contenttype.model.field.ImmutableColumnField',
                            contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                            dataType: 'SYSTEM',
                            fieldContentTypeProperties: [],
                            fieldType: 'Column',
                            fieldTypeLabel: 'Column',
                            fieldVariables: [],
                            fixed: false,
                            forceIncludeInApi: false,
                            iDate: 1568315901000,
                            id: '54699dae-f65a-477d-875e-06019a544fd4',
                            indexed: false,
                            listed: false,
                            modDate: 1703020624000,
                            name: 'fields-4',
                            readOnly: false,
                            required: false,
                            searchable: false,
                            sortOrder: 11,
                            unique: false,
                            variable: 'fields4'
                        },
                        fields: [
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableWysiwygField',
                                contentTypeId: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
                                dataType: 'LONG_TEXT',
                                fieldType: 'WYSIWYG',
                                fieldTypeLabel: 'WYSIWYG',
                                fieldVariables: [
                                    {
                                        clazz: 'com.dotcms.contenttype.model.field.ImmutableFieldVariable',
                                        fieldId: 'b3b7d7c2-3dcd-4fca-af31-8eda00363eab',
                                        id: 'e7e6144a-e4b2-47ad-aa17-555293aaa36a',
                                        key: 'tinymceprops',
                                        value: "#set($dontShowIcon=true) #dotParse('/application/wysiwyg/wysiwyg-minimal.vtl')"
                                    }
                                ],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1568315854000,
                                id: 'b3b7d7c2-3dcd-4fca-af31-8eda00363eab',
                                indexed: false,
                                listed: false,
                                modDate: 1703020624000,
                                name: 'Body',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 12,
                                unique: false,
                                variable: 'body'
                            }
                        ]
                    }
                ]
            }
        ],
        modDate: 1703020624000,
        multilingualable: false,
        nEntries: 10,
        name: 'Activity',
        siteName: 'demo.dotcms.com',
        sortOrder: 0,
        system: false,
        systemActionMappings: [
            {
                archived: false,
                creationDate: 1703026814428,
                defaultScheme: false,
                description: '',
                entryActionId: null,
                id: 'd61a59e1-a49c-46f2-a929-db2b4bfa88b2',
                mandatory: false,
                modDate: 1703020631984,
                name: 'System Workflow',
                system: true
            }
        ],
        urlMapPattern: '/activities/{urlTitle}',
        variable: 'Activity',
        versionable: true,
        workflows: [
            {
                archived: false,
                creationDate: 1703026814428,
                defaultScheme: false,
                description: '',
                entryActionId: null,
                id: 'd61a59e1-a49c-46f2-a929-db2b4bfa88b2',
                mandatory: false,
                modDate: 1703020631984,
                name: 'System Workflow',
                system: true
            }
        ]
    },
    {
        baseType: 'CONTENT',
        clazz: 'com.dotcms.contenttype.model.type.ImmutableSimpleContentType',
        defaultType: false,
        description: 'Hero image used on homepage and landing pages',
        fixed: false,
        folder: 'SYSTEM_FOLDER',
        folderPath: '/',
        host: 'SYSTEM_HOST',
        iDate: 1489086945734,
        icon: 'image_aspect_ratio',
        id: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
        layout: [
            {
                divider: {
                    clazz: 'com.dotcms.contenttype.model.field.ImmutableRowField',
                    contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                    dataType: 'SYSTEM',
                    fieldContentTypeProperties: [],
                    fieldType: 'Row',
                    fieldTypeLabel: 'Row',
                    fieldVariables: [],
                    fixed: false,
                    forceIncludeInApi: false,
                    iDate: 1529965036000,
                    id: '5dfdad46-49f4-450f-b66d-33460f645aaf',
                    indexed: false,
                    listed: false,
                    modDate: 1703020612000,
                    name: 'fields-0',
                    readOnly: false,
                    required: false,
                    searchable: false,
                    sortOrder: 0,
                    unique: false,
                    variable: 'fields0'
                },
                columns: [
                    {
                        columnDivider: {
                            clazz: 'com.dotcms.contenttype.model.field.ImmutableColumnField',
                            contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                            dataType: 'SYSTEM',
                            fieldContentTypeProperties: [],
                            fieldType: 'Column',
                            fieldTypeLabel: 'Column',
                            fieldVariables: [],
                            fixed: false,
                            forceIncludeInApi: false,
                            iDate: 1529965036000,
                            id: '6ab3fec7-c46b-4c95-b6dd-6f9ea5e2826e',
                            indexed: false,
                            listed: false,
                            modDate: 1703020612000,
                            name: 'fields-1',
                            readOnly: false,
                            required: false,
                            searchable: false,
                            sortOrder: 1,
                            unique: false,
                            variable: 'fields1'
                        },
                        fields: [
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableHostFolderField',
                                contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                                dataType: 'SYSTEM',
                                fieldType: 'Host-Folder',
                                fieldTypeLabel: 'Site or Folder',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1566840730000,
                                id: '3e089676-778a-4f17-905f-7e6b707415b9',
                                indexed: true,
                                listed: false,
                                modDate: 1703020612000,
                                name: 'Host',
                                readOnly: false,
                                required: true,
                                searchable: false,
                                sortOrder: 2,
                                unique: false,
                                variable: 'contentHost'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableTextField',
                                contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                                dataType: 'TEXT',
                                fieldType: 'Text',
                                fieldTypeLabel: 'Text',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1308941149000,
                                id: '5c21daa4-1482-4bc9-9d61-04b42d35a6ee',
                                indexed: true,
                                listed: true,
                                modDate: 1703020612000,
                                name: 'Title',
                                readOnly: false,
                                regexCheck: '[^(<[.\\n]+>)]*',
                                required: true,
                                searchable: true,
                                sortOrder: 3,
                                unique: false,
                                variable: 'title'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableCustomField',
                                contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                                dataType: 'LONG_TEXT',
                                fieldType: 'Custom-Field',
                                fieldTypeLabel: 'Custom Field',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1555426352000,
                                id: '31eb3833-53e6-47cc-af45-221a42a3ebc5',
                                indexed: false,
                                listed: false,
                                modDate: 1703020612000,
                                name: 'styles',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 4,
                                unique: false,
                                values: '<style>\r\n#styles_tag {\r\n    display: none;\r\n}\r\n.field__radio {\r\n    display: flex;\r\n}\r\n.radio {\r\n    margin-right: 20px;\r\n}\r\n.thumbnailDiv {\r\n    border: solid 1px #C5C5C5;\r\n    margin-bottom: 10px;\r\n    width: 100% !important;\r\n}\r\n\r\n.thumbnailDivHover {\r\n    border: solid 1px #161616;\r\n    margin-bottom: 10px;\r\n    width: 100% !important;\r\n}\r\n</style>',
                                variable: 'styles'
                            }
                        ]
                    }
                ]
            },
            {
                divider: {
                    clazz: 'com.dotcms.contenttype.model.field.ImmutableRowField',
                    contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                    dataType: 'SYSTEM',
                    fieldContentTypeProperties: [],
                    fieldType: 'Row',
                    fieldTypeLabel: 'Row',
                    fieldVariables: [],
                    fixed: false,
                    forceIncludeInApi: false,
                    iDate: 1555000294000,
                    id: 'b885d71b-2d6c-40ae-9351-b6d58f3c6704',
                    indexed: false,
                    listed: false,
                    modDate: 1703020612000,
                    name: 'fields-2',
                    readOnly: false,
                    required: false,
                    searchable: false,
                    sortOrder: 5,
                    unique: false,
                    variable: 'fields9'
                },
                columns: [
                    {
                        columnDivider: {
                            clazz: 'com.dotcms.contenttype.model.field.ImmutableColumnField',
                            contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                            dataType: 'SYSTEM',
                            fieldContentTypeProperties: [],
                            fieldType: 'Column',
                            fieldTypeLabel: 'Column',
                            fieldVariables: [],
                            fixed: false,
                            forceIncludeInApi: false,
                            iDate: 1555000294000,
                            id: '92777b44-e53c-4635-b42a-2ce745d10d6c',
                            indexed: false,
                            listed: false,
                            modDate: 1703020612000,
                            name: 'fields-3',
                            readOnly: false,
                            required: false,
                            searchable: false,
                            sortOrder: 6,
                            unique: false,
                            variable: 'fields10'
                        },
                        fields: [
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableCustomField',
                                contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                                dataType: 'LONG_TEXT',
                                defaultValue: '1',
                                fieldType: 'Custom-Field',
                                fieldTypeLabel: 'Custom Field',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1412016703000,
                                id: 'c4712e56-ec64-4795-8613-63dff910b34e',
                                indexed: true,
                                listed: true,
                                modDate: 1703020612000,
                                name: 'Layout',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 7,
                                unique: false,
                                values: "#dotParse('/application/vtl/custom-fields/banner-layout.vtl')",
                                variable: 'layout'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableTextField',
                                contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                                dataType: 'TEXT',
                                fieldType: 'Text',
                                fieldTypeLabel: 'Text',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1582137456000,
                                id: '0eeef3b4-7fc2-45d3-9fda-c99c5b016374',
                                indexed: true,
                                listed: true,
                                modDate: 1703020612000,
                                name: 'Caption',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 8,
                                unique: false,
                                variable: 'caption'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableTextField',
                                contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                                dataType: 'TEXT',
                                fieldType: 'Text',
                                fieldTypeLabel: 'Text',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1562795494000,
                                id: '814af473-c03d-446d-8609-f82b0d67b7c3',
                                indexed: false,
                                listed: false,
                                modDate: 1703020612000,
                                name: 'Button Text',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 9,
                                unique: false,
                                variable: 'buttonText'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableTextField',
                                contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                                dataType: 'TEXT',
                                fieldType: 'Text',
                                fieldTypeLabel: 'Text',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1562795510000,
                                id: 'f959784b-b2e7-4a09-b004-fe3e67e5fbd6',
                                indexed: false,
                                listed: false,
                                modDate: 1703020612000,
                                name: 'Link',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 10,
                                unique: false,
                                variable: 'link'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableCustomField',
                                contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                                dataType: 'LONG_TEXT',
                                defaultValue: '#FFFFFF',
                                fieldType: 'Custom-Field',
                                fieldTypeLabel: 'Custom Field',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1555001286000,
                                id: '9d859b44-18c5-4b3c-b077-e812a945f255',
                                indexed: false,
                                listed: false,
                                modDate: 1703020612000,
                                name: 'Text Color',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 11,
                                unique: false,
                                values: '##SET FIELD VARIABLE NAME TO APPLY PICKER TO\r\n#set($fieldName = "textColor")\r\n#dotParse(\'/application/vtl/custom-fields/color-picker.vtl\')',
                                variable: 'textColor'
                            },
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableTagField',
                                contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                                dataType: 'SYSTEM',
                                fieldType: 'Tag',
                                fieldTypeLabel: 'Tag',
                                fieldVariables: [],
                                fixed: false,
                                forceIncludeInApi: false,
                                iDate: 1567533022000,
                                id: '27499ccb-1bbb-4c02-ab91-c11e01f58ac7',
                                indexed: true,
                                listed: false,
                                modDate: 1703020612000,
                                name: 'Tags',
                                readOnly: false,
                                required: false,
                                searchable: false,
                                sortOrder: 12,
                                unique: false,
                                variable: 'tags'
                            }
                        ]
                    },
                    {
                        columnDivider: {
                            clazz: 'com.dotcms.contenttype.model.field.ImmutableColumnField',
                            contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                            dataType: 'SYSTEM',
                            fieldContentTypeProperties: [],
                            fieldType: 'Column',
                            fieldTypeLabel: 'Column',
                            fieldVariables: [],
                            fixed: false,
                            forceIncludeInApi: false,
                            iDate: 1555000294000,
                            id: 'f735c683-f05e-4138-8056-73d76e80b1aa',
                            indexed: false,
                            listed: false,
                            modDate: 1703020612000,
                            name: 'fields-4',
                            readOnly: false,
                            required: false,
                            searchable: false,
                            sortOrder: 13,
                            unique: false,
                            variable: 'fields11'
                        },
                        fields: [
                            {
                                clazz: 'com.dotcms.contenttype.model.field.ImmutableBinaryField',
                                contentTypeId: '4c441ada-944a-43af-a653-9bb4f3f0cb2b',
                                dataType: 'SYSTEM',
                                fieldType: 'Binary',
                                fieldTypeLabel: 'Binary',
                                fieldVariables: [
                                    {
                                        clazz: 'com.dotcms.contenttype.model.field.ImmutableFieldVariable',
                                        fieldId: 'fff86d86-7908-4922-aaed-a3e8b0c6aae4',
                                        id: '58a97b0a-92b9-4ef6-b12f-df2c05b5cb3d',
                                        key: 'accept',
                                        value: 'image/*'
                                    }
                                ],
                                fixed: false,
                                forceIncludeInApi: false,
                                hint: 'Recommended size 940x350',
                                iDate: 1308941399000,
                                id: 'fff86d86-7908-4922-aaed-a3e8b0c6aae4',
                                indexed: false,
                                listed: false,
                                modDate: 1703020612000,
                                name: 'Image',
                                readOnly: false,
                                required: true,
                                searchable: false,
                                sortOrder: 14,
                                unique: false,
                                variable: 'image'
                            }
                        ]
                    }
                ]
            }
        ],
        modDate: 1703020612000,
        multilingualable: false,
        nEntries: 11,
        name: 'Banner',
        siteName: 'systemHost',
        sortOrder: 0,
        system: false,
        variable: 'Banner',
        versionable: true,
        workflows: [
            {
                archived: false,
                creationDate: 1703026814437,
                defaultScheme: false,
                description: '',
                entryActionId: null,
                id: 'd61a59e1-a49c-46f2-a929-db2b4bfa88b2',
                mandatory: false,
                modDate: 1703020631984,
                name: 'System Workflow',
                system: true
            }
        ]
    }
];

export const CONTENTLETS_MOCK = [
    {
        hostName: 'demo.dotcms.com',
        modDate: '2021-04-08 13:53:32.618',
        imageMetaData: {
            modDate: 1703020595125,
            sha256: '01bed04a0807b45245d38188da3bece44e42fcdd0cf8e8bfe0585e8bd7a61913',
            length: 15613,
            title: 'box-info-2-270x270.jpg',
            version: 20220201,
            isImage: true,
            fileSize: 15613,
            name: 'box-info-2-270x270.jpg',
            width: 270,
            contentType: 'image/jpeg',
            height: 270
        },
        publishDate: '2021-04-08 13:53:32.681',
        description:
            "Snowboarding, once a prime route for teen rebellion, today is definitely mainstream. Those teens — both guys and Shred Bettys, who took up snowboarding in the late '80s and '90s now are riding with their kids.",
        title: 'Snowboarding',
        body: "<p>As with skiing, there are different styles of riding. Free-riding is all-mountain snowboarding on the slopes, in the trees, down the steeps and through the moguls. Freestyle is snowboarding in a pipe or park filled with rails, fun boxes and other features.<br /><br />Snowboarding parks are designed for specific skill levels, from beginner parks with tiny rails hugging the ground to terrain parks with roller-coaster rails, fun boxes and tabletops for more experienced snowboarders.<br /><br />Whether you're a first-timer or already comfortable going lip-to-lip in a pipe, there are classes and special clinics for you at our ski and snowboard resorts. Our resorts offer multiday clinics, so if you're headed to ski this winter, consider wrapping your vacation dates around a snowboarding clinic.</p>",
        baseType: 'CONTENT',
        inode: 'd77576ce-6e3a-4cf3-b412-8e5209f56cae',
        archived: false,
        host: '48190c8c-42c4-46af-8d1a-0cd5db894797',
        working: true,
        locked: false,
        stInode: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
        contentType: 'Activity',
        live: true,
        altTag: 'Snowboarding',
        owner: 'dotcms.org.1',
        imageVersion: '/dA/d77576ce-6e3a-4cf3-b412-8e5209f56cae/image/box-info-2-270x270.jpg',
        identifier: '574f0aec-185a-4160-9c17-6d037b298318',
        image: '/dA/574f0aec-185a-4160-9c17-6d037b298318/image/box-info-2-270x270.jpg',
        imageContentAsset: '574f0aec-185a-4160-9c17-6d037b298318/image',
        urlTitle: 'snowboarding',
        languageId: 1,
        URL_MAP_FOR_CONTENT: '/activities/snowboarding',
        url: '/content.2f6fe5b8-a2cc-4ecb-a868-db632d695fca',
        tags: 'snowboarding,winterenthusiast',
        titleImage: 'image',
        modUserName: 'Admin User',
        urlMap: '/activities/snowboarding',
        hasLiveVersion: true,
        folder: 'SYSTEM_FOLDER',
        hasTitleImage: true,
        sortOrder: 0,
        modUser: 'dotcms.org.1',
        __icon__: 'contentIcon',
        contentTypeIcon: 'paragliding',
        variant: 'DEFAULT'
    },
    {
        hostName: 'demo.dotcms.com',
        modDate: '2020-09-02 16:42:10.049',
        imageMetaData: {
            modDate: 1703020594791,
            sha256: '7e1cf9d3c8c144f592af72658456031c8283bfe4a5ecce3e188c71aa7b1e590e',
            length: 37207,
            title: 'zip-line.jpg',
            version: 20220201,
            isImage: true,
            fileSize: 37207,
            name: 'zip-line.jpg',
            width: 270,
            contentType: 'image/jpeg',
            height: 270
        },
        publishDate: '2020-09-02 16:42:10.101',
        description:
            'Ever wondered what it is like to fly through the forest canopy? Zip-lining ais the best way to explore the forest canopy, where thick branches serve as platforms for the adventurous traveler, more than 100 feet above the forest floor.',
        title: 'Zip-Lining',
        body: '<p>Ever wondered what it is a monkey finds so fascinating about the forest canopy? Costa Rica is a pioneer in canopy exploration, where thick branches serve as platforms for the adventurous traveler, more than 100 feet above the jungle floor. If you&rsquo;re wondering why you&rsquo;d want to head to the top of a tree just to look around, remember that 90% of Costa Rica animals and 50% of plant species in rainforests live in the upper levels of the trees. When you explore that far off the ground, the view is something you&rsquo;ll never forget! A Costa Rica zip line tour, hanging bridges hike, or aerial tram tour are all fantastic ways to take advantage of Costa Rica&rsquo;s stunning forest canopy views.</p>\n<p>Almost anyone of any age and physical condition can enjoy a Costa Rica zip line adventure as it is not strenuous. Secured into a harness and attached to a sturdy cable, you will have the opportunity to fly through the rainforest canopy and experience a bird&rsquo;s eye view of the lively forest below. A Costa Rica zip line is about a five hour adventure that operates rain or shine all year and is led by bilingual guides. For the non-adrenaline junkie, the aerial tram can take you through the rainforest in comfort and safety. Prefer to linger? Hanging bridges offer panoramic views for acres, and an experienced guide will be happy to point out a variety of birds and animals.</p>',
        baseType: 'CONTENT',
        inode: '8df9a375-0386-401c-b5d6-da21c1c5c301',
        archived: false,
        host: '48190c8c-42c4-46af-8d1a-0cd5db894797',
        working: true,
        locked: false,
        stInode: '778f3246-9b11-4a2a-a101-e7fdf111bdad',
        contentType: 'Activity',
        live: true,
        altTag: 'Zip-line',
        owner: 'dotcms.org.1',
        imageVersion: '/dA/8df9a375-0386-401c-b5d6-da21c1c5c301/image/zip-line.jpg',
        identifier: '50757fb4-75df-4e2c-8335-35d36bdb944b',
        image: '/dA/50757fb4-75df-4e2c-8335-35d36bdb944b/image/zip-line.jpg',
        imageContentAsset: '50757fb4-75df-4e2c-8335-35d36bdb944b/image',
        urlTitle: 'zip-lining',
        languageId: 1,
        URL_MAP_FOR_CONTENT: '/activities/zip-lining',
        url: '/content.c17f9c4c-ad14-4777-ae61-334ee6c9fcbf',
        tags: 'ecoenthusiast,zip-lining',
        titleImage: 'image',
        modUserName: 'Admin User',
        urlMap: '/activities/zip-lining',
        hasLiveVersion: true,
        folder: 'SYSTEM_FOLDER',
        hasTitleImage: true,
        sortOrder: 0,
        modUser: 'dotcms.org.1',
        __icon__: 'contentIcon',
        contentTypeIcon: 'paragliding',
        variant: 'DEFAULT'
    }
];

export const INITIAL_STATE_PALETTE_CONTENTTYPE_MOCK: DotPaletteState = {
    contentlets: {
        filter: {
            query: '',
            contentTypeVarName: ''
        },
        items: [],
        totalRecords: 0,
        itemsPerPage: 10
    },
    contenttypes: {
        items: [],
        filter: ''
    },
    status: EditEmaPaletteStoreStatus.LOADED,
    currentPaletteType: PALETTE_TYPES.CONTENTTYPE,
    allowedTypes: []
};

export const INITIAL_STATE_PALETTE_CONTENTLET_MOCK: DotPaletteState = {
    contentlets: {
        filter: {
            query: '',
            contentTypeVarName: 'Test'
        },
        items: CONTENTLETS_MOCK,
        totalRecords: CONTENTLETS_MOCK.length,
        itemsPerPage: 10
    },
    contenttypes: {
        items: [],
        filter: ''
    },
    status: EditEmaPaletteStoreStatus.LOADED,
    currentPaletteType: PALETTE_TYPES.CONTENTLET,
    allowedTypes: []
};
