#!/usr/bin/env node
/**
 * Per-project migration steps other than the Vitest config — FR-005, FR-007.
 *
 * Run AFTER tools/generate-vite-configs.mjs. Like that script, everything here is
 * shaped after what Nx's own generators emit
 * (`nx g @nx/angular:library --unitTestRunner=vitest-analog`), so a migrated project
 * is indistinguishable from a generated one. For each project:
 *
 *   1. tsconfig.spec.json  types/include/files as Nx emits them, and `module:
 *      commonjs` switched off — ts-jest wanted it, an ESM pipeline cannot use it.
 *   2. src/test-setup.ts   Analog's `setupTestBed`, replacing whichever hand-rolled
 *      bootstrap this migration went through.
 *   3. project.json        drop the `test` target; `@nx/vitest` infers it.
 *   4. jest.config.ts      delete.
 *
 * Idempotent: re-running a migrated project is a no-op.
 *
 * Usage: node tools/migrate-project.mjs <project-dir> [...] | --all [--dry-run]
 */

import { readFileSync, writeFileSync, existsSync, rmSync, readdirSync } from 'node:fs';
import { join, resolve } from 'node:path';

const CW = resolve(import.meta.dirname, '..');
const OUT_OF_SCOPE = ['libs/dotcms-webcomponents', 'apps/dotcms-ui-e2e'];

/**
 * Discovery from four sources, because no single one is complete: the plugin's
 * include list, explicit `@nx/jest:jest` executors (five projects use those), and
 * the presence of a jest config or an already-generated vitest config. The last two
 * are what keep this re-runnable after the migration strips nx.json and the targets.
 */
function projects() {
    const found = new Set();

    try {
        const nx = JSON.parse(readFileSync(join(CW, 'nx.json'), 'utf8'));
        const plugin = nx.plugins?.find((p) => typeof p === 'object' && p.plugin === '@nx/jest/plugin');
        for (const g of plugin?.include ?? []) found.add(g.split('/**')[0]);
    } catch {
        /* nx.json already stripped */
    }

    const walk = (rel) => {
        for (const e of readdirSync(join(CW, rel), { withFileTypes: true })) {
            if (e.name === 'node_modules' || e.name.startsWith('.')) continue;
            const child = `${rel}/${e.name}`;
            if (e.isDirectory()) {
                walk(child);
                continue;
            }
            if (e.name === 'jest.config.ts') found.add(rel);
            else if (e.name === 'vite.config.mts' && readFileSync(join(CW, child), 'utf8').includes('GENERATED by tools/generate-vite-configs')) found.add(rel);
            else if (e.name === 'project.json') {
                try {
                    const d = JSON.parse(readFileSync(join(CW, child), 'utf8'));
                    if (d.targets?.test?.executor === '@nx/jest:jest') found.add(rel);
                } catch {
                    /* not ours to fix */
                }
            }
        }
    };
    for (const top of ['libs', 'apps']) walk(top);

    return [...found].filter((d) => !OUT_OF_SCOPE.some((o) => d === o || d.startsWith(`${o}/`))).sort();
}

function migrateTsconfigSpec(dir, dry) {
    const p = join(CW, dir, 'tsconfig.spec.json');
    if (!existsSync(p)) return 'absent';
    const d = JSON.parse(readFileSync(p, 'utf8'));
    const before = JSON.stringify(d);
    const co = (d.compilerOptions ??= {});

    // Exactly what Nx's vitest-analog generator emits, so a migrated spec tsconfig
    // matches a generated one.
    co.types = ['vitest/globals', 'vitest/importMeta', 'vite/client', 'node', 'vitest'];
    d.include = [
        'vite.config.ts',
        'vite.config.mts',
        'vitest.config.ts',
        'vitest.config.mts',
        'src/**/*.test.ts',
        'src/**/*.spec.ts',
        'src/**/*.test.tsx',
        'src/**/*.spec.tsx',
        'src/**/*.d.ts'
    ];
    if (existsSync(join(CW, dir, 'src', 'test-setup.ts'))) d.files = ['src/test-setup.ts'];

    // `module: commonjs` is what ts-jest wanted and an ESM pipeline cannot use:
    // extensionless relative imports stop resolving and Node reports
    // `Cannot find module './define-adapter'`, naming the file and not the module
    // system. Measured on sdk-ai: 0 tests running before, 58/58 after.
    if (co.module === 'commonjs') {
        co.module = 'esnext';
        co.moduleResolution = 'bundler';
    }

    if (JSON.stringify(d) === before) return 'unchanged';
    if (!dry) writeFileSync(p, `${JSON.stringify(d, null, 4)}\n`);
    return 'updated';
}

/**
 * Rewrite the TestBed bootstrap to Analog's supported one, as Nx's generator emits it.
 *
 * TARGETED replacements, not one span. An earlier version matched everything between
 * the zone import and the bootstrap call with `[\s\S]*?`, which swallowed any import
 * sitting between them — it deleted
 * `import { setupResizeObserverMock } from '@dotcms/utils-testing'` while leaving the
 * call, and 228 of dotcms-ui's suites died on `setupResizeObserverMock is not
 * defined`. A greedy regex across import statements is not a safe edit.
 *
 * What the replacement buys: `@angular/compiler` must be imported before anything
 * touches the TestBed (JIT needs it; it was missing from 36 of 40 setups), and
 * `setupTestBed` installs the Vitest zone patch `fakeAsync` depends on — zone.js
 * patches only jasmine/mocha/jest, so a hand-rolled `import 'zone.js/testing'` leaves
 * every fakeAsync test failing with "Expected to be running in 'ProxyZone'".
 */
function migrateTestSetup(dir, dry) {
    const p = join(CW, dir, 'src', 'test-setup.ts');
    if (!existsSync(p)) return 'absent';
    let s = readFileSync(p, 'utf8');
    const before = s;

    // 1. Drop the old bootstrap IMPORT lines, one line at a time.
    s = s.replace(/^import\s*\{\s*setupZoneTestEnv\s*\}\s*from\s*'jest-preset-angular\/setup-env\/zone';[ \t]*\r?\n/m, '');
    // setup-zone is KEPT — it is the piece that patches Vitest for zone.js.
    // NOT stripping the zone imports: they are required (see the head block below).
    s = s.replace(/^import\s*\{\s*getTestBed\s*\}\s*from\s*'@angular\/core\/testing';[ \t]*\r?\n/m, '');
    s = s.replace(/^import\s*\{[^}]*platformBrowserTesting[^}]*\}\s*from\s*'@angular\/platform-browser\/testing';[ \t]*\r?\n/m, '');

    // 2. Replace the bootstrap CALL, wherever it sits, keeping its options.
    const call = /(?:\/\/[^\n]*\r?\n)*(?:setupZoneTestEnv|getTestBed\(\)\.initTestEnvironment)\([\s\S]*?\);[ \t]*\r?\n?/;
    if (call.test(s)) {
        s = s.replace(call, "setupTestBed({ zoneless: false });\n");
    } else if (!s.includes('setupTestBed(')) {
        return 'no-bootstrap';
    }

    // 3. Prepend the imports Nx's generator puts first, without duplicating them.
    const head = [];
    // Analog's setup-zone FIRST, and it replaces raw `import 'zone.js/testing'`.
    //
    // Three bootstraps were measured. Nx's generated `setupTestBed` alone leaves 88
    // "zone-testing.js is needed for the fakeAsync() test helper" errors, and because
    // those fail at file level the projects report fewer tests with ZERO failures —
    // the silent-skip shape. Raw zone.js imports fix the loading (96% of the baseline
    // running) but do not patch Vitest, so 1,653 tests then fail with
    // "Expected to be running in 'ProxyZone'". setup-zone does both: on data-access,
    // ProxyZone errors went 104 -> 2 and 850 of 851 tests pass.
    //
    // So it is setup-zone AND setupTestBed, not either one.
    if (!s.includes('@analogjs/vitest-angular/setup-zone')) head.push("import '@analogjs/vitest-angular/setup-zone';");
    if (!/^import '@angular\/compiler';/m.test(s)) head.push("import '@angular/compiler';");
    if (!s.includes('@analogjs/vitest-angular/setup-snapshots')) head.push("import '@analogjs/vitest-angular/setup-snapshots';");
    if (!s.includes("from '@analogjs/vitest-angular/setup-testbed'")) {
        head.push("import { setupTestBed } from '@analogjs/vitest-angular/setup-testbed';");
    }
    if (head.length) {
        // Insert at the top of the FIRST import group, not at the very top of the
        // file. Prepending ahead of the leading /* eslint-disable */ block left a
        // blank line inside the import group and eslint's import/order rejected it,
        // failing the pre-commit hook.
        const firstImport = /^import\s/m.exec(s);
        if (firstImport) {
            const at = firstImport.index;
            s = `${s.slice(0, at)}${head.join('\n')}\n${s.slice(at)}`;
        } else {
            s = `${head.join('\n')}\n${s}`;
        }
    }

    // Collapse any duplicate compiler import a previous pass may have left.
    s = s.replace(/(^import '@angular\/compiler';\r?\n)(?=[\s\S]*^import '@angular\/compiler';\r?\n)/m, '');

    // Collapse blank lines that fall BETWEEN import statements. Inserting into the
    // first import group can leave a pre-existing blank line inside it, and the
    // repo's import/order rule rejects that — it failed the pre-commit hook on four
    // setups, and `eslint --fix` does not repair this particular case.
    const importLines = s.split('\n');
    const idx = importLines.map((l, i) => (l.startsWith('import ') ? i : -1)).filter((i) => i >= 0);
    if (idx.length > 1) {
        const [first, last] = [idx[0], idx[idx.length - 1]];
        s = [
            ...importLines.slice(0, first),
            ...importLines.slice(first, last + 1).filter((l) => l.trim() !== ''),
            ...importLines.slice(last + 1)
        ].join('\n');
    }

    if (s === before) return 'unchanged';
    if (!dry) writeFileSync(p, s);
    return 'updated';
}

/**
 * Drop the `test` target and let `@nx/vitest` infer it, as in a generated project.
 *
 * An earlier version wrote an explicit `nx:run-commands` target with
 * `cwd: {workspaceRoot}`, because the config had `root` at the workspace and the
 * inferred target's project-directory cwd broke alias resolution. With `root:
 * __dirname` — Nx's own shape — cwd is no longer load-bearing, so the workaround
 * goes away together with the thing that required it.
 */
function migrateProjectJson(dir, dry) {
    const p = join(CW, dir, 'project.json');
    if (!existsSync(p)) return 'absent';
    const d = JSON.parse(readFileSync(p, 'utf8'));
    if (!d.targets?.test) return 'unchanged';
    delete d.targets.test;
    if (!dry) writeFileSync(p, `${JSON.stringify(d, null, 4)}\n`);
    return 'updated';
}

function removeJestConfig(dir, dry) {
    const p = join(CW, dir, 'jest.config.ts');
    if (!existsSync(p)) return 'absent';
    if (!dry) rmSync(p);
    return 'deleted';
}

const args = process.argv.slice(2);
const dry = args.includes('--dry-run');
const dirs = args.includes('--all') ? projects() : args.filter((a) => !a.startsWith('--'));

if (dirs.length === 0) {
    console.error('usage: migrate-project.mjs <project-dir> [...] | --all [--dry-run]');
    process.exit(2);
}

for (const dir of dirs) {
    const r = {
        tsconfig: migrateTsconfigSpec(dir, dry),
        setup: migrateTestSetup(dir, dry),
        project: migrateProjectJson(dir, dry),
        jest: removeJestConfig(dir, dry)
    };
    console.log(`${dir.padEnd(44)} tsconfig=${r.tsconfig} setup=${r.setup} project=${r.project} jest=${r.jest}`);
}
console.log(`\n${dirs.length} project(s)${dry ? ' (dry run)' : ''}`);
