/// <reference types="vitest" />
import angular from '@analogjs/vite-plugin-angular';
import { defineConfig } from 'vite';
import tsconfigPaths from 'vite-tsconfig-paths';

import { resolve } from 'path';

/**
 * GENERATED by tools/generate-vite-configs.mjs from this project's jest.config.ts.
 * Regenerate rather than hand-editing where possible; see research.md R-16 for why
 * each block is here and which failure it prevents.
 */
const WORKSPACE = resolve(import.meta.dirname, '../../..');
const PROJECT = 'libs/sdk/uve';

export default defineConfig({
    // The workspace, not the project: sibling libs resolve through tsconfig paths to
    // their TypeScript source, and the Angular plugin only compiles under root.
    root: WORKSPACE,
    plugins: [
        angular({
            tsconfig: resolve(import.meta.dirname, 'tsconfig.spec.json'),
            workspaceRoot: WORKSPACE
        }),
        tsconfigPaths({ root: WORKSPACE, projects: ['tsconfig.base.json', `${PROJECT}/tsconfig.spec.json`] })
    ],
    // No mainFields here, deliberately. Setting it to ['module'] — copied from the
    // SDK *build* configs, where it is correct — makes Vite ignore packages that
    // declare only a main field, including @analogjs/vitest-angular. Resolution falls
    // through to a bogus root-relative path and takes the whole project down with an
    // error that names the package but not the cause (research R-20).
    resolve: {
    },
    test: {
        root: WORKSPACE,
        globals: true,
        // Carried across from jest.config.ts (FR-007). Without pinning it the project
        // would silently adopt Vitest's default instead.
        environment: 'jsdom',
        include: [`${PROJECT}/src/**/*.spec.ts`, `${PROJECT}/src/**/*.spec.tsx`, `${PROJECT}/src/**/*.test.ts`, `${PROJECT}/src/**/*.test.tsx`],
        // Jest gave each spec file a fresh module registry; state this rather than
        // inherit it, so the semantics the specs were written under stay explicit.
        isolate: true,
        server: {
            // Deliberately true, not a package list. The list started as Angular + Spectator +
            // zone.js, then needed PrimeNG, then @ngrx, then each project's own
            // transformIgnorePatterns chain — and dotcms-ui still produced 420 NG0203
            // errors from something not on it. Every package that touches
            // @angular/core must resolve to the same instance, and enumerating them
            // is a losing game: one missed package fails ~200 tests with an error
            // that names Angular, not the package. Inlining everything is slower and
            // correct; FR-017 sets no performance threshold.
            //
            // This project's jest.config.ts listed: (no transformIgnorePatterns)
            deps: { inline: true }
        },
        reporters: ['default', 'github-actions', ['junit', { outputFile: 'target/core-web-reports/sdk-uve.xml' }]],
        coverage: {
            provider: 'v8',
            reporter: ['html', 'lcov', 'text'],
            reportsDirectory: 'coverage/libs/sdk/uve'
        }
    }
});
