/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface DotCheckbox {
    'hint': string;
    'label': string;
    'options': string;
    'value': string;
  }
  interface DotCheckboxAttributes extends StencilHTMLAttributes {
    'hint'?: string;
    'label'?: string;
    'onOnChange'?: (event: CustomEvent) => void;
    'options'?: string;
    'value'?: string;
  }

  interface DotDropdown {
    'hint': string;
    'label': string;
    'options': string;
    'value': string;
  }
  interface DotDropdownAttributes extends StencilHTMLAttributes {
    'hint'?: string;
    'label'?: string;
    'onOnChange'?: (event: CustomEvent) => void;
    'options'?: string;
    'value'?: string;
  }

  interface DotTextfield {
    'hint': string;
    'label': string;
    'placeholder': string;
    'readOnly': string;
    'regexcheck': string;
    'required': boolean;
    'value': string;
  }
  interface DotTextfieldAttributes extends StencilHTMLAttributes {
    'hint'?: string;
    'label'?: string;
    'onOnChange'?: (event: CustomEvent) => void;
    'placeholder'?: string;
    'readOnly'?: string;
    'regexcheck'?: string;
    'required'?: boolean;
    'value'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'DotCheckbox': Components.DotCheckbox;
    'DotDropdown': Components.DotDropdown;
    'DotTextfield': Components.DotTextfield;
  }

  interface StencilIntrinsicElements {
    'dot-checkbox': Components.DotCheckboxAttributes;
    'dot-dropdown': Components.DotDropdownAttributes;
    'dot-textfield': Components.DotTextfieldAttributes;
  }


  interface HTMLDotCheckboxElement extends Components.DotCheckbox, HTMLStencilElement {}
  var HTMLDotCheckboxElement: {
    prototype: HTMLDotCheckboxElement;
    new (): HTMLDotCheckboxElement;
  };

  interface HTMLDotDropdownElement extends Components.DotDropdown, HTMLStencilElement {}
  var HTMLDotDropdownElement: {
    prototype: HTMLDotDropdownElement;
    new (): HTMLDotDropdownElement;
  };

  interface HTMLDotTextfieldElement extends Components.DotTextfield, HTMLStencilElement {}
  var HTMLDotTextfieldElement: {
    prototype: HTMLDotTextfieldElement;
    new (): HTMLDotTextfieldElement;
  };

  interface HTMLElementTagNameMap {
    'dot-checkbox': HTMLDotCheckboxElement
    'dot-dropdown': HTMLDotDropdownElement
    'dot-textfield': HTMLDotTextfieldElement
  }

  interface ElementTagNameMap {
    'dot-checkbox': HTMLDotCheckboxElement;
    'dot-dropdown': HTMLDotDropdownElement;
    'dot-textfield': HTMLDotTextfieldElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
